PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS game_runs (id TEXT NOT NULL,user_id TEXT NOT NULL,device_id TEXT NOT NULL,device_label TEXT NOT NULL DEFAULT '',game TEXT NOT NULL,mode TEXT NOT NULL,state_json TEXT NOT NULL DEFAULT '',revision INTEGER NOT NULL DEFAULT 0,score INTEGER NOT NULL DEFAULT 0,max_tile INTEGER NOT NULL DEFAULT 0,rebirths INTEGER NOT NULL DEFAULT 0,board_total INTEGER NOT NULL DEFAULT 0,board_rows INTEGER NOT NULL DEFAULT 0,board_cols INTEGER NOT NULL DEFAULT 0,lives INTEGER NOT NULL DEFAULT 0,used_lives INTEGER NOT NULL DEFAULT 0,moves INTEGER NOT NULL DEFAULT 0,active_ms INTEGER NOT NULL DEFAULT 0,review_until INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'playing',created_at INTEGER NOT NULL,last_checkpoint_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,PRIMARY KEY(id,user_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS room_invites (token_hash TEXT PRIMARY KEY,room_id TEXT NOT NULL,created_by TEXT NOT NULL,created_at INTEGER NOT NULL,expires_at INTEGER NOT NULL,FOREIGN KEY(room_id) REFERENCES rooms(id) ON DELETE CASCADE,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS room_bans (room_id TEXT NOT NULL,user_id TEXT NOT NULL,banned_by TEXT NOT NULL,created_at INTEGER NOT NULL,PRIMARY KEY(room_id,user_id),FOREIGN KEY(room_id) REFERENCES rooms(id) ON DELETE CASCADE,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS runs_user_game ON game_runs(user_id,game,mode,updated_at DESC);
CREATE INDEX IF NOT EXISTS runs_game_score ON game_runs(game,mode,score DESC);
CREATE INDEX IF NOT EXISTS members_user ON room_members(user_id,joined_at DESC);
CREATE INDEX IF NOT EXISTS invites_room ON room_invites(room_id,expires_at);
INSERT OR IGNORE INTO game_runs(id,user_id,device_id,device_label,game,mode,state_json,revision,score,max_tile,rebirths,board_total,board_rows,board_cols,lives,used_lives,moves,active_ms,review_until,status,created_at,last_checkpoint_at,updated_at)
SELECT 'legacy-'||user_id||'-'||device_id||'-'||game||'-'||mode,user_id,device_id,'Legacy device',game,mode,'',0,score,max_tile,0,board_total,board_rows,board_cols,lives,used_lives,moves,active_ms,review_until,status,updated_at,updated_at,updated_at FROM (SELECT gs.*,ROW_NUMBER() OVER(PARTITION BY user_id,device_id,game,mode ORDER BY score DESC,updated_at ASC) rank FROM game_scores gs) WHERE rank=1;
