import{flyLanguage,playSlap,showFlyMeme}from'./fly-engine.js';

const ONLINE='https://zhanat-arch.github.io/Portable-Tests/modules/fly-game.html';
const TEXT={
  ru:{home:'Главная',badge:'МЕМНАЯ ПОДСТАВА · 18+',title:'Муха-',accent:'наебщица',lead:'Отправьте другу правдоподобный «результат теста». Пока человек читает, на экран садится муха — дальше всё решает инстинкт.',start:'Проверить на себе',how:'Как это работает',steps:['Человек открывает ваш «результат»','Через пару секунд прилетает обычная муха','После поимки раскрывается прикол','Кнопка «Отправить другому» продолжает цепочку'],fakeKicker:'РЕЗУЛЬТАТ ТЕСТА',fakeNote:'Сравнение рассчитано по вашим ответам. Результат сохранён только на устройстве.',wait:'Секунду, загружаем подробности…',tired:'Устала! Жми сейчас!',caught:'Тебя подставили 😂',stats:'Но результат настоящий',time:'Поймал муху за',attempts:'Попыток',send:'Отправить другому',choose:'Выберите приманку для следующего человека',again:'Попробовать ещё раз',shareTitle:'Бро, зацени мой результат 😂',copied:'Ссылка-подстава скопирована',shareSafe:'Уйдёт только ссылка на игру — ваши личные данные не передаются.',baitReaction:'Тест реакции',baitReactionText:'Я поймал за {value} сек. У тебя быстрее?',baitMatch:'Тест совпадения',baitMatchText:'У нас совпадение {value}%. Проверь, сколько у тебя.',baitFocus:'Тест внимательности',baitFocusText:'Моя внимательность — {value}%. А твоя?'},
  kk:{home:'Басты бет',badge:'МЕМ ӘЗІЛ · 18+',title:'Айлакер',accent:'шыбын',lead:'Досыңызға шынайы көрінетін «тест нәтижесін» жіберіңіз. Оқып отырғанда экранға шыбын қонады.',start:'Өзім тексеремін',how:'Қалай жұмыс істейді',steps:['Адам сіздің «нәтижеңізді» ашады','Бірнеше секундтан кейін шыбын ұшады','Ұстаған соң әзіл ашылады','«Басқа адамға жіберу» тізбекті жалғастырады'],fakeKicker:'ТЕСТ НӘТИЖЕСІ',fakeNote:'Салыстыру жауаптарыңыз бойынша есептелді. Нәтиже тек құрылғыда сақталады.',wait:'Толық нәтижені жүктеп жатырмыз…',tired:'Шаршады! Қазір басыңыз!',caught:'Сізді алдап кетті 😂',stats:'Бірақ нәтиже шынайы',time:'Шыбынды ұстау уақыты',attempts:'Әрекет саны',send:'Басқа адамға жіберу',choose:'Келесі адамға қызық тақырып таңдаңыз',again:'Тағы көру',shareTitle:'Менің нәтижеме қарашы 😂',copied:'Сілтеме көшірілді',shareSafe:'Тек ойын сілтемесі жіберіледі. Жеке деректер берілмейді.',baitReaction:'Реакция тесті',baitReactionText:'Мен {value} секундта ұстадым. Сіз жылдамсыз ба?',baitMatch:'Ұқсастық тесті',baitMatchText:'Біздің ұқсастығымыз {value}%. Сізде қанша?',baitFocus:'Зейін тесті',baitFocusText:'Менің зейінім — {value}%. Ал сіздікі?'},
  en:{home:'Home',badge:'MEME PRANK · 18+',title:'The trickster',accent:'fly',lead:'Send a believable “test result”. While your friend reads, a fly lands on the screen — instinct does the rest.',start:'Try it on me',how:'How it works',steps:['They open your “result”','An ordinary fly appears after a moment','Catching it reveals the joke','“Send to someone else” keeps the chain going'],fakeKicker:'TEST RESULT',fakeNote:'The comparison is based on your answers. The result stays on this device.',wait:'Loading the details…',tired:'It is tired — tap now!',caught:'You got pranked 😂',stats:'But this result is real',time:'You caught it in',attempts:'Attempts',send:'Send to someone else',choose:'Pick a lure for the next person',again:'Try again',shareTitle:'Hey, check my result 😂',copied:'Prank link copied',shareSafe:'Only the game link is shared. No personal data is included.',baitReaction:'Reaction test',baitReactionText:'I caught it in {value}s. Can you beat me?',baitMatch:'Match test',baitMatchText:'We match {value}%. Check yours.',baitFocus:'Focus test',baitFocusText:'My focus score is {value}%. What is yours?'},
  fr:{home:'Accueil',badge:'PIÈGE MÈME · 18+',title:'La mouche',accent:'farceuse',lead:'Envoyez un « résultat de test » crédible. Pendant la lecture, une mouche se pose sur l’écran.',start:'Tester sur moi',how:'Comment ça marche',steps:['La personne ouvre votre « résultat »','Une mouche apparaît après un instant','La capture révèle la blague','« Envoyer à une autre personne » relance la chaîne'],fakeKicker:'RÉSULTAT DU TEST',fakeNote:'La comparaison repose sur vos réponses. Le résultat reste sur cet appareil.',wait:'Chargement des détails…',tired:'Elle fatigue — touchez maintenant !',caught:'Vous êtes tombé dans le piège 😂',stats:'Mais ce résultat est réel',time:'Mouche attrapée en',attempts:'Tentatives',send:'Envoyer à une autre personne',choose:'Choisissez une accroche pour la prochaine personne',again:'Recommencer',shareTitle:'Regarde mon résultat 😂',copied:'Lien-piège copié',shareSafe:'Seul le lien du jeu est partagé. Aucune donnée personnelle.',baitReaction:'Test de réaction',baitReactionText:'Je l’ai attrapée en {value}s. Plus rapide ?',baitMatch:'Test de compatibilité',baitMatchText:'Notre score commun est {value} %. Vérifiez le vôtre.',baitFocus:'Test d’attention',baitFocusText:'Mon attention atteint {value} %. Et la vôtre ?'}
};
const lang=flyLanguage(),L=TEXT[lang]||TEXT.ru,params=new URLSearchParams(location.search),validBaits=['reaction','match','focus'];
let bait=validBaits.includes(params.get('bait'))?params.get('bait'):null,fly=null,frame=0,spriteTimer=0,attempts=0,startedAt=0,tired=false,chosen='reaction';
const WALK_FRAMES=['../assets/fly-sprite.png','../assets/fly-sprite-walk2.png'],GROOM_FRAMES=['../assets/fly-sprite.png','../assets/fly-sprite-groom.png'];
const app=document.querySelector('#app'),fmt=(s,v)=>s.replaceAll('{value}',v),baitCopy=(id,value)=>({reaction:[L.baitReaction,fmt(L.baitReactionText,value)],match:[L.baitMatch,fmt(L.baitMatchText,value)],focus:[L.baitFocus,fmt(L.baitFocusText,value)]}[id]);

function header(){return `<header class="top"><a class="brand" href="../index.html"><span class="mark">🪰</span><span>Portable Tests</span></a><div class="tools"><a href="../index.html">← ${L.home}</a><select id="lang" aria-label="Language"><option>RU</option><option>KK</option><option>EN</option><option>FR</option></select></div></header>`}
function bindLanguage(){const select=document.querySelector('#lang');if(!select)return;select.value=lang.toUpperCase();select.onchange=e=>{localStorage.setItem('pt.lang',e.target.value.toLowerCase());location.reload()}}
function landing(){document.body.className='';document.title=`${L.title} ${L.accent} · Portable Tests`;app.innerHTML=`${header()}<main><section class="hero"><div class="hero-copy"><div class="eyebrow">${L.badge}</div><h1>${L.title}<em>${L.accent}</em></h1><p>${L.lead}</p><button class="primary" id="start">${L.start} →</button></div><div class="hero-art"><img src="../assets/fly-meme.webp" alt=""></div></section><section class="how"><div class="eyebrow">${L.how}</div><div class="step-grid">${L.steps.map((s,i)=>`<article><b>0${i+1}</b><p>${s}</p></article>`).join('')}</div></section></main>`;bindLanguage();document.querySelector('#start').onclick=()=>{history.replaceState(null,'',`${location.pathname}?bait=reaction&demo=1`);bait='reaction';prank()}}
function fakeValue(){const supplied=params.get('value');if(bait==='reaction')return supplied&&/^\d+(\.\d)?$/.test(supplied)?supplied:'4.8';return supplied&&/^\d{2}$/.test(supplied)?supplied:String(86+Math.floor(Math.random()*11))}
function prank(){document.body.className='prank-mode';attempts=0;tired=false;const value=fakeValue(),[title,text]=baitCopy(bait,value);document.title=`${title} · Portable Tests`;app.innerHTML=`${header()}<main class="prank-page"><div class="result-kicker">${L.fakeKicker}</div><section class="fake-result"><div class="fake-icon">${bait==='reaction'?'⚡':bait==='match'?'♡':'◎'}</div><p>${title}</p><h1>${text}</h1><div class="fake-score">${bait==='reaction'?`${value}s`:`${value}%`}</div><small>🔒 ${L.fakeNote}</small></section><p class="loading-line"><i></i>${L.wait}</p></main>`;bindLanguage();startedAt=performance.now();setTimeout(spawnFly,4000)}
function animateSprite(frames,delay){clearInterval(spriteTimer);let index=0,img=fly?.querySelector('img');if(!img)return;img.src=frames[0];spriteTimer=setInterval(()=>{if(!fly)return clearInterval(spriteTimer);img.src=frames[++index%frames.length]},delay)}
function spawnFly(){if(fly)return;fly=document.createElement('button');fly.type='button';fly.className='prank-fly';fly.innerHTML='<img src="../assets/fly-sprite.png" alt="">';fly.setAttribute('aria-label','fly');fly.addEventListener('pointerdown',hit);document.body.appendChild(fly);fly.p={x:innerWidth*.62,y:Math.min(innerHeight*.45,360),vx:2.8,vy:2.1,phase:Math.random()*6};animateSprite(WALK_FRAMES,115);frame=requestAnimationFrame(move);window.ptAnalytics?.track('fly_prank_spawn',{bait})}
function move(){if(!fly)return;const p=fly.p;if(!tired){p.phase+=.045;p.vx+=Math.sin(p.phase*1.7)*.035;p.vy+=Math.cos(p.phase*1.25)*.035;const speed=Math.hypot(p.vx,p.vy),target=3.7;p.vx=p.vx/speed*(speed*.94+target*.06);p.vy=p.vy/speed*(speed*.94+target*.06);p.x+=p.vx;p.y+=p.vy;if(p.x<5||p.x>innerWidth-60)p.vx*=-1;if(p.y<65||p.y>innerHeight-75)p.vy*=-1;p.x=Math.max(5,Math.min(innerWidth-60,p.x));p.y=Math.max(65,Math.min(innerHeight-75,p.y))}const angle=Math.atan2(p.vy,p.vx)*180/Math.PI+90;fly.style.transform=`translate3d(${p.x}px,${p.y}px,0) rotate(${angle}deg)`;frame=requestAnimationFrame(move)}
function dodge(){const p=fly.p,turn=(.9+Math.random()*1.5)*(Math.random()>.5?1:-1),angle=Math.atan2(p.vy,p.vx)+turn,speed=5.3+Math.random()*1.8;p.vx=Math.cos(angle)*speed;p.vy=Math.sin(angle)*speed;p.phase=Math.random()*6}
function hit(e){e.preventDefault();e.stopPropagation();attempts++;if(attempts<4){dodge();return}if(!tired){tired=true;fly.classList.add('tired');animateSprite(GROOM_FRAMES,210);const hint=document.createElement('div');hint.className='fly-hint';hint.textContent=L.tired;document.body.appendChild(hint);hint.style.left=`${Math.max(8,Math.min(innerWidth-190,fly.p.x-60))}px`;hint.style.top=`${Math.max(55,fly.p.y-50)}px`;setTimeout(()=>hint.remove(),1600);return}const seconds=((performance.now()-startedAt)/1000).toFixed(1);cancelAnimationFrame(frame);clearInterval(spriteTimer);fly.remove();fly=null;playSlap();showFlyMeme({duration:5000,onClose:()=>result(seconds)})}
function result(seconds){document.body.className='';window.ptAnalytics?.track('fly_prank_caught',{attempts,seconds:Number(seconds)});app.innerHTML=`${header()}<main class="revenge-page"><section class="revenge-card"><div class="eyebrow">${L.caught}</div><h1>${L.stats}</h1><div class="real-stats"><div><strong>${seconds}s</strong><span>${L.time}</span></div><div><strong>${attempts}</strong><span>${L.attempts}</span></div></div><h2>${L.choose}</h2><div class="bait-list">${validBaits.map((id,i)=>{const sample=id==='reaction'?seconds:String(88+i*3),copy=baitCopy(id,sample);return `<button class="bait ${id===chosen?'active':''}" data-bait="${id}"><b>${copy[0]}</b><span>${copy[1]}</span></button>`}).join('')}</div><button class="primary revenge" id="share">📲 ${L.send}</button><button class="secondary" id="again">↻ ${L.again}</button><p class="share-safe">🔒 ${L.shareSafe}</p></section></main>`;bindLanguage();document.querySelectorAll('[data-bait]').forEach(button=>button.onclick=()=>{chosen=button.dataset.bait;document.querySelectorAll('[data-bait]').forEach(x=>x.classList.toggle('active',x===button))});document.querySelector('#share').onclick=()=>shareTrap(seconds);document.querySelector('#again').onclick=prank}
async function shareTrap(seconds){const value=chosen==='reaction'?seconds:String(87+Math.floor(Math.random()*10)),copy=baitCopy(chosen,value),url=`${ONLINE}?bait=${chosen}&value=${encodeURIComponent(value)}`,data={title:L.shareTitle,text:copy[1],url};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(`${data.text}\n${url}`);alert(L.copied)}}catch(error){if(error.name!=='AbortError')console.error(error)}window.ptAnalytics?.track('fly_prank_share',{bait:chosen})}

addEventListener('pagehide',()=>{cancelAnimationFrame(frame);clearInterval(spriteTimer);fly?.remove()});bait?prank():landing();
