/* PortHub adaptation of Gabriele Cirulli's 2048 (MIT). The board movement
   follows the upstream game's rules; UI, lives, saves and room client are new. */
(()=>{
'use strict';
const LANGS=['ru','kk','en','fr'],SAVE_KEY='ph.2048.state.v1',BEST_KEY='ph.2048.best.v1',ACH_KEY='ph.achievements.v1',SETTINGS_KEY='ph.2048.settings.v1',PROFILE_KEY='ph.player.v1',ROOM_KEY='ph.2048.room.v1';
const API='https://api.porthub.fyi/v1';
const SUPPORT={boosty:'https://boosty.to/zhanat-arch',kofi:'https://ko-fi.com/zhanat_arch'};
const REVIEW={
ru:{title:'⚠️ Подозрительно высокий результат!',text:'У нас нет жёсткого античита, но этот скачок выглядит, мягко говоря, дико. Проверьте своего дружбана — возможно, он читерит или двигает плитки со скоростью робота.'},
kk:{title:'⚠️ Күдік тудыратын жоғары нәтиже!',text:'Қатаң античит жоқ, бірақ бұл секіріс тым ерекше көрінеді. Досыңызды тексеріңіз — мүмкін ол робот жылдамдығымен ойнайды.'},
en:{title:'⚠️ Suspiciously high score!',text:'There is no heavy-handed anti-cheat here, but that jump looks wild. Check on your friend—they may be cheating or moving tiles at robot speed.'},
fr:{title:'⚠️ Score étrangement élevé !',text:'Il n’y a pas d’anticheat strict, mais cette progression paraît folle. Vérifiez votre ami : il triche peut-être ou joue à la vitesse d’un robot.'}
};
const T={
ru:{back:'Назад',score:'Счёт',best:'Рекорд',time:'Время',lives:'Жизни',playing:'Игра продолжается',saved:'Сохранено на устройстве',menu:'Меню',room:'Комната друзей',invite:'Пригласить друга',rating:'Рейтинг друзей',share:'Поделиться игрой',newGame:'Новая игра',rules:'Как играть',settings:'Звук и вибрация',sound:'Звук',vibration:'Вибрация',login:'Войти через Google',soon:'Скоро · прогресс на всех устройствах',close:'Закрыть',confirmNew:'Начать новую игру?',confirmText:'Текущее поле будет заменено. Лучший рекорд и достижения сохранятся.',cancel:'Отмена',start:'Начать',gameOver:'Ходы закончились',gameOverText:'Все три жизни использованы. Рекорд сохранён.',again:'Играть ещё',lifeUsed:'Жизнь спасла игру: две маленькие плитки сгорели',achievement:'Новое достижение',coffeeTitle:'Здесь могла быть назойливая реклама',coffeeText:'Но пока вместо неё — короткая просьба поддержать PortHub. Если игра затянула, можете угостить разработчика кофе или просто поделиться игрой с друзьями. Оба варианта действительно помогают проекту расти 🙂',boosty:'Поддержать через Boosty',kofi:'Поддержать через Ko-fi',continue:'Продолжить через {n} сек.',continueNow:'Продолжить',createInvite:'Создать комнату и пригласить',shareText:'Я играю в 2048 на PortHub. Три жизни — попробуй побить мой рекорд!',copied:'Ссылка на игру скопирована',roomName:'Название комнаты',yourName:'Ваше имя',createRoom:'Создать комнату',roomOffline:'Комнаты друзей почти готовы',roomOfflineText:'Игра уже работает, а общий рейтинг включится после подключения PortHub Cloud. Место для него подготовлено.',retry:'Проверить подключение',leaderEmpty:'Пригласите друзей — здесь появятся их рекорды.',updated:'обновлено {n}',rulesText:'Соединяйте одинаковые плитки свайпами или стрелками. Когда ходов не останется, одна из трёх жизней удалит две самые маленькие плитки. После третьего спасения следующий тупик завершит игру.',achievements:'Достижения',noScroll:'Свайпы работают прямо по полю.',syncLocal:'Локальная игра',online:'Облако подключено',statusLives:'{score} очков · {tile} · {lives} · играет',playerFallback:'Игрок'},
kk:{back:'Артқа',score:'Ұпай',best:'Рекорд',time:'Уақыт',lives:'Өмір',playing:'Ойын жалғасуда',saved:'Құрылғыда сақталды',menu:'Мәзір',room:'Достар бөлмесі',invite:'Досты шақыру',rating:'Достар рейтингі',share:'Ойынмен бөлісу',newGame:'Жаңа ойын',rules:'Қалай ойнау керек',settings:'Дыбыс пен діріл',sound:'Дыбыс',vibration:'Діріл',login:'Google арқылы кіру',soon:'Жақында · барлық құрылғыдағы прогресс',close:'Жабу',confirmNew:'Жаңа ойын басталсын ба?',confirmText:'Қазіргі алаң ауыстырылады. Рекорд пен жетістіктер сақталады.',cancel:'Бас тарту',start:'Бастау',gameOver:'Жүріс қалмады',gameOverText:'Үш өмір де қолданылды. Рекорд сақталды.',again:'Тағы ойнау',lifeUsed:'Өмір ойынды сақтады: екі кіші плитка жойылды',achievement:'Жаңа жетістік',coffeeTitle:'Мұнда мазалайтын жарнама болуы мүмкін еді',coffeeText:'Әзірше оның орнына PortHub-ты қолдау туралы қысқа өтініш. Ойын ұнаса, әзірлеушіні кофемен қуанта аласыз немесе ойынды достарыңызбен бөлісіңіз 🙂',boosty:'Boosty арқылы қолдау',kofi:'Ko-fi арқылы қолдау',continue:'{n} сек. кейін жалғастыру',continueNow:'Жалғастыру',createInvite:'Бөлме құрып, шақыру',shareText:'Мен PortHub-та 2048 ойнап жатырмын. Үш өмір бар — рекордымнан асып көр!',copied:'Ойын сілтемесі көшірілді',roomName:'Бөлме атауы',yourName:'Атыңыз',createRoom:'Бөлме құру',roomOffline:'Достар бөлмесі дайындалып жатыр',roomOfflineText:'Ойын жұмыс істейді, ортақ рейтинг PortHub Cloud қосылған соң ашылады.',retry:'Қосылымды тексеру',leaderEmpty:'Достарыңызды шақырыңыз — рекордтары осында көрінеді.',updated:'жаңартылды {n}',rulesText:'Бірдей плиткаларды свайппен немесе жебелермен біріктіріңіз. Жүріс қалмаса, үш өмірдің бірі ең кіші екі плитканы жояды.',achievements:'Жетістіктер',noScroll:'Свайптар ойын алаңында жұмыс істейді.',syncLocal:'Жергілікті ойын',online:'Бұлт қосылды',statusLives:'{score} ұпай · {tile} · {lives} · ойында',playerFallback:'Ойыншы'},
en:{back:'Back',score:'Score',best:'Best',time:'Time',lives:'Lives',playing:'Game in progress',saved:'Saved on this device',menu:'Menu',room:'Friends room',invite:'Invite a friend',rating:'Friends leaderboard',share:'Share game',newGame:'New game',rules:'How to play',settings:'Sound and vibration',sound:'Sound',vibration:'Vibration',login:'Sign in with Google',soon:'Coming soon · progress on every device',close:'Close',confirmNew:'Start a new game?',confirmText:'The current board will be replaced. Your best score and achievements stay.',cancel:'Cancel',start:'Start',gameOver:'No moves left',gameOverText:'All three lives were used. Your best score is saved.',again:'Play again',lifeUsed:'A life saved the game: two smallest tiles burned away',achievement:'Achievement unlocked',coffeeTitle:'An annoying ad could be here',coffeeText:'For now, here is a short request to support PortHub instead. If the game hooked you, buy the developer a coffee or simply share it with friends. Both genuinely help the project grow 🙂',boosty:'Support via Boosty',kofi:'Support via Ko-fi',continue:'Continue in {n}s',continueNow:'Continue',createInvite:'Create room and invite',shareText:'I am playing 2048 on PortHub. Three lives—try to beat my score!',copied:'Game link copied',roomName:'Room name',yourName:'Your name',createRoom:'Create room',roomOffline:'Friends rooms are almost ready',roomOfflineText:'The game works now. Shared leaderboards switch on when PortHub Cloud is connected.',retry:'Check connection',leaderEmpty:'Invite friends and their records will appear here.',updated:'updated {n}',rulesText:'Merge matching tiles with swipes or arrow keys. When no moves remain, one of three lives removes the two smallest tiles. The next dead end after all lives are gone ends the game.',achievements:'Achievements',noScroll:'Swipe directly on the board.',syncLocal:'Local game',online:'Cloud connected',statusLives:'{score} points · {tile} · {lives} · playing',playerFallback:'Player'},
fr:{back:'Retour',score:'Score',best:'Record',time:'Temps',lives:'Vies',playing:'Partie en cours',saved:'Sauvegardé sur cet appareil',menu:'Menu',room:'Salon d’amis',invite:'Inviter un ami',rating:'Classement des amis',share:'Partager le jeu',newGame:'Nouvelle partie',rules:'Comment jouer',settings:'Son et vibration',sound:'Son',vibration:'Vibration',login:'Se connecter avec Google',soon:'Bientôt · progression sur tous les appareils',close:'Fermer',confirmNew:'Commencer une nouvelle partie ?',confirmText:'La grille actuelle sera remplacée. Le record et les succès seront conservés.',cancel:'Annuler',start:'Commencer',gameOver:'Plus aucun mouvement',gameOverText:'Les trois vies ont été utilisées. Votre record est sauvegardé.',again:'Rejouer',lifeUsed:'Une vie sauve la partie : les deux plus petites tuiles disparaissent',achievement:'Nouveau succès',coffeeTitle:'Une publicité agaçante aurait pu être ici',coffeeText:'Pour l’instant, voici plutôt une courte demande de soutien. Si le jeu vous plaît, offrez un café au développeur ou partagez-le avec vos amis 🙂',boosty:'Soutenir via Boosty',kofi:'Soutenir via Ko-fi',continue:'Continuer dans {n} s',continueNow:'Continuer',createInvite:'Créer un salon et inviter',shareText:'Je joue à 2048 sur PortHub. Trois vies : essayez de battre mon record !',copied:'Lien du jeu copié',roomName:'Nom du salon',yourName:'Votre nom',createRoom:'Créer le salon',roomOffline:'Les salons d’amis arrivent bientôt',roomOfflineText:'Le jeu fonctionne déjà. Le classement partagé sera activé avec PortHub Cloud.',retry:'Vérifier la connexion',leaderEmpty:'Invitez vos amis : leurs records apparaîtront ici.',updated:'actualisé {n}',rulesText:'Fusionnez les tuiles identiques par balayage ou avec les flèches. Quand aucun mouvement ne reste, une des trois vies supprime les deux plus petites tuiles.',achievements:'Succès',noScroll:'Balayez directement sur la grille.',syncLocal:'Jeu local',online:'Cloud connecté',statusLives:'{score} points · {tile} · {lives} · en cours',playerFallback:'Joueur'}
};
const A=[{id:'first',v:8,icon:'✨',name:{ru:'Первое слияние',kk:'Алғашқы біріктіру',en:'First merge',fr:'Première fusion'}},{id:'tile512',v:512,icon:'🟣',name:{ru:'Плитка 512',kk:'512 плиткасы',en:'512 tile',fr:'Tuile 512'}},{id:'tile2048',v:2048,icon:'🏆',name:{ru:'Дошёл до 2048',kk:'2048-ге жетті',en:'Reached 2048',fr:'2048 atteint'}},{id:'tile4096',v:4096,icon:'👑',name:{ru:'4096 — это уже зависимость',kk:'4096 — нағыз шеберлік',en:'4096 — officially hooked',fr:'4096 — vraiment accro'}},{id:'clean2048',v:2048,clean:true,icon:'❤️',name:{ru:'Без потерь',kk:'Шығынсыз',en:'No lives lost',fr:'Sans perdre de vie'}}];
const $=s=>document.querySelector(s),fmt=n=>Number(n||0).toLocaleString(lang),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function read(key,fallback){try{const v=JSON.parse(localStorage.getItem(key)||'null');return v??fallback}catch{return fallback}}
function write(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
function detectLang(){const path=location.pathname.split('/').filter(Boolean),route=path.find(x=>LANGS.includes(x));if(route)return route;const saved=localStorage.getItem('pt.lang');if(LANGS.includes(saved))return saved;const b=(navigator.language||'ru').slice(0,2);return LANGS.includes(b)?b:'ru'}
const lang=detectLang(),t=T[lang];document.documentElement.lang=lang;
const settings=Object.assign({sound:false,vibration:true},read(SETTINGS_KEY,{}));
let state=loadState(),paused=false,touchStart=null,timer=null,toastTimer=null,room=read(ROOM_KEY,null),cloudBusy=false;

// Defensive migration: invalid or old saves never block the game.
function validBoard(board){return Array.isArray(board)&&board.length===16&&board.every(v=>v===0||(Number.isInteger(v)&&v>=2&&(v&(v-1))===0));}
function freshState(){const s={version:1,board:Array(16).fill(0),score:0,lives:3,usedLives:0,moves:0,activeMs:0,lastTick:Date.now(),startedAt:Date.now(),over:false,shownPauses:[]};spawn(s);spawn(s);return s}
function loadState(){const raw=read(SAVE_KEY,null);if(!raw||!validBoard(raw.board)||!Number.isFinite(raw.score))return freshState();const lives=Number(raw.lives);return Object.assign(freshState(),raw,{version:1,board:raw.board.map(Number),score:Math.max(0,Number(raw.score)||0),lives:Number.isFinite(lives)?Math.max(0,Math.min(3,lives)):3,usedLives:Math.max(0,Number(raw.usedLives)||0),moves:Math.max(0,Number(raw.moves)||0),activeMs:Math.max(0,Number(raw.activeMs)||0),shownPauses:Array.isArray(raw.shownPauses)?raw.shownPauses:[]})}
function spawn(s=state){const empty=s.board.map((v,i)=>v?null:i).filter(i=>i!==null);if(!empty.length)return;const i=empty[Math.floor(Math.random()*empty.length)];s.board[i]=Math.random()<.9?2:4}
function maxTile(){return Math.max(...state.board)}
function save(){state.lastTick=Date.now();write(SAVE_KEY,state);const best=Math.max(Number(localStorage.getItem(BEST_KEY)||0),state.score);localStorage.setItem(BEST_KEY,String(best));return best}
function lineIndices(direction,line){const a=[];for(let p=0;p<4;p++){let x,y;if(direction===3){x=p;y=line}else if(direction===1){x=3-p;y=line}else if(direction===0){x=line;y=p}else{x=line;y=3-p}a.push(y*4+x)}return a}
function mergedLine(values){const nums=values.filter(Boolean),out=[],gains=[];for(let i=0;i<nums.length;i++){if(nums[i]===nums[i+1]){const v=nums[i]*2;out.push(v);gains.push(v);i++}else out.push(nums[i])}while(out.length<4)out.push(0);return{out,gain:gains.reduce((a,b)=>a+b,0)}}
function canMove(){if(state.board.includes(0))return true;for(let y=0;y<4;y++)for(let x=0;x<4;x++){const i=y*4+x;if(x<3&&state.board[i]===state.board[i+1])return true;if(y<3&&state.board[i]===state.board[i+4])return true}return false}
function rescue(){if(state.lives<=0)return false;state.lives--;state.usedLives++;const occupied=state.board.map((v,i)=>v?{v,i}:null).filter(Boolean).sort((a,b)=>a.v-b.v||a.i-b.i);occupied.slice(0,2).forEach(x=>state.board[x.i]=0);if(settings.vibration&&navigator.vibrate)navigator.vibrate([80,50,80]);toast(`❤️ ${t.lifeUsed}`);return true}
function move(direction){if(paused||state.over)return;const before=state.board.join(','),created=[];let gained=0,rescued=false;for(let l=0;l<4;l++){const ids=lineIndices(direction,l),result=mergedLine(ids.map(i=>state.board[i]));ids.forEach((i,p)=>state.board[i]=result.out[p]);gained+=result.gain;result.out.forEach(v=>{if(v>=8)created.push(v)})}if(before===state.board.join(','))return;state.score+=gained;state.moves++;spawn();if(!canMove()){rescued=rescue();if(!rescued){state.over=true;save();cloudSync(true,'finished');render();showGameOver();return}}save();if(rescued)cloudSync(true);unlockAchievements(created);beep(gained);render();maybeCoffee(created)}
function unlockAchievements(created){const max=Math.max(0,...created,maxTile()),owned=new Set(read(ACH_KEY,[])),newOnes=[];for(const item of A){if(max>=item.v&&(!item.clean||state.usedLives===0)&&!owned.has(item.id)){owned.add(item.id);newOnes.push(item)}}if(newOnes.length){write(ACH_KEY,[...owned]);newOnes.forEach((a,i)=>setTimeout(()=>toast(`${a.icon} ${t.achievement}: ${a.name[lang]}`),i*1600))}}
function beep(gain){if(!settings.sound||!gain)return;try{const C=window.AudioContext||window.webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=Math.min(780,220+Math.log2(gain)*45);g.gain.setValueAtTime(.04,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.09);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.1)}catch{}}
function duration(ms){const s=Math.floor(ms/1000),h=Math.floor(s/3600),m=Math.floor(s%3600/60);return h?`${h}:${String(m).padStart(2,'0')}`:`${m}:${String(s%60).padStart(2,'0')}`}
function rootPath(){const parts=location.pathname.split('/').filter(Boolean),idx=parts.findIndex(x=>LANGS.includes(x));return idx>=0?`${location.origin}/${parts[idx]}/games/`:`${location.origin}/games/`}
function render(){const best=Math.max(Number(localStorage.getItem(BEST_KEY)||0),state.score),lives='❤️'.repeat(state.lives)+'♡'.repeat(3-state.lives);$('#app').innerHTML=`<header class="game-top"><a class="back" href="${rootPath()}">← ${t.back}</a><div class="wordmark">Port<b>Hub</b></div><div class="top-actions"><button class="room-pill" id="roomTop" type="button">👥</button><button class="menu-button" id="menu" type="button" aria-label="${t.menu}">⋮</button></div></header><section class="stats"><div class="stat"><small>${t.score}</small><strong>${fmt(state.score)}</strong></div><div class="stat"><small>${t.best}</small><strong>${fmt(best)}</strong></div><div class="stat"><small>${t.time}</small><strong id="time">${duration(state.activeMs)}</strong></div><div class="stat"><small>${t.lives}</small><strong class="life-value">${lives}</strong></div></section><section class="board-wrap"><div class="board" id="board" aria-label="2048"><div class="cell"></div>`.replace('<div class="cell"></div>',Array(16).fill('<div class="cell"></div>').join(''))+`<div class="tile-layer">${state.board.map(v=>v?`<div class="tile" data-v="${v}" data-high="${v>2048?1:0}">${v}</div>`:'<div></div>').join('')}</div></div></section><footer class="game-bottom"><div class="status"><b>●</b> ${room?t.online:t.syncLocal} · ${t.saved}</div><div class="controls"><button class="ghost" id="rating" type="button">🏆 ${t.rating}</button><button class="primary" id="invite" type="button">👥 ${room?t.invite:t.room}</button></div></footer>`;bindBoard();$('#menu').onclick=showMenu;$('#roomTop').onclick=showRoom;$('#rating').onclick=showRoom;$('#invite').onclick=showRoom}
function bindBoard(){const b=$('#board');b.addEventListener('pointerdown',e=>{touchStart={x:e.clientX,y:e.clientY};b.setPointerCapture?.(e.pointerId)});b.addEventListener('pointerup',e=>{if(!touchStart)return;const dx=e.clientX-touchStart.x,dy=e.clientY-touchStart.y;touchStart=null;if(Math.max(Math.abs(dx),Math.abs(dy))<24)return;move(Math.abs(dx)>Math.abs(dy)?(dx>0?1:3):(dy>0?2:0))});b.addEventListener('contextmenu',e=>e.preventDefault())}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2600)}
function backdrop(content){paused=true;const el=document.createElement('div');el.className='backdrop';el.innerHTML=`<section class="modal">${content}</section>`;document.body.appendChild(el);return el}
function closeOverlay(el){el?.remove();paused=false}
function showGameOver(){const el=backdrop(`<h2>${t.gameOver}</h2><p>${t.gameOverText}</p><p><strong>${fmt(state.score)}</strong> · ${maxTile()}</p><div class="modal-actions"><button class="accent wide" id="again">${t.again}</button><button id="shareResult">${t.share}</button><button id="friends">${t.room}</button></div>`);el.querySelector('#again').onclick=()=>{closeOverlay(el);resetGame()};el.querySelector('#shareResult').onclick=shareGame;el.querySelector('#friends').onclick=()=>{closeOverlay(el);showRoom()}}
function confirmReset(){const el=backdrop(`<h2>${t.confirmNew}</h2><p>${t.confirmText}</p><div class="modal-actions"><button id="cancel">${t.cancel}</button><button class="accent" id="yes">${t.start}</button></div>`);el.querySelector('#cancel').onclick=()=>closeOverlay(el);el.querySelector('#yes').onclick=()=>{closeOverlay(el);resetGame()}}
function resetGame(){state=freshState();save();render()}
function showRules(){const el=backdrop(`<h2>2048</h2><p>${t.rulesText}</p><p>${t.noScroll}</p><div class="modal-actions"><button class="accent wide" id="ok">${t.close}</button></div>`);el.querySelector('#ok').onclick=()=>closeOverlay(el)}
function achievementsMarkup(){const owned=new Set(read(ACH_KEY,[]));return A.filter(a=>owned.has(a.id)).map(a=>`<div class="leader"><span>${a.icon}</span><span>${esc(a.name[lang])}</span><b>✓</b></div>`).join('')||`<p>${t.playing}</p>`}
function drawer(title,body){paused=true;const shade=document.createElement('div');shade.className='drawer-backdrop';const el=document.createElement('aside');el.className='drawer';el.innerHTML=`<div class="drawer-head"><h2>${title}</h2><button class="drawer-close" aria-label="${t.close}">×</button></div>${body}`;document.body.append(shade,el);const close=()=>{shade.remove();el.remove();paused=false};shade.onclick=close;el.querySelector('.drawer-close').onclick=close;return{el,close}}
function showMenu(){const d=drawer(t.menu,`<div class="menu-list"><button id="roomMenu">👥 ${t.room}</button><button id="shareMenu">↗ ${t.share}</button><button id="achMenu">🏆 ${t.achievements}<small>${read(ACH_KEY,[]).length} / ${A.length}</small></button><button id="rulesMenu">❔ ${t.rules}</button><button class="switch-row" id="soundMenu"><span>🔊 ${t.sound}</span><b>${settings.sound?'ON':'OFF'}</b></button><button class="switch-row" id="vibMenu"><span>📳 ${t.vibration}</span><b>${settings.vibration?'ON':'OFF'}</b></button><button class="login-soon" disabled>G&nbsp; ${t.login}<small>${t.soon}</small></button><button id="newMenu">↻ ${t.newGame}</button></div>`);d.el.querySelector('#roomMenu').onclick=()=>{d.close();showRoom()};d.el.querySelector('#shareMenu').onclick=shareGame;d.el.querySelector('#achMenu').onclick=()=>{d.close();const a=drawer(t.achievements,`<div class="leaderboard">${achievementsMarkup()}</div>`)};d.el.querySelector('#rulesMenu').onclick=()=>{d.close();showRules()};d.el.querySelector('#soundMenu').onclick=()=>{settings.sound=!settings.sound;write(SETTINGS_KEY,settings);d.close();showMenu()};d.el.querySelector('#vibMenu').onclick=()=>{settings.vibration=!settings.vibration;write(SETTINGS_KEY,settings);d.close();showMenu()};d.el.querySelector('#newMenu').onclick=()=>{d.close();confirmReset()}}
async function shareGame(){const url=room?.inviteUrl||`${location.origin}${location.pathname}`,data={title:'2048 PortHub',text:`${t.shareText} ${t.statusLives.replace('{score}',fmt(state.score)).replace('{tile}',maxTile()).replace('{lives}','❤️'.repeat(state.lives))}`,url};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(`${data.text} ${url}`);toast(t.copied)}}catch(e){if(e?.name!=='AbortError')toast(t.copied)}}
function profile(){let p=read(PROFILE_KEY,null);if(!p){p={id:crypto.randomUUID?.()||Math.random().toString(36).slice(2),name:''};write(PROFILE_KEY,p)}return p}
async function api(path,options={}){const headers={'content-type':'application/json',...(options.headers||{})};const ctl=new AbortController(),timeout=setTimeout(()=>ctl.abort(),5500);try{const res=await fetch(`${API}${path}`,{...options,headers,signal:ctl.signal});if(!res.ok)throw new Error(String(res.status));return await res.json()}finally{clearTimeout(timeout)}}
function roomFormText(){return `<div class="room-card"><p>${t.roomOfflineText}</p><label>${t.yourName}<input id="playerName" maxlength="24" value="${esc(profile().name)}" autocomplete="nickname"></label><label>${t.roomName}<input id="roomName" maxlength="40" value="2048" autocomplete="off"></label><button class="primary" id="createRoom">👥 ${t.createRoom}</button></div>`}
async function showRoom(){const d=drawer(t.room,room?`<div class="room-card"><h3>${esc(room.name||'2048')}</h3><p>${t.updated.replace('{n}',room.updatedLabel||'—')}</p><button class="primary" id="inviteRoom">↗ ${t.invite}</button></div><div class="leaderboard" id="leaders"><p>${t.leaderEmpty}</p></div>`:roomFormText());if(room){d.el.querySelector('#inviteRoom').onclick=shareGame;loadRoom(d.el.querySelector('#leaders'));return}d.el.querySelector('#createRoom').onclick=async()=>{const button=d.el.querySelector('#createRoom'),name=d.el.querySelector('#playerName').value.trim()||t.playerFallback,roomName=d.el.querySelector('#roomName').value.trim()||'2048';button.disabled=true;button.textContent='…';const p=profile();p.name=name;write(PROFILE_KEY,p);try{const created=await api('/rooms',{method:'POST',body:JSON.stringify({name:roomName,playerName:name,deviceId:p.id})});room={...created,name:roomName,lastSync:0,inviteUrl:`${location.origin}${location.pathname}?room=${encodeURIComponent(created.roomId)}#key=${created.roomKey}`};write(ROOM_KEY,room);cloudSync(true);d.close();render();showRoom()}catch{button.disabled=false;button.textContent=t.retry;const note=document.createElement('p');note.textContent=t.roomOffline;button.before(note)}}}
async function loadRoom(container){try{const data=await api(`/rooms/${encodeURIComponent(room.roomId)}`,{headers:{authorization:`Bearer ${room.roomKey}`}});room.updatedLabel=new Date().toLocaleTimeString(lang,{hour:'2-digit',minute:'2-digit'});write(ROOM_KEY,room);const flagged=data.leaderboard?.some(x=>x.review),notice=flagged?`<div class="review-note"><b>${REVIEW[lang].title}</b><span>${REVIEW[lang].text}</span></div>`:'';container.innerHTML=notice+(data.leaderboard?.length?data.leaderboard.map((x,i)=>`<div class="leader${x.review?' review':''}"><b>${x.review?'🚨':i+1}</b><span>${esc(x.name)}<small>${t.statusLives.replace('{score}',fmt(x.score)).replace('{tile}',x.maxTile).replace('{lives}','❤️'.repeat(x.lives))}</small></span><strong>${fmt(x.score)}</strong></div>`).join(''):`<p>${t.leaderEmpty}</p>`)}catch{container.innerHTML=`<p>${t.roomOfflineText}</p>`}}
async function cloudSync(force=false,status='playing'){if(!room?.playerId||!room?.playerKey||cloudBusy)return;const interval=Math.max(60,Number(room.syncAfter)||120)*1000;if(!force&&Date.now()-(Number(room.lastSync)||0)<interval)return;cloudBusy=true;try{const data=await api(`/rooms/${encodeURIComponent(room.roomId)}/players/${encodeURIComponent(room.playerId)}`,{method:'PUT',keepalive:force,headers:{authorization:`Bearer ${room.playerKey}`},body:JSON.stringify({score:state.score,maxTile:maxTile(),lives:state.lives,moves:state.moves,activeMs:state.activeMs,status})});room.lastSync=Date.now();room.syncAfter=data.syncAfter||room.syncAfter||120;write(ROOM_KEY,room)}catch{}finally{cloudBusy=false}}
function inviteData(){const roomId=new URLSearchParams(location.search).get('room'),key=new URLSearchParams(location.hash.slice(1)).get('key');return roomId&&key?{roomId,key}:null}
function showJoinInvite(invite){const p=profile(),el=backdrop(`<h2>👥 ${t.room}</h2><p>${t.invite}</p><label>${t.yourName}<input id="joinName" maxlength="24" value="${esc(p.name)}" autocomplete="nickname"></label><div class="modal-actions"><button id="joinCancel">${t.cancel}</button><button class="accent" id="joinNow">${t.start}</button></div>`);el.querySelector('#joinCancel').onclick=()=>closeOverlay(el);el.querySelector('#joinNow').onclick=async()=>{const b=el.querySelector('#joinNow'),name=el.querySelector('#joinName').value.trim()||t.playerFallback;b.disabled=true;b.textContent='…';try{const joined=await api(`/rooms/${encodeURIComponent(invite.roomId)}/join`,{method:'POST',headers:{authorization:`Bearer ${invite.key}`},body:JSON.stringify({playerName:name,deviceId:p.id})});p.name=name;write(PROFILE_KEY,p);room={...joined,roomKey:invite.key,name:joined.roomName||'2048',lastSync:0,inviteUrl:`${location.origin}${location.pathname}?room=${encodeURIComponent(invite.roomId)}#key=${invite.key}`};write(ROOM_KEY,room);closeOverlay(el);cloudSync(true);render();toast(t.online)}catch{b.disabled=false;b.textContent=t.retry}}}
function maybeCoffee(created){const milestone=[2048,8192].find(v=>created.includes(v)&&!state.shownPauses.includes(v));if(!milestone)return;state.shownPauses.push(milestone);save();showCoffee()}
function showCoffee(){const el=backdrop(`<h2>📺 ${t.coffeeTitle}</h2><p>${t.coffeeText}</p><div class="modal-actions"><a href="${SUPPORT.boosty}" target="_blank" rel="noopener">☕ ${t.boosty}</a><a href="${SUPPORT.kofi}" target="_blank" rel="noopener">☕ ${t.kofi}</a><button id="sharePause">↗ ${t.share}</button><button id="roomPause">👥 ${room?t.invite:t.createInvite}</button><button class="accent wide countdown" id="continuePause" disabled>${t.continue.replace('{n}',10)}</button></div>`);el.querySelector('#sharePause').onclick=shareGame;el.querySelector('#roomPause').onclick=()=>{closeOverlay(el);showRoom()};const b=el.querySelector('#continuePause');let n=10;const tick=setInterval(()=>{n--;b.textContent=n?t.continue.replace('{n}',n):t.continueNow;if(!n){clearInterval(tick);b.disabled=false;b.onclick=()=>closeOverlay(el)}},1000)}
function tick(){if(!paused&&!state.over&&document.visibilityState==='visible'){state.activeMs+=1000;const e=$('#time');if(e)e.textContent=duration(state.activeMs)}if(state.activeMs%15000===0)save();cloudSync()}
document.addEventListener('keydown',e=>{const map={ArrowUp:0,w:0,W:0,ArrowRight:1,d:1,D:1,ArrowDown:2,s:2,S:2,ArrowLeft:3,a:3,A:3};if(map[e.key]!==undefined){e.preventDefault();move(map[e.key])}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){save();cloudSync(true)}});addEventListener('pagehide',()=>{save();cloudSync(true)});addEventListener('beforeunload',save);
render();timer=setInterval(tick,1000);
if(state.over)setTimeout(showGameOver,200);
const invite=inviteData();if(invite&&room?.roomId!==invite.roomId)setTimeout(()=>showJoinInvite(invite),250);
})();
