const LANGS=['ru','kk','en','fr'];
const browserLang=(navigator.language||'ru').slice(0,2).toLowerCase();
let lang=(()=>{try{const saved=localStorage.getItem('pt.lang');return LANGS.includes(saved)?saved:(LANGS.includes(browserLang)?browserLang:'ru')}catch{return'ru'}})();

const UI={
ru:{home:'На главную',kicker:'ТЕСТ НА СКОРОСТЬ БРЕДА',title:'Анти‑IQ.<br><em>Затупи красиво.</em>',lead:'Забудьте про умные тесты. Здесь считаем не интеллект, а скорость реакции, любовь к абсурду и способность вовремя перестать искать глубокий смысл.',facts:['16 вопросов','≈ 2 минуты','результат остаётся на устройстве'],notice:'Это игра и мемный тест, а не измерение интеллекта. Низкий или высокий результат ничего не говорит о ваших способностях.',start:'Начать без подготовки',round:'Вопрос {now} из {all}',live:'Анти‑очки: {score}',think:'Время реакции',logical:'Логика заметила ваш ответ',absurd:'Абсурд принят',result:'Ваш уровень Анти‑IQ',shared:'Вам отправили готовый результат',points:'анти‑очков',logicStat:'логических ответов совпало',absurdStat:'средняя реакция на абсурд',tempoStat:'общая скорость',why:'Что произошло',share:'Поделиться результатом',again:'Затупить ещё раз',other:'Другие тесты',copied:'Ссылка на результат скопирована',safe:'В ссылке только итоговые очки и игровая статистика — никаких личных данных.',shareText:'Я набрал {score} анти‑очков и получил статус «{title}». Сможешь затупить красивее?',bands:[['Душный профессор','Вы слишком старательно искали логику даже там, где табуретка просто была синей. Мозг держал оборону до последнего.'],['Стабильный дуб','Мозг периодически включался, но вы вовремя делали вид, что ничего не произошло. Уверенный бытовой Анти‑IQ.'],['Сверхзвуковой хаос','Палец принимал решения раньше, чем мысль успевала оформить заявку. Абсурд явно чувствует себя рядом с вами как дома.'],['Абсолютная легенда тупости','Вы не прошли тест — вы его сломали. Где-то муха остановилась, сняла шляпу и начала аплодировать.']]},
kk:{home:'Басты бетке',kicker:'АБСУРД ЖЫЛДАМДЫҒЫ ТЕСТІ',title:'Анти‑IQ.<br><em>Әдемі шатас.</em>',lead:'Ақылды тесттерді ұмытыңыз. Мұнда интеллект емес, реакция жылдамдығы, абсурдқа деген махаббат және артық мағына іздеуді уақытында тоқтату қабілеті есептеледі.',facts:['16 сұрақ','≈ 2 минут','нәтиже құрылғыда қалады'],notice:'Бұл — ойын және мем-тест, интеллект өлшемі емес. Нәтиже қабілетіңіз туралы қорытынды бермейді.',start:'Дайындықсыз бастау',round:'{all} сұрақтың {now}-і',live:'Анти‑ұпай: {score}',think:'Реакция уақыты',logical:'Логика жауабыңызды байқады',absurd:'Абсурд қабылданды',result:'Сіздің Анти‑IQ деңгейіңіз',shared:'Сізге дайын нәтиже жіберілді',points:'анти‑ұпай',logicStat:'логикалық жауап сәйкес келді',absurdStat:'абсурдқа орташа реакция',tempoStat:'жалпы жылдамдық',why:'Не болды',share:'Нәтижемен бөлісу',again:'Тағы бір рет шатасу',other:'Басқа тесттер',copied:'Нәтиже сілтемесі көшірілді',safe:'Сілтемеде тек ойын ұпайы мен статистика бар — жеке дерек жоқ.',shareText:'Мен {score} анти‑ұпай жинап, «{title}» атағын алдым. Сен әдемірек шатаса аласың ба?',bands:[['Жалықтыратын профессор','Сіз көк орындықтан да логика іздеуге тырыстыңыз. Ми соңына дейін қорғанды.'],['Тұрақты емен','Ми кейде қосылды, бірақ сіз оны уақытында байқамағандай болдыңыз. Сенімді тұрмыстық Анти‑IQ.'],['Дыбыстан жылдам хаос','Саусақ ой өтініш беріп үлгермей тұрып шешім қабылдады. Абсурд сіздің жаныңызда өзін үйіндегідей сезінеді.'],['Түпкілікті шатасу аңызы','Сіз тесттен өтпедіңіз — оны сындырдыңыз. Бір жерде шыбын бас киімін шешіп, қол соғып тұр.']]},
en:{home:'Home',kicker:'A TEST OF NONSENSE SPEED',title:'Anti‑IQ.<br><em>Fail brilliantly.</em>',lead:'Forget smart tests. This one measures reaction speed, affection for nonsense, and knowing when to stop searching for hidden meaning.',facts:['16 questions','≈ 2 minutes','result stays on device'],notice:'This is a game and a meme quiz, not an intelligence test. A high or low result says nothing about your abilities.',start:'Start unprepared',round:'Question {now} of {all}',live:'Anti‑points: {score}',think:'Reaction time',logical:'Logic noticed your answer',absurd:'Nonsense accepted',result:'Your Anti‑IQ level',shared:'Someone sent you a finished result',points:'anti‑points',logicStat:'logical answers matched',absurdStat:'average nonsense reaction',tempoStat:'overall speed',why:'What happened',share:'Share result',again:'Fail again',other:'Other quizzes',copied:'Result link copied',safe:'The link contains only the score and game stats—no personal data.',shareText:'I scored {score} anti‑points and earned “{title}”. Can you fail more brilliantly?',bands:[['Serious Professor','You searched for logic even inside a blue stool. Your brain defended the perimeter until the end.'],['Dependable Oak','Your brain switched on occasionally, but you wisely pretended not to notice. Solid everyday Anti‑IQ.'],['Supersonic Chaos','Your finger made decisions before the thought filed its paperwork. Nonsense feels completely at home around you.'],['Absolute Legend of Nonsense','You did not take the quiz—you broke it. Somewhere, a fly took off its hat and started applauding.']]},
fr:{home:'Accueil',kicker:'TEST DE VITESSE ABSURDE',title:'Anti‑QI.<br><em>Ratez avec panache.</em>',lead:'Oubliez les tests savants. Ici, on mesure la rapidité, l’amour de l’absurde et le talent d’arrêter de chercher un sens caché.',facts:['16 questions','≈ 2 minutes','résultat conservé sur l’appareil'],notice:'Ceci est un jeu et un test-mème, pas une mesure de l’intelligence. Le résultat ne dit rien de vos capacités.',start:'Commencer sans préparation',round:'Question {now} sur {all}',live:'Anti‑points : {score}',think:'Temps de réaction',logical:'La logique a remarqué votre réponse',absurd:'Absurdité acceptée',result:'Votre niveau Anti‑QI',shared:'On vous a envoyé un résultat terminé',points:'anti‑points',logicStat:'réponses logiques trouvées',absurdStat:'réaction moyenne à l’absurde',tempoStat:'vitesse générale',why:'Ce qui s’est passé',share:'Partager le résultat',again:'Rater encore une fois',other:'Autres tests',copied:'Lien du résultat copié',safe:'Le lien ne contient que le score et les statistiques du jeu, aucune donnée personnelle.',shareText:'J’ai marqué {score} anti‑points et obtenu « {title} ». Tu peux rater avec plus de panache ?',bands:[['Professeur trop sérieux','Vous avez cherché de la logique jusque dans un tabouret bleu. Votre cerveau a résisté jusqu’au bout.'],['Chêne stable','Le cerveau s’est parfois allumé, mais vous avez eu la sagesse de ne pas le remarquer.'],['Chaos supersonique','Votre doigt décidait avant que la pensée remplisse les papiers. L’absurde se sent chez lui avec vous.'],['Légende absolue du grand n’importe quoi','Vous n’avez pas passé le test : vous l’avez cassé. Quelque part, une mouche applaudit.']]}
};

const Q=[
{type:'logical',q:{ru:'Продолжите: 3, 6, 12, 24…',kk:'Жалғастырыңыз: 3, 6, 12, 24…',en:'Continue: 3, 6, 12, 24…',fr:'Continuez : 3, 6, 12, 24…'},a:[['48',1],['36'],['27'],['Сырок / Ірімшік / Cheese / Fromage']]},
{type:'absurd',q:{ru:'Если перевернуть пингвина, он станет фиолетовым?',kk:'Пингвинді төңкерсе, ол күлгін бола ма?',en:'If you turn a penguin upside down, will it become purple?',fr:'Si on retourne un pingouin, devient-il violet ?'},a:[['Да, по ГОСТу / Иә / Yes / Oui',0,1],['Только в четверг / Бейсенбіде / Thursdays / Le jeudi'],['Зависит от Wi‑Fi / Wi‑Fi-ға байланысты / Depends on Wi‑Fi / Selon le Wi‑Fi'],['Пингвин занят / Пингвин бос емес / Penguin is busy / Le pingouin est occupé']]},
{type:'logical',q:{ru:'Какая фигура лишняя: круг, квадрат, треугольник, куб?',kk:'Қай пішін артық: шеңбер, шаршы, үшбұрыш, куб?',en:'Which shape is different: circle, square, triangle, cube?',fr:'Quelle forme est différente : cercle, carré, triangle, cube ?'},a:[['Круг / Шеңбер / Circle / Cercle'],['Квадрат / Шаршы / Square / Carré'],['Треугольник / Үшбұрыш / Triangle'],['Куб / Cube',1]]},
{type:'absurd',q:{ru:'Сколько ног у синей табуретки, если сегодня вторник?',kk:'Бүгін сейсенбі болса, көк орындықтың неше аяғы бар?',en:'How many legs does a blue stool have if today is Tuesday?',fr:'Combien de pieds a un tabouret bleu si nous sommes mardi ?'},a:[['Четыре, но не точно / Төрт / Four-ish / Environ quatre'],['Вторник отменяет ноги / Сейсенбі аяқты жояды / Tuesday cancels legs / Le mardi annule les pieds',0,1],['Семь с половиной / Жеті жарым / Seven and a half / Sept et demi'],['Смотря чей вторник / Қай сейсенбіге байланысты / Whose Tuesday? / Le mardi de qui ?']]},
{type:'logical',q:{ru:'У Маши 5 яблок. Два отдала. Сколько осталось?',kk:'Машада 5 алма болды. Екеуін берді. Қанша қалды?',en:'Masha has 5 apples and gives away 2. How many remain?',fr:'Macha a 5 pommes et en donne 2. Combien en reste-t-il ?'},a:[['2'],['3',1],['5'],['Яблоки вне политики / Алма саясаттан тыс / Apples abstain / Les pommes s’abstiennent']]},
{type:'absurd',q:{ru:'Куда девается звук, когда выключают колонку?',kk:'Колонканы өшіргенде дыбыс қайда кетеді?',en:'Where does sound go when you turn off a speaker?',fr:'Où va le son quand on éteint l’enceinte ?'},a:[['Домой / Үйге / Home / À la maison'],['В соседний Bluetooth / Көрші Bluetooth-қа / Next Bluetooth / Dans le Bluetooth voisin',0,1],['Под диван / Диван астына / Under the sofa / Sous le canapé'],['Ждёт обновления / Жаңартуды күтеді / Waits for an update / Attend une mise à jour']]},
{type:'logical',q:{ru:'Что тяжелее: килограмм железа или килограмм ваты?',kk:'Не ауыр: бір килограмм темір ме, әлде бір килограмм мақта ма?',en:'Which is heavier: a kilogram of iron or a kilogram of cotton?',fr:'Qu’est-ce qui est plus lourd : un kilo de fer ou un kilo de coton ?'},a:[['Железо / Темір / Iron / Fer'],['Вата / Мақта / Cotton / Coton'],['Одинаково / Бірдей / Same / Pareil',1],['Понедельник / Дүйсенбі / Monday / Lundi']]},
{type:'absurd',q:{ru:'Что первым делом делает холодильник ночью?',kk:'Тоңазытқыш түнде ең алдымен не істейді?',en:'What is the first thing a fridge does at night?',fr:'Que fait un réfrigérateur en premier pendant la nuit ?'},a:[['Светится при свидетелях / Куәгер болса жанады / Glows when witnessed / Brille devant témoins'],['Обсуждает хозяина / Иесін талқылайды / Discusses its owner / Parle de son propriétaire',0,1],['Охлаждает атмосферу / Атмосфераны суытады / Chills the mood / Refroidit l’ambiance'],['Ничего не помнит / Ештеңе есінде жоқ / Remembers nothing / Ne se souvient de rien']]},
{type:'logical',q:{ru:'Если все ламы — животные, а Лола — лама, то Лола…',kk:'Барлық лама жануар болса, ал Лола лама болса, Лола…',en:'If all llamas are animals and Lola is a llama, then Lola is…',fr:'Si tous les lamas sont des animaux et Lola est un lama, Lola est…'},a:[['Животное / Жануар / An animal / Un animal',1],['Философ / Философ / A philosopher / Philosophe'],['Треугольник / Үшбұрыш / A triangle / Un triangle'],['В отпуске / Демалыста / On holiday / En vacances']]},
{type:'absurd',q:{ru:'Почему носок исчезает после стирки?',kk:'Неге шұлық жуудан кейін жоғалады?',en:'Why does a sock disappear after washing?',fr:'Pourquoi une chaussette disparaît-elle après le lavage ?'},a:[['Начал новую жизнь / Жаңа өмір бастады / Started a new life / Nouvelle vie',0,1],['Стиралка берёт налог / Кір жуғыш салық алады / Washer tax / Taxe de machine'],['Ушёл за хлебом / Нанға кетті / Went for bread / Partie chercher du pain'],['Он был легендой / Ол аңыз еді / It was a legend / C’était une légende']]},
{type:'logical',q:{ru:'Какое число идёт перед 100?',kk:'100 санының алдында қандай сан тұр?',en:'Which number comes before 100?',fr:'Quel nombre vient avant 100 ?'},a:[['98'],['99',1],['101'],['Очень уверенное 7 / Сенімді 7 / A confident 7 / Un 7 très sûr']]},
{type:'absurd',q:{ru:'Можно ли зарядить телефон добрым словом?',kk:'Телефонды жылы сөзбен зарядтауға бола ма?',en:'Can you charge a phone with a kind word?',fr:'Peut-on charger un téléphone avec un mot gentil ?'},a:[['До 3%, если искренне / Шын болса 3%-ға / Up to 3% sincerely / Jusqu’à 3 %'],['Только Samsung хвалить / Samsung-ты мақтау керек / Compliment Samsung / Complimenter Samsung'],['Да, но кабель обидится / Иә, кабель ренжиді / Yes, cable gets jealous / Oui, le câble sera jaloux',0,1],['Нет, он токсичный / Жоқ, ол токсик / No, it is toxic / Non, il est toxique']]},
{type:'logical',q:{ru:'Сколько минут в двух часах?',kk:'Екі сағатта неше минут бар?',en:'How many minutes are in two hours?',fr:'Combien de minutes dans deux heures ?'},a:[['60'],['100'],['120',1],['Зависит от совещания / Жиналысқа байланысты / Depends on the meeting / Selon la réunion']]},
{type:'absurd',q:{ru:'Если кот сел на ноутбук, кто теперь администратор?',kk:'Мысық ноутбукке отырса, енді әкімші кім?',en:'If a cat sits on the laptop, who is the administrator now?',fr:'Si un chat s’assoit sur l’ordinateur, qui est administrateur ?'},a:[['Кот, права root / Мысық, root құқығы / Cat has root / Le chat est root',0,1],['Ноутбук усыновлён / Ноутбук асырап алынды / Laptop adopted / Ordinateur adopté'],['Тот, у кого корм / Жемі бар адам / Whoever has food / Celui qui a les croquettes'],['Служба поддержки / Қолдау қызметі / Support desk / Le support']]},
{type:'logical',q:{ru:'Найдите половину от 50.',kk:'50 санының жартысын табыңыз.',en:'Find half of 50.',fr:'Trouvez la moitié de 50.'},a:[['15'],['20'],['25',1],['50, но грустнее / Мұңды 50 / A sadder 50 / 50 en plus triste']]},
{type:'absurd',q:{ru:'Как правильно открыть дверь в параллельную вселенную?',kk:'Параллель әлемнің есігін қалай ашу керек?',en:'How do you open a door to a parallel universe?',fr:'Comment ouvrir la porte d’un univers parallèle ?'},a:[['Потянуть, хотя написано «от себя» / «Итер» десе де тарту / Pull despite PUSH / Tirer malgré POUSSER'],['Трижды обновить страницу / Бетті үш рет жаңарту / Refresh three times / Actualiser trois fois'],['Постучать мемом / Меммен қағу / Knock with a meme / Frapper avec un mème',0,1],['Она уже открыта / Ол ашық тұр / It is already open / Elle est déjà ouverte']]}
];

const app=document.querySelector('#app'),fmt=n=>new Intl.NumberFormat(lang).format(Math.round(n));
const fill=(s,v)=>Object.entries(v).reduce((a,[k,x])=>a.replaceAll(`{${k}}`,x),s);
const optionText=s=>{const parts=s.split(' / ');return parts[{ru:0,kk:1,en:2,fr:3}[lang]]||parts[0]};
const shuffle=a=>{const x=[...a];for(let i=x.length-1;i>0;i--){const r=new Uint32Array(1);crypto.getRandomValues(r);const j=r[0]%(i+1);[x[i],x[j]]=[x[j],x[i]]}return x};
const encode=o=>btoa(unescape(encodeURIComponent(JSON.stringify(o)))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
const decode=s=>{try{return JSON.parse(decodeURIComponent(escape(atob(s.replaceAll('-','+').replaceAll('_','/')))))}catch{return null}};
let order=[],at=0,total=0,started=0,timer=0,locked=false,stats={logical:0,correct:0,logicalMs:0,absurd:0,absurdMs:0},result=null;

function top(){return `<header class="top"><a class="brand" href="../../">PortHub</a><div class="tools"><a class="home" href="../../">⌂ ${UI[lang].home}</a><select id="lang" aria-label="Language">${LANGS.map(x=>`<option value="${x}"${x===lang?' selected':''}>${x.toUpperCase()}</option>`).join('')}</select></div></header>`}
function bindTop(){document.querySelector('#lang').onchange=e=>{lang=e.target.value;localStorage.setItem('pt.lang',lang);renderCurrent()}}
function intro(){const c=UI[lang];app.innerHTML=top()+`<main class="panel intro"><span class="kicker">${c.kicker}</span><h1>${c.title}</h1><p class="lead">${c.lead}</p><div class="facts">${c.facts.map(x=>`<span>${x}</span>`).join('')}</div><div class="notice">⚠ ${c.notice}</div><button class="primary wide" id="start">${c.start}</button></main>`;bindTop();document.querySelector('#start').onclick=start}
function start(){history.replaceState(null,'',location.pathname);localStorage.removeItem('pt.antiIq.result');order=shuffle(Q);at=0;total=0;stats={logical:0,correct:0,logicalMs:0,absurd:0,absurdMs:0};result=null;question()}
function pointsFor(q,ms,answer){if(q.type==='logical')return Math.round(Math.min(6500,Math.max(250,ms))*8+(answer[1]?0:15000));const speed=Math.max(.05,1-Math.max(0,ms-200)/4800);return Math.round(120000*speed+(answer[2]?12000:0))}
function question(){locked=false;clearInterval(timer);const c=UI[lang],q=order[at];app.innerHTML=top()+`<main class="panel quiz"><div class="quiz-head"><span>${fill(c.round,{now:at+1,all:order.length})}</span><span class="score-live">${fill(c.live,{score:fmt(total)})}</span></div><div class="progress"><i style="width:${at/order.length*100}%"></i></div><div class="timer"><span>${c.think}</span><div class="timer-track"><i id="timer-bar"></i></div><b id="clock">0.0s</b></div><h1 class="question">${q.q[lang]}</h1><div class="answers">${q.a.map((x,i)=>`<button class="answer" data-answer="${i}">${optionText(x[0])}</button>`).join('')}</div></main>`;bindTop();started=performance.now();timer=setInterval(()=>{const ms=performance.now()-started,clock=document.querySelector('#clock'),bar=document.querySelector('#timer-bar');if(clock)clock.textContent=`${(ms/1000).toFixed(1)}s`;if(bar)bar.style.transform=`scaleX(${Math.max(0,1-ms/8000)})`},50);document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(Number(b.dataset.answer)))}
function answer(index){if(locked)return;locked=true;clearInterval(timer);const q=order[at],choice=q.a[index],ms=Math.max(1,Math.round(performance.now()-started)),points=pointsFor(q,ms,choice);total+=points;if(q.type==='logical'){stats.logical++;stats.logicalMs+=ms;if(choice[1])stats.correct++}else{stats.absurd++;stats.absurdMs+=ms}document.querySelectorAll('[data-answer]').forEach((b,i)=>{b.disabled=true;if(i===index)b.classList.add('picked',q.type==='logical'?(choice[1]?'correct':'wrong'):'correct')});const flash=document.createElement('div');flash.className='flash';flash.textContent=`+${fmt(points)} · ${q.type==='logical'?UI[lang].logical:UI[lang].absurd}`;document.body.appendChild(flash);setTimeout(()=>{flash.remove();at++;at<order.length?question():finish()},520)}
function bandIndex(score){return score<450000?0:score<850000?1:score<1150000?2:3}
function finish(){const avgAbsurd=Math.round(stats.absurdMs/Math.max(1,stats.absurd)),avgAll=Math.round((stats.absurdMs+stats.logicalMs)/Math.max(1,stats.absurd+stats.logical));result={v:1,score:Math.round(total),band:bandIndex(total),correct:stats.correct,logical:stats.logical,absurdMs:avgAbsurd,avgMs:avgAll,lang};try{localStorage.setItem('pt.antiIq.result',JSON.stringify(result))}catch{}showResult(false)}
function validResult(x){return x&&x.v===1&&Number.isFinite(x.score)&&x.score>=0&&x.score<3000000&&Number.isInteger(x.band)&&x.band>=0&&x.band<4}
function showResult(shared){const c=UI[lang],band=c.bands[result.band];app.innerHTML=top()+`<main class="panel result result-page">${shared?`<div class="shared">↗ ${c.shared}</div>`:''}<span class="kicker">${c.result}</span><div class="score">${fmt(result.score)}</div><div>${c.points}</div><h1>${band[0]}</h1><p class="result-lead">${band[1]}</p><div class="stat-grid"><div class="stat"><b>${result.correct}/${result.logical}</b><span>${c.logicStat}</span></div><div class="stat"><b>${(result.absurdMs/1000).toFixed(2)}s</b><span>${c.absurdStat}</span></div><div class="stat"><b>${(result.avgMs/1000).toFixed(2)}s</b><span>${c.tempoStat}</span></div></div><section class="readout"><h2>${c.why}</h2><p>${result.band<2?c.notice:band[1]}</p></section><div class="actions"><button class="primary" id="share">↗ ${c.share}</button><button class="secondary" id="again">${c.again}</button><a class="secondary" href="../../">${c.other}</a></div><p class="safe">🔒 ${c.safe}</p></main>`;bindTop();document.querySelector('#again').onclick=start;document.querySelector('#share').onclick=share}
async function share(){const c=UI[lang],base=globalThis.PT_CONFIG?.onlineUrl('tests/anti-iq/')||new URL('./',location.href).href,url=`${base}#r=${encode({...result,lang})}`,title=`${UI[lang].bands[result.band][0]} · Anti-IQ`,text=fill(c.shareText,{score:fmt(result.score),title:UI[lang].bands[result.band][0]});try{if(navigator.share)await navigator.share({title,text,url});else{await navigator.clipboard.writeText(`${text} ${url}`);toast(c.copied)}}catch(e){if(e?.name!=='AbortError')toast(c.copied)}}
function toast(text){const box=document.querySelector('#toast');box.textContent=text;box.classList.add('show');setTimeout(()=>box.classList.remove('show'),1800)}
function renderCurrent(){if(result)showResult(location.hash.startsWith('#r='));else if(order.length&&at<order.length)question();else intro()}
const shared=location.hash.startsWith('#r=')?decode(location.hash.slice(3)):null,view=new URLSearchParams(location.search);if(validResult(shared)){result=shared;if(LANGS.includes(shared.lang))lang=shared.lang;showResult(true)}else if(view.get('retake')==='1'){start()}else if(view.get('view')==='result'){try{const saved=JSON.parse(localStorage.getItem('pt.antiIq.result')||'null');if(validResult(saved)){result=saved;showResult(false)}else intro()}catch{intro()}}else intro();
