const COPY={
  ru:{
    ui:{normal:'😇 Спокойно',humor:'🎭 С юмором',toneLabel:'Как рассказать результат',locked:'Главный вердикт готов',unlock:'Открыть вердикт',unlocked:'Вердикт открыт',strength:'Что вас сближает',friction:'Где может искрить',advice:'Что реально поможет',details:'Нажмите на сферу — покажем, откуда взялась оценка',why:'Почему так',sharePair:'Поделиться нашим результатом',shareSafe:'В ссылке будут имена и готовый результат пары. Даты рождения не передаются.',rankOpen:'Открыть пояснение',rankWhy:'Почему подходит',rankRisk:'Где возможна сложность',rankTip:'Что поможет'},
    bands:{
      fragile:{normal:['Очень разные способы строить близость','Сочетание, которому нужны ясные договорённости'],humor:['Инструкция к этому союзу толще, чем договор ипотеки','Притяжение есть, а заводские настройки явно из разных коробок']},
      contrast:{normal:['Различия заметны, но ими можно управлять','Союз контрастов с несколькими важными условиями'],humor:['Вместе можно, но техподдержка отношениям понадобится','Совместимость в режиме: «а давай ещё раз нормально объясним»']},
      sparks:{normal:['Контакт есть, а ритм ещё предстоит настроить','Живое сочетание с заметными точками роста'],humor:['Искры летят — иногда от химии, иногда от короткого замыкания','Взаимный интерес есть. Инструкция по эксплуатации потерялась']},
      workable:{normal:['Хорошая основа, если не замалчивать различия','Устойчивое сочетание с пространством для настройки'],humor:['Нормально склеились — главное не проверять шов бытовухой каждый день','Союз рабочий: романтика загружается, мелкие баги известны']},
      strong:{normal:['Сильное сочетание с хорошим запасом взаимопонимания','Много естественных точек совпадения'],humor:['Два сапога пара, и оба знают, где лежит второй носок','Один придумал странную идею — второй уже добавил её в корзину']},
      close:{normal:['Очень близкий ритм и заметная взаимная поддержка','Редко удобное сочетание характеров'],humor:['Выпинывать будешь — далеко всё равно не уйдёт','Можете молча залипать в телефоны и считать это качественным свиданием']},
      rare:{normal:['Необычно цельное сочетание по выбранным системам','Максимально близкий символический ритм'],humor:['Слиплись на уровне космического Wi‑Fi','Подозрительно хорошо совпали. Проверьте, не читаете ли мысли друг друга']}
    },
    elements:{
      air_air:['Оба цените разговор, свободу мысли и движение идей.','Два генератора идей: вкладок много, скуки мало.'],air_fire:['Огонь запускает действие, воздух подбрасывает идеи и поддерживает азарт.','Один зажигает, второй раздувает — главное не спалить общий календарь.'],air_earth:['Один слой ищет свободу и варианты, другой — надёжность и конкретику.','Один строит воздушный замок, второй уже спрашивает смету и сроки.'],air_water:['Разум и чувства говорят на разных диалектах, зато способны многому научить друг друга.','Один объясняет логикой, второй считывает паузу между сообщениями.'],fire_fire:['Темп высокий, инициатива взаимная, а конкуренция включается быстро.','Два двигателя, один руль и ни одного желания ехать медленно.'],earth_fire:['Инициатива встречается с практичностью: хороший союз, если скорость согласована.','Один уже стартовал, второй ещё проверяет гарантию и собирает документы.'],fire_water:['Прямота и чувствительность создают сильное притяжение, но требуют бережной подачи.','Один сказал как есть, второй услышал ещё три скрытых смысла.'],earth_earth:['Важны надёжность, понятные планы и поступки вместо обещаний.','Романтика по расписанию тоже романтика, особенно если столик забронирован заранее.'],earth_water:['Практичность даёт опору эмоциям, а эмоциональность добавляет отношениям глубину.','Один приносит плед, второй объясняет, почему этот плед сейчас жизненно необходим.'],water_water:['Эмоциональная чувствительность высокая, поэтому настроение быстро становится общим.','Один вздохнул — второй уже понял сюжет, причину и возможный финал.']
    },
    numberRelations:{same:['Похожие числа сознания дают узнаваемый способ реагировать и принимать решения.','Настройки похожи: иногда понимаете без слов, иногда одинаково упрямитесь.'],near:['Числовые роли достаточно близки, чтобы быстро находить общий способ действия.','Механика похожая, но кнопки расположены чуть по-разному.'],mixed:['Числа дают разные, но взаимодополняющие роли в паре.','Один открывает квест, второй внезапно знает, где лежит нужный ключ.'],contrast:['Числовые роли заметно различаются; особенно важны ясные ожидания.','У одного инструкция на одну страницу, у второго — режиссёрская версия на три часа.']},
    strong:{communication:['Разговор легче возвращает вас на одну сторону.','Можете начать со спора, а закончить общей шуткой и заказом еды.'],emotions:['Поддержку проще замечать и принимать без длинных объяснений.','Эмоциональный Wi‑Fi ловит даже через стену и режим «я в порядке».'],daily:['Бытовые договорённости способны работать без постоянного контроля.','Есть шанс делить быт без международного суда из-за кружки в раковине.'],attraction:['Между вами легко появляется интерес и желание быть ближе.','Химия включается быстрее, чем здравый смысл успевает открыть инструкцию.'],pace:['Похожий темп уменьшает ощущение, что одного постоянно торопят или тормозят.','Идёте примерно с одной скоростью — никто не тащит другого за капюшон.'],repair:['После напряжения вам проще вернуться к разговору и восстановить контакт.','Можете поссориться, остыть и не открывать сезон сериала «молчание на трое суток».']},
    friction:{communication:['Не додумывайте интонацию за другого — уточняйте смысл прямо.','Главный враг — сообщение «ясно». Оно никогда не означает просто «ясно».'],emotions:['Потребность в близости и личном пространстве может различаться.','Один хочет обниматься, второй в этот момент хочет, чтобы его не трогали даже уведомления.'],daily:['Ожидания о порядке и обязанностях лучше назвать заранее.','Любовь любовью, но кто-то всё равно должен вспомнить про мусор и туалетную бумагу.'],attraction:['Сильная искра не заменяет договорённости и уважение к границам.','Химия отличная, но одной химией аренду и обиды не закроешь.'],pace:['Решения могут созревать с разной скоростью.','Один уже выбрал отпуск, второй ещё не согласился выйти из дома.'],repair:['После конфликта один может искать разговор, а другой — паузу.','Один готов мириться сейчас, второй ещё мысленно выигрывает спор в душе.']},
    advice:{communication:['Повторите мысль друг друга своими словами, прежде чем отвечать.','Запретите на сутки фразу «ты сам всё понимаешь». Спойлер: не понимает.'],emotions:['Спросите: сейчас нужна поддержка, совет или немного пространства?','Введите три режима: обнять, выслушать, отойти и принести вкусное.'],daily:['Разделите три повторяющихся дела и пересмотрите договор через неделю.','Два одеяла и понятная очередь за мусором спасли больше союзов, чем красивые цитаты.'],attraction:['Не превращайте яркость начала в требование постоянно держать ту же интенсивность.','Иногда нормальное свидание — это еда, тишина и никто не выясняет отношения в 01:40.'],pace:['Для важного решения сразу назначьте срок, когда вернётесь к нему.','Поставьте дедлайн даже романтике: иначе один уже живёт вместе, другой ещё печатает ответ.'],repair:['Заранее договоритесь, сколько длится пауза и кто возвращает разговор.','Ссориться можно. Исчезать в туман без срока возврата — уже плохой сериал.']}
  },
  en:{
    ui:{normal:'😇 Calm',humor:'🎭 With humor',toneLabel:'How to tell the story',locked:'Your main verdict is ready',unlock:'Reveal verdict',unlocked:'Verdict revealed',strength:'What brings you together',friction:'Where sparks may fly',advice:'What actually helps',details:'Tap a category to see what shaped the score',why:'Why this result',sharePair:'Share our result',shareSafe:'The link includes names and the ready result. Birth dates are not shared.',rankOpen:'Open explanation',rankWhy:'Why it fits',rankRisk:'Possible friction',rankTip:'What helps'},
    bands:{fragile:{normal:['Very different ways of building closeness','A match that needs clear agreements'],humor:['This relationship manual is thicker than a mortgage contract','There is attraction, but your factory settings came from different boxes']},contrast:{normal:['Clear differences that can still be managed','A contrasting match with a few important conditions'],humor:['It can work, but the relationship may need tech support','Compatibility mode: “let me explain that one more time”']},sparks:{normal:['There is a connection; the rhythm still needs tuning','A lively match with visible room to grow'],humor:['Sparks are flying—sometimes chemistry, sometimes a short circuit','Mutual interest found. User manual missing']},workable:{normal:['A good base when differences are not ignored','A steady match with room for adjustment'],humor:['Nicely glued together—just do not stress-test it with chores daily','The relationship runs; a few known bugs remain']},strong:{normal:['A strong match with plenty of mutual understanding','Many natural points of connection'],humor:['Two matching shoes, and both know where the missing sock went','One imagines a weird idea; the other has already added it to cart']},close:{normal:['A very close rhythm with visible mutual support','An unusually comfortable character match'],humor:['Even if pushed away, nobody is going very far','You can scroll in silence and call it quality time']},rare:{normal:['An unusually cohesive match in these traditions','An exceptionally close symbolic rhythm'],humor:['Connected through cosmic Wi‑Fi','Suspiciously compatible. Check for accidental mind-reading']}},
    elements:{air_air:['Both value conversation, freedom of thought, and moving ideas.','Two idea generators: many tabs, very little boredom.'],air_fire:['Fire starts action while air feeds ideas and excitement.','One lights the spark, the other fans it—keep the shared calendar safe.'],air_earth:['One seeks options and freedom; the other wants reliability and specifics.','One builds a castle in the air; the other requests a quote and deadline.'],air_water:['Logic and feeling use different dialects but can teach each other a lot.','One explains with logic; the other reads the pause between messages.'],fire_fire:['High pace, shared initiative, and quick competition.','Two engines, one steering wheel, zero interest in driving slowly.'],earth_fire:['Initiative meets practicality when both agree on speed.','One has started; the other is checking the warranty and paperwork.'],fire_water:['Directness and sensitivity create attraction but need careful delivery.','One says it plainly; the other hears three hidden meanings.'],earth_earth:['Reliability, clear plans, and actions matter more than promises.','Scheduled romance is still romance when the table is booked.'],earth_water:['Practicality grounds emotion, while feeling adds depth.','One brings a blanket; the other explains why the blanket is emotionally essential.'],water_water:['Emotional sensitivity is high, so moods quickly become shared.','One sighs; the other already knows the plot, cause, and ending.']},
    numberRelations:{same:['Similar consciousness numbers create familiar reactions and decisions.','Similar settings: sometimes wordless understanding, sometimes synchronized stubbornness.'],near:['The number roles are close enough to find a shared way of acting.','Similar mechanics, slightly different button placement.'],mixed:['The numbers suggest different but complementary roles.','One starts the quest; the other somehow knows where the key is.'],contrast:['The number roles differ, so expectations need to be explicit.','One has a one-page manual; the other comes with a three-hour director’s cut.']},
    strong:{communication:['Conversation can bring you back to the same side.','A debate can end as a shared joke and a food order.'],emotions:['Support is easier to notice and receive.','Emotional Wi‑Fi works through walls and the phrase “I’m fine.”'],daily:['Everyday agreements can work without constant supervision.','Chores may be shared without an international trial over a cup in the sink.'],attraction:['Interest and closeness arise naturally.','Chemistry loads before common sense opens the manual.'],pace:['A similar pace means less pushing and pulling.','You move at roughly the same speed; nobody gets dragged by the hoodie.'],repair:['It is easier to reconnect after tension.','You can argue, cool down, and skip the three-day silent-series premiere.']},
    friction:{communication:['Do not invent the other person’s tone—ask what was meant.','The main enemy is “fine.” It is almost never just fine.'],emotions:['Needs for closeness and personal space may differ.','One wants a hug; the other wants even notifications to stop touching them.'],daily:['Name expectations about order and responsibility early.','Love is love, but somebody still has to remember trash bags.'],attraction:['Strong chemistry cannot replace boundaries and agreements.','Chemistry is great, but it cannot pay rent or settle every hurt.'],pace:['Decisions may mature at different speeds.','One picked the vacation; the other has not agreed to leave home.'],repair:['After conflict, one may want dialogue while the other needs a pause.','One is ready to reconcile; the other is still winning the shower argument.']},
    advice:{communication:['Repeat each other’s point in your own words before replying.','Ban “you know what I mean” for a day. Spoiler: they do not.'],emotions:['Ask whether support, advice, or space is needed right now.','Use three modes: hug, listen, or step back and bring snacks.'],daily:['Split three recurring tasks and review the deal in a week.','Two blankets and a clear trash schedule have saved many evenings.'],attraction:['Do not demand that early intensity stay at maximum forever.','Sometimes a good date is food, silence, and no 1:40 a.m. summit.'],pace:['Set a time to return to an important decision.','Give romance a deadline: one has moved in mentally while the other is typing.'],repair:['Agree how long a pause lasts and who restarts the talk.','Arguments happen. Vanishing without a return time is bad television.']}
  },
  kk:{
    ui:{normal:'😇 Байыппен',humor:'🎭 Әзілмен',toneLabel:'Нәтижені қалай айтамыз',locked:'Негізгі қорытынды дайын',unlock:'Қорытындыны ашу',unlocked:'Қорытынды ашылды',strength:'Сіздерді не жақындастырады',friction:'Қай жерде ұшқын шығуы мүмкін',advice:'Не көмектеседі',details:'Бағаны не қалыптастырғанын көру үшін бөлімді басыңыз',why:'Неге бұлай шықты',sharePair:'Ортақ нәтижемізбен бөлісу',shareSafe:'Сілтемеде есімдер мен дайын нәтиже болады. Туған күндер берілмейді.',rankOpen:'Түсіндірмені ашу',rankWhy:'Неге үйлеседі',rankRisk:'Қай жерде қиындық болуы мүмкін',rankTip:'Не көмектеседі'},
    bands:{fragile:{normal:['Жақындық құру тәсілдеріңіз өте бөлек','Нақты келісімді қажет ететін жұп'],humor:['Бұл одақтың нұсқаулығы ипотека келісімінен де қалың','Тартылыс бар, бірақ зауыттық баптаулар екі бөлек қораптан шыққан']},contrast:{normal:['Айырмашылық көп, бірақ оны басқаруға болады','Бірнеше маңызды шарты бар қарама-қарсы жұп'],humor:['Бірге болуға болады, бірақ қарым-қатынасқа техқолдау керек','Үйлесім режимі: «тағы бір рет дұрыстап түсіндірейін»']},sparks:{normal:['Байланыс бар, ортақ ырғақты әлі баптау керек','Өсуге мүмкіндігі бар жанды үйлесім'],humor:['Ұшқын бар: кейде химиядан, кейде қысқа тұйықталудан','Қызығушылық табылды, пайдалану нұсқаулығы жоғалған']},workable:{normal:['Айырмашылықты жасырмасаңыздар, негізі жақсы','Баптауға болатын тұрақты үйлесім'],humor:['Жақсы жабыстыңыздар, тек күнде тұрмыспен сынамаңыздар','Одақ жұмыс істеп тұр, ұсақ багтар белгілі']},strong:{normal:['Өзара түсінісу қоры мол күшті үйлесім','Табиғи сәйкестік көп'],humor:['Екі етік — бір жұп, жоғалған шұлықтың орнын да білесіздер','Бірі қызық ой айтады, екіншісі себетке салып қойған']},close:{normal:['Ырғақтарыңыз жақын, қолдау анық сезіледі','Мінездер сирек кездесетіндей ыңғайлы үйлескен'],humor:['Қусаңыз да алысқа кетпейді','Үндемей телефон қарап, оны жақсы кездесу деп санай аласыздар']},rare:{normal:['Таңдалған жүйелер бойынша өте тұтас үйлесім','Символдық ырғақтарыңыз ерекше жақын'],humor:['Ғарыштық Wi‑Fi арқылы қосылғансыздар','Күмәнді деңгейде үйлесесіздер: ой оқымайсыздар ма?']}},
    elements:{air_air:['Екеуіңізге де әңгіме, ой еркіндігі және идея қозғалысы маңызды.','Екі идея генераторы: бет көп, іш пыспайды.'],air_fire:['От әрекетті бастайды, ауа идея мен құлшынысты күшейтеді.','Бірі жағады, бірі үрлейді — ортақ күнтізбені өртемеңіздер.'],air_earth:['Бірі еркіндік пен нұсқа іздейді, екіншісі нақтылық пен сенімділік қалайды.','Бірі ауада сарай салады, екіншісі смета мен мерзімді сұрап тұр.'],air_water:['Ақыл мен сезім екі тілде сөйлегенмен, бір-бірінен көп нәрсе үйренеді.','Бірі логикамен түсіндіреді, екіншісі хабарлама арасындағы үзілісті оқиды.'],fire_fire:['Қарқын жоғары, бастама екеуіңізде де бар, бәсеке тез қосылады.','Екі қозғалтқыш, бір руль, баяу жүруге ниет жоқ.'],earth_fire:['Бастама мен практикалық көзқарас жылдамдық келісілсе жақсы жұмыс істейді.','Бірі бастап кетті, екіншісі кепілдік пен құжатты тексеріп жатыр.'],fire_water:['Туралық пен сезімталдық күшті тартылыс береді, бірақ сөзді абайлап айту керек.','Бірі ашық айтты, екіншісі тағы үш жасырын мағына естіді.'],earth_earth:['Сенімділік, нақты жоспар және іс уәдеден маңызды.','Кестедегі романтика да романтика, әсіресе үстел алдын ала алынған болса.'],earth_water:['Практикалық көзқарас сезімге тірек, ал сезім қарым-қатынасқа тереңдік береді.','Бірі көрпе әкеледі, екіншісі оның неге дәл қазір өте қажет екенін түсіндіреді.'],water_water:['Сезімталдық жоғары, сондықтан көңіл күй тез ортақ болады.','Бірі күрсінді, екіншісі оқиғаны, себебін және соңын түсініп қойды.']},
    numberRelations:{same:['Ұқсас сана сандары әрекет пен шешім тәсілін жақындатады.','Баптаулар ұқсас: кейде сөзсіз түсінесіздер, кейде бірге қырсығасыздар.'],near:['Сандық рөлдер ортақ әрекет тәсілін тез табуға жеткілікті жақын.','Механика бірдей, батырмалар сәл басқа жерде.'],mixed:['Сандар жұпта бөлек, бірақ бірін-бірі толықтыратын рөл береді.','Бірі квестті ашады, екіншісі кілттің қайда жатқанын біледі.'],contrast:['Сандық рөлдер бөлек, сондықтан күтуді анық айту маңызды.','Бірінде бір бет нұсқаулық, екіншісінде үш сағаттық режиссёрлік нұсқа.']},
    strong:{communication:['Әңгіме сіздерді қайтадан бір жаққа шығара алады.','Дауды ортақ әзілмен және тамақ тапсырысымен аяқтай аласыздар.'],emotions:['Қолдауды байқау және қабылдау оңайырақ.','Эмоциялық Wi‑Fi қабырға мен «бәрі жақсы» режимінен де өтеді.'],daily:['Тұрмыстық келісім тұрақты бақылаусыз жұмыс істей алады.','Раковинадағы кесе үшін халықаралық сот ашпай-ақ тұрмысты бөлуге болады.'],attraction:['Қызығушылық пен жақындасу табиғи пайда болады.','Химия ақыл нұсқаулықты ашқанша жүктеліп үлгереді.'],pace:['Ұқсас қарқын бір-біріңізді асықтырмауға көмектеседі.','Жылдамдықтарыңыз ұқсас, ешкімді киімінен сүйреудің қажеті жоқ.'],repair:['Кернеуден кейін сөйлесуге қайта оралу оңайырақ.','Ұрысып, тынышталып, үш күндік үнсіздік сериалын бастамайсыздар.']},
    friction:{communication:['Басқа адамның үнін ойдан қоспай, мағынасын нақты сұраңыз.','Негізгі жау — «түсінікті» деген хабарлама. Ол ешқашан жай ғана түсінікті емес.'],emotions:['Жақындық пен жеке кеңістікке қажеттілік әртүрлі болуы мүмкін.','Бірі құшақтағысы келеді, екіншісі хабарламаның өзі тимесе дейді.'],daily:['Тәртіп пен міндет туралы күтуді алдын ала атаңыз.','Махаббат махаббатпен, бірақ қоқыс пен қағазды біреу есіне түсіреді.'],attraction:['Күшті тартылыс шекара мен келісімді алмастырмайды.','Химия мықты, бірақ жалдау ақысы мен ренішті жалғыз өзі жаппайды.'],pace:['Шешім әртүрлі жылдамдықпен пісуі мүмкін.','Бірі демалысты таңдап қойды, екіншісі үйден шығуға әлі келіспеді.'],repair:['Жанжалдан кейін бірі сөйлескісі, екіншісі үзіліс алғысы келеді.','Бірі татуласуға дайын, екіншісі душта дауды әлі жеңіп жатыр.']},
    advice:{communication:['Жауап бермей тұрып, бір-біріңіздің ойын өз сөзіңізбен қайталаңыз.','«Өзің түсініп тұрсың» деген сөзге бір күн тыйым салыңыз. Түсінбейді.'],emotions:['Қазір қолдау, кеңес әлде кеңістік керек пе деп сұраңыз.','Үш режим енгізіңіз: құшақтау, тыңдау немесе тәтті әкеліп, тыныштық беру.'],daily:['Үш қайталанатын істі бөліп, бір аптадан кейін келісімді қараңыз.','Екі көрпе мен қоқыс кезегі талай кешті құтқарған.'],attraction:['Алғашқы күшті сезімді үнемі сол деңгейде ұстауды талап етпеңіз.','Кейде жақсы кездесу — тамақ, тыныштық және түнгі 01:40-та жиналыс жоқ.'],pace:['Маңызды шешімге қашан қайта оралатыныңызды белгілеңіз.','Романтикаға да мерзім қойыңыз: бірі бірге тұрып жатыр, екіншісі жауап теріп отыр.'],repair:['Үзіліс қанша созылатынын және әңгімені кім бастайтынын келісіңіз.','Ұрысуға болады. Қайту уақытын айтпай жоғалу — нашар сериал.']}
  },
  fr:{
    ui:{normal:'😇 Posément',humor:'🎭 Avec humour',toneLabel:'Comment raconter le résultat',locked:'Votre verdict principal est prêt',unlock:'Révéler le verdict',unlocked:'Verdict révélé',strength:'Ce qui vous rapproche',friction:'Là où ça peut grincer',advice:'Ce qui aide vraiment',details:'Touchez une dimension pour comprendre la note',why:'Pourquoi ce résultat',sharePair:'Partager notre résultat',shareSafe:'Le lien contient les prénoms et le résultat final. Les dates de naissance ne sont pas partagées.',rankOpen:'Ouvrir l’explication',rankWhy:'Pourquoi ça fonctionne',rankRisk:'Point de friction possible',rankTip:'Ce qui aide'},
    bands:{fragile:{normal:['Deux manières très différentes de créer de la proximité','Une combinaison qui demande des accords clairs'],humor:['Le mode d’emploi de ce duo dépasse le contrat de crédit','Il y a de l’attirance, mais les réglages viennent de deux boîtes différentes']},contrast:{normal:['Des différences nettes, mais gérables','Un duo contrasté avec quelques conditions importantes'],humor:['Ça peut marcher, mais prévoyez le support technique','Mode compatibilité : « attends, je réexplique »']},sparks:{normal:['Le contact existe, le rythme reste à accorder','Un duo vivant avec une belle marge de progression'],humor:['Des étincelles : parfois la chimie, parfois le court-circuit','Intérêt mutuel détecté, mode d’emploi introuvable']},workable:{normal:['Une bonne base si les différences sont dites','Une combinaison stable qui peut encore s’ajuster'],humor:['Bien collés, évitez juste le crash-test ménager quotidien','Le duo fonctionne, quelques bugs sont déjà connus']},strong:{normal:['Une combinaison forte et beaucoup de compréhension','De nombreux points d’accord naturels'],humor:['Deux chaussures de la même paire, chaussette perdue comprise','L’un imagine une idée étrange, l’autre l’a déjà mise au panier']},close:{normal:['Un rythme très proche et un soutien visible','Une compatibilité de caractères rarement aussi confortable'],humor:['Même en poussant, personne ne part très loin','Vous pouvez scroller en silence et appeler ça un rendez-vous réussi']},rare:{normal:['Une combinaison particulièrement cohérente dans ces traditions','Un rythme symbolique exceptionnellement proche'],humor:['Connectés au Wi‑Fi cosmique','Compatibilité suspecte : vérifiez la lecture de pensée']}},
    elements:{air_air:['Vous aimez tous les deux les échanges, la liberté et les idées.','Deux générateurs d’idées : beaucoup d’onglets, peu d’ennui.'],air_fire:['Le feu lance l’action, l’air nourrit les idées et l’élan.','L’un allume, l’autre souffle : protégez le calendrier commun.'],air_earth:['L’un cherche les options, l’autre la fiabilité et le concret.','L’un construit un château en l’air, l’autre demande le devis.'],air_water:['La logique et l’émotion parlent deux dialectes qui peuvent s’enrichir.','L’un explique par la logique, l’autre lit la pause entre deux messages.'],fire_fire:['Le rythme est élevé, l’initiative partagée et la compétition rapide.','Deux moteurs, un volant, aucune envie de ralentir.'],earth_fire:['L’initiative rencontre le pragmatisme quand la vitesse est négociée.','L’un démarre, l’autre vérifie la garantie et les papiers.'],fire_water:['La franchise et la sensibilité créent une forte attirance à manier avec soin.','L’un parle franchement, l’autre entend trois sens cachés.'],earth_earth:['La fiabilité, les plans clairs et les actes comptent beaucoup.','La romance planifiée reste romantique quand la table est réservée.'],earth_water:['Le concret stabilise l’émotion, qui donne en retour de la profondeur.','L’un apporte un plaid, l’autre explique pourquoi il est vital maintenant.'],water_water:['La sensibilité est forte et l’humeur devient vite commune.','L’un soupire, l’autre connaît déjà l’histoire, la cause et la fin.']},
    numberRelations:{same:['Des nombres proches donnent des réactions et décisions familières.','Réglages similaires : compréhension silencieuse ou entêtement synchronisé.'],near:['Les rôles numériques trouvent assez vite une façon commune d’agir.','Même mécanique, boutons placés un peu différemment.'],mixed:['Les nombres proposent des rôles différents mais complémentaires.','L’un ouvre la quête, l’autre sait déjà où se trouve la clé.'],contrast:['Les rôles diffèrent et demandent des attentes explicites.','L’un a une notice d’une page, l’autre la version longue de trois heures.']},
    strong:{communication:['Le dialogue peut facilement vous remettre du même côté.','Un débat peut finir en blague commune et commande de repas.'],emotions:['Le soutien est plus facile à voir et à recevoir.','Le Wi‑Fi émotionnel traverse même le mur du « tout va bien ».'],daily:['Les accords du quotidien peuvent fonctionner sans surveillance constante.','Le ménage peut se partager sans procès international pour une tasse.'],attraction:['L’intérêt et l’envie de proximité apparaissent naturellement.','La chimie démarre avant que la raison ouvre la notice.'],pace:['Un rythme proche réduit la sensation de pousser ou freiner l’autre.','Vous avancez à la même vitesse, personne ne tire l’autre par la capuche.'],repair:['Après une tension, le contact revient plus facilement.','Vous pouvez vous disputer sans lancer une série de trois jours de silence.']},
    friction:{communication:['Ne devinez pas le ton de l’autre : demandez le sens.','L’ennemi principal est « d’accord ». Il veut rarement dire seulement d’accord.'],emotions:['Le besoin de proximité et d’espace personnel peut différer.','L’un veut un câlin, l’autre ne veut même plus être touché par les notifications.'],daily:['Parlez tôt des attentes sur l’ordre et les responsabilités.','L’amour est là, mais quelqu’un doit penser aux poubelles.'],attraction:['Une forte chimie ne remplace ni les limites ni les accords.','La chimie est belle, mais elle ne paie pas le loyer ni toutes les blessures.'],pace:['Les décisions peuvent mûrir à des vitesses différentes.','L’un a choisi les vacances, l’autre n’a pas accepté de sortir.'],repair:['Après un conflit, l’un cherche le dialogue et l’autre une pause.','L’un veut se réconcilier, l’autre gagne encore la dispute sous la douche.']},
    advice:{communication:['Reformulez la pensée de l’autre avant de répondre.','Interdisez « tu sais très bien » pendant une journée. Non, pas toujours.'],emotions:['Demandez : soutien, conseil ou espace maintenant ?','Trois modes : enlacer, écouter, ou reculer avec quelque chose de bon.'],daily:['Partagez trois tâches récurrentes et revoyez l’accord dans une semaine.','Deux couvertures et un tour de poubelle clair sauvent bien des soirées.'],attraction:['N’exigez pas que l’intensité du début reste toujours maximale.','Parfois un bon rendez-vous, c’est manger en paix sans sommet à 1 h 40.'],pace:['Fixez le moment où vous reprendrez une décision importante.','Même la romance a besoin d’un délai : l’un a emménagé en pensée, l’autre écrit.'],repair:['Décidez combien dure une pause et qui relance la discussion.','Se disputer arrive. Disparaître sans heure de retour, c’est une mauvaise série.']}
  }
};

const pick=(items,index)=>items[index%items.length];
const fill=(text,values)=>Object.entries(values).reduce((result,[key,value])=>result.replaceAll(`{${key}}`,value),text);
const numberRelation=pair=>{const [a,b]=pair.split('_').map(Number),distance=Math.abs(a-b);return distance===0?'same':distance<=2?'near':distance>=5?'contrast':'mixed'};

export function narrativeUi(lang){return(COPY[lang]||COPY.ru).ui}

export function buildPairNarrative(result,names,lang='ru',tone='humor'){
  const C=COPY[lang]||COPY.ru,style=tone==='normal'?0:1,ctx=result.context;
  const band=C.bands[ctx.band][tone]||C.bands[ctx.band].normal;
  const element=C.elements[ctx.elementPair]||C.elements.air_earth;
  const relation=C.numberRelations[numberRelation(ctx.consciousnessPair)];
  const values={a:names[0],b:names[1]};
  return{
    tone,
    headline:fill(pick(band,ctx.variants.headline),values),
    element:element[style],
    numbers:relation[style],
    strength:C.strong[ctx.strongest][style],
    friction:C.friction[ctx.attention][style],
    advice:C.advice[ctx.attention][style],
    share:lang==='ru'?`У нас с ${names[1]} получилось ${result.overall}%. Главный вердикт лучше увидеть самому.`:lang==='kk'?`${names[1]} екеуміздің нәтижеміз — ${result.overall}%. Негізгі қорытындыны өзің көр.`:lang==='fr'?`Avec ${names[1]}, notre résultat est de ${result.overall} %. Le verdict vaut le détour.`:`${names[1]} and I got ${result.overall}%. You should see the main verdict yourself.`
  };
}

export function buildRankingDetail(item,lang='ru',tone='normal'){
  const C=COPY[lang]||COPY.ru,style=tone==='normal'?0:1;
  return{why:C.strong[item.strongest][style],risk:C.friction[item.attention][style],tip:C.advice[item.attention][style]};
}
