const LANGS=['ru','kk','en','fr'];
const COPY={
  ru:{language:'Язык',eyebrow:'ВАЖНО И ПОНЯТНО',title:'Конфиденциальность и условия',lead:'Коротко о том, что хранится на устройстве, что видит аналитика и как правильно пользоваться материалами сайта.',updated:'Обновлено: 15 сентября 2026',notice:'Мы не продаём личные данные и не собираем общую историю вашей активности. Вход и облако используются только по вашему выбору.',sections:[
    ['1. Что это за сервис',['Portable Tests предоставляет тесты, игры, расчёты и справочные материалы для знакомства с собой и отдыха. Это не профессиональная консультация и не официальный способ принимать важные решения.']],
    ['2. Сохранения, вход и комнаты',['Ответы и настройки сохраняются в браузере. Если вы входите через Google, PortHub получает имя, email и фото профиля и хранит защищённую сессию, игровые сохранения, рекорды и членство в созданных вами комнатах. Это нужно для продолжения игры на разных устройствах и рейтинга друзей.','Мы не храним пароль Google и не ведём общий учёт времени на сайте. Локальные данные удаляются через настройки браузера; облачная сессия завершается кнопкой выхода.']],
    ['3. Аналитика и cookie',['Мы используем Google Analytics 4, чтобы видеть посещаемость, тип устройства, примерный регион и обезличенные события: открытие раздела, начало и завершение теста, установку и нажатие кнопки «Поделиться».','Мы намеренно не передаём в аналитику имена, даты рождения, ответы, тексты снов и содержимое результатов. Google может обрабатывать технические данные и cookie по собственной политике конфиденциальности.']],
    ['4. Результаты и ссылки',['Результат остаётся на устройстве. Если вы сами нажмёте «Поделиться результатом», часть результата будет записана в ссылку и станет доступна человеку, которому вы её отправили. Обычная кнопка «Поделиться приложением» результат не передаёт.']],
    ['5. Внешние и партнёрские ссылки',['На сайте могут быть ссылки на сторонние игры, сервисы, магазины и авторов. У них действуют собственные правила. Партнёрские ссылки помечаются; покупка по такой ссылке может принести проекту комиссию без увеличения цены для пользователя.']],
    ['6. Ответственность',['Материалы по психологии, профессиям, Сюцай, астрологии и толкованию снов показывают возможные интерпретации. Они не заменяют врача, психолога, юриста или финансового консультанта. Не принимайте на их основе решения о здоровье, деньгах, безопасности, найме или отношениях без проверки реальных обстоятельств.']],
    ['7. Авторство и лицензии',['Наш интерфейс и собственный код защищены применимым законодательством. Сторонние игры, библиотеки, названия и изображения принадлежат своим правообладателям и используются по соответствующим лицензиям или с указанием источника.']],
    ['8. Связь и изменения',['Правила могут обновляться вместе с развитием проекта. Актуальная версия всегда размещается на этой странице. По вопросам можно написать через репозиторий проекта на GitHub.']]
  ]},
  kk:{language:'Тіл',eyebrow:'МАҢЫЗДЫ ЖӘНЕ ТҮСІНІКТІ',title:'Құпиялылық және пайдалану шарттары',lead:'Құрылғыда не сақталатыны, аналитика нені көретіні және сайт материалдарын қалай қолдану керегі туралы қысқаша.',updated:'Жаңартылды: 15 қыркүйек 2026',notice:'Біз жеке деректерді сатпаймыз және жалпы әрекет тарихын жинамаймыз. Кіру мен бұлтты сақтау тек өз таңдауыңызбен қосылады.',sections:[
    ['1. Бұл қандай сервис',['Portable Tests өзін тануға және демалуға арналған тесттер, ойындар, есептеулер мен анықтамалық материалдар ұсынады. Бұл кәсіби кеңес те, маңызды шешім қабылдаудың ресми тәсілі де емес.']],
    ['2. Сақтау, кіру және бөлмелер',['Жауаптар мен баптаулар браузерде сақталады. Google арқылы кірсеңіз, PortHub аты-жөніңізді, email және профиль суретін алып, қорғалған сессияны, ойын сақтауларын, рекордтар мен бөлме мүшелігін сақтайды. Бұл ойынды басқа құрылғыда жалғастыру және достар рейтингі үшін қажет.','Google құпиясөзі сақталмайды және сайттағы жалпы уақыт есептелмейді.']],
    ['3. Аналитика және cookie',['Келушілер санын, құрылғы түрін, шамамен аймақты және бөлімді ашу, тестті бастау не аяқтау, орнату және бөлісу сияқты иесіздендірілген оқиғаларды көру үшін Google Analytics 4 қолданамыз.','Есімдер, туған күндер, жауаптар, түс мәтіндері мен нәтиже мазмұны аналитикаға әдейі жіберілмейді. Google техникалық деректер мен cookie файлдарын өз құпиялылық саясаты бойынша өңдеуі мүмкін.']],
    ['4. Нәтижелер мен сілтемелер',['Нәтиже құрылғыда қалады. «Нәтижемен бөлісу» батырмасын өзіңіз бассаңыз, нәтиженің бір бөлігі сілтемеге жазылып, оны жіберген адамға көрінеді. «Қолданбамен бөлісу» батырмасы нәтижені жібермейді.']],
    ['5. Сыртқы және серіктестік сілтемелер',['Сайтта бөгде ойындарға, сервистерге, дүкендерге және авторларға сілтемелер болуы мүмкін. Олардың өз ережелері қолданылады. Серіктестік сілтеме белгіленеді; сол сілтеме арқылы сатып алу бағаны өсірмей жобаға комиссия әкелуі мүмкін.']],
    ['6. Жауапкершілік',['Психология, кәсіп, Сюцай, астрология және түс жору материалдары ықтимал түсіндірмелерді көрсетеді. Олар дәрігерді, психологты, заңгерді немесе қаржы кеңесшісін алмастырмайды.']],
    ['7. Авторлық және лицензиялар',['Біздің интерфейс пен төл код қолданыстағы заңмен қорғалады. Бөгде ойындар, кітапханалар, атаулар мен суреттер өз иелеріне тиесілі және тиісті лицензиялармен не дереккөз көрсетіліп пайдаланылады.']],
    ['8. Байланыс және өзгерістер',['Жоба дамыған сайын ережелер жаңаруы мүмкін. Өзекті нұсқа осы бетте болады. Сұрақтарды GitHub-тағы жоба репозиторийі арқылы жіберуге болады.']]
  ]},
  en:{language:'Language',eyebrow:'IMPORTANT AND CLEAR',title:'Privacy and terms',lead:'A short explanation of what stays on your device, what analytics can see, and how to use this site responsibly.',updated:'Updated: September 15, 2026',notice:'We do not sell personal data or build a general history of your activity. Sign-in and cloud storage are optional.',sections:[
    ['1. About the service',['Portable Tests provides quizzes, games, calculations, and reference material for self-exploration and leisure. It is not professional advice or an official basis for important decisions.']],
    ['2. Saves, sign-in, and rooms',['Answers and settings are stored in your browser. If you sign in with Google, PortHub receives your name, email, and profile picture and stores a protected session, game saves, scores, and memberships in rooms you join. This supports cross-device play and friends leaderboards.','We never receive your Google password and do not track total time across the site. Local data can be cleared in browser settings; the cloud session ends when you sign out.']],
    ['3. Analytics and cookies',['We use Google Analytics 4 to understand visits, device type, approximate region, and anonymous interactions such as opening a section, starting or completing a quiz, installing the app, and pressing Share.','We intentionally do not send names, birth dates, answers, dream text, or result contents to analytics. Google may process technical data and cookies under its own privacy policy.']],
    ['4. Results and shared links',['Results stay on your device. If you choose “Share result,” part of the result is placed in the link and becomes visible to its recipient. The ordinary “Share app” button does not include your result.']],
    ['5. External and affiliate links',['The site may link to third-party games, services, shops, and creators, which have their own terms. Affiliate links are labelled; a purchase through one may earn the project a commission without increasing your price.']],
    ['6. Responsibility',['Psychology, career, Syutsai, astrology, and dream material offers possible interpretations. It does not replace a doctor, psychologist, lawyer, or financial adviser. Do not use it alone for health, money, safety, hiring, or relationship decisions.']],
    ['7. Ownership and licences',['Our interface and original code are protected by applicable law. Third-party games, libraries, names, and images belong to their respective owners and are used under their licences or with attribution.']],
    ['8. Contact and changes',['These terms may change as the project develops. The current version is always published here. Questions can be sent through the project repository on GitHub.']]
  ]},
  fr:{language:'Langue',eyebrow:'IMPORTANT ET CLAIR',title:'Confidentialité et conditions',lead:'Une explication courte des données conservées sur votre appareil, de l’analytique et de l’usage responsable du site.',updated:'Mise à jour : 15 septembre 2026',notice:'Nous ne vendons pas les données personnelles et ne créons pas d’historique général de votre activité. Connexion et cloud restent facultatifs.',sections:[
    ['1. À propos du service',['Portable Tests propose des tests, jeux, calculs et contenus de référence pour la découverte de soi et les loisirs. Ils ne constituent pas un conseil professionnel ni une base officielle pour une décision importante.']],
    ['2. Sauvegardes, connexion et salons',['Les réponses et réglages restent dans le navigateur. Avec Google, PortHub reçoit nom, email et photo de profil et conserve une session protégée, les sauvegardes, scores et salons rejoints, afin de continuer sur plusieurs appareils et afficher le classement des amis.','Nous ne recevons jamais votre mot de passe Google et ne suivons pas votre temps total sur le site.']],
    ['3. Analytique et cookies',['Nous utilisons Google Analytics 4 pour connaître la fréquentation, le type d’appareil, la région approximative et des actions anonymisées : ouverture d’une rubrique, début ou fin d’un test, installation et partage.','Nous n’envoyons volontairement ni noms, ni dates de naissance, ni réponses, ni textes de rêves, ni contenu des résultats. Google peut traiter des données techniques et des cookies selon sa propre politique.']],
    ['4. Résultats et liens partagés',['Le résultat reste sur votre appareil. Si vous choisissez « Partager le résultat », une partie du résultat est placée dans le lien et devient visible pour son destinataire. « Partager l’application » n’inclut pas votre résultat.']],
    ['5. Liens externes et affiliés',['Le site peut renvoyer vers des jeux, services, boutiques et auteurs tiers soumis à leurs propres règles. Les liens affiliés sont signalés ; un achat peut rapporter une commission au projet sans augmenter votre prix.']],
    ['6. Responsabilité',['Les contenus liés à la psychologie, l’orientation, au Syutsai, à l’astrologie et aux rêves proposent des interprétations possibles. Ils ne remplacent ni médecin, ni psychologue, ni avocat, ni conseiller financier.']],
    ['7. Propriété et licences',['Notre interface et notre code original sont protégés par le droit applicable. Les jeux, bibliothèques, noms et images tiers appartiennent à leurs titulaires et sont utilisés selon leurs licences ou avec attribution.']],
    ['8. Contact et modifications',['Ces règles peuvent évoluer avec le projet. La version actuelle est toujours publiée ici. Vous pouvez nous contacter via le dépôt du projet sur GitHub.']]
  ]}
};

const $=selector=>document.querySelector(selector);
function language(){const saved=localStorage.getItem('pt.lang');if(LANGS.includes(saved))return saved;const browser=(navigator.language||'ru').slice(0,2).toLowerCase();return LANGS.includes(browser)?browser:'ru'}
function render(){const lang=language(),copy=COPY[lang];document.documentElement.lang=lang;document.title=`${copy.title} · Portable Tests`;$('#language').value=lang;$('#languageLabel').textContent=copy.language;$('#eyebrow').textContent=copy.eyebrow;$('#title').textContent=copy.title;$('#lead').textContent=copy.lead;$('#updated').textContent=copy.updated;$('#notice').textContent=copy.notice;$('#sections').replaceChildren(...copy.sections.map(([title,paragraphs],index)=>{const card=document.createElement('section');card.className='legal-card';const heading=document.createElement('h2');heading.textContent=title;card.append(heading,...paragraphs.map(text=>{const p=document.createElement('p');p.textContent=text;return p}));if(index===2){const link=document.createElement('a');link.href='https://policies.google.com/privacy';link.target='_blank';link.rel='noopener';link.className='contact';link.textContent='Google Privacy Policy ↗';card.append(link)}if(index===7){const link=document.createElement('a');link.href='https://github.com/zhanat-arch/Portable-Tests';link.target='_blank';link.rel='noopener';link.className='contact';link.textContent='GitHub · Portable Tests ↗';card.append(link)}return card}));}
$('#language').addEventListener('change',event=>{localStorage.setItem('pt.lang',event.target.value);window.dispatchEvent(new CustomEvent('pt-language-change',{detail:{lang:event.target.value}}));render()});
render();
