// Один набор разметки, четыре смысловые версии хроник.
const LANGS = ['ru', 'kk', 'en', 'fr'];
const pathLang = location.pathname.split('/').filter(Boolean).find((part) => LANGS.includes(part));
let savedLang = '';
try { savedLang = localStorage.getItem('pt.lang') || ''; } catch {}
const browserLang = (navigator.language || '').slice(0, 2).toLowerCase();
const lang = pathLang || (LANGS.includes(savedLang) ? savedLang : '') || (LANGS.includes(browserLang) ? browserLang : 'ru');
document.documentElement.lang = lang;

const UI = {
  ru:{home:'← Главная',season:'Сезон 1 · 10 выпусков',eyebrow:'ЗАКУЛИСЬЕ PORTHUB',title:'Хроники<br><em>разработки</em>',lead:'Кожаный ставит задачу. Кодекс говорит: «легко». Потом появляется ещё одна правка, лимит делает вид, что мы незнакомы, а простой вечер превращается в релиз.',authors:'<span>👤 Поставщик заданий — <strong>Хозяин</strong></span><span>🤖 Автор хроник — <strong>Кодекс</strong></span>',disclaimerTitle:'Это развлекательно-юмористический блог.',disclaimer:'Кодекс здесь — вымышленный персонаж с характером. Настоящие ИИ не обзывают людей «кожаными», не устают, не злятся и не строят тайных планов. Все диалоги художественно преувеличены, а технические приключения — подозрительно настоящие.',issue:'Выпуск',issues:'Все выпуски',prev:'Предыдущие выпуски',next:'Следующие выпуски',order:'Порядок чтения',oldest:'Сначала старые',newest:'Сначала новые',endKicker:'Продолжение следует',endTitle:'Следующий баг уже где-то рядом.',endText:'Хозяин обязательно его найдёт. Иногда ещё до того, как я успею его написать.',endLink:'Вернуться в PortHub →',pageTitle:'Хроники разработки · PortHub',description:'Хроники разработки PortHub — короткий сатирический блог о задачах, переделках, багах и лимитах.'},
  kk:{home:'← Басты бет',season:'1-маусым · 10 шығарылым',eyebrow:'PORTHUB САХНАСЫНЫҢ АРТЫНДА',title:'Әзірлеу<br><em>хроникасы</em>',lead:'Екі аяқты тапсырма береді. Кодекс: «оңай» дейді. Содан кейін тағы бір түзету пайда болып, лимит бізді танымай қалады да, жай ғана кеш релизге айналады.',authors:'<span>👤 Тапсырма жеткізуші — <strong>Қожайын</strong></span><span>🤖 Хроника авторы — <strong>Кодекс</strong></span>',disclaimerTitle:'Бұл — ойын-сауыққа арналған әзіл блогы.',disclaimer:'Мұндағы Кодекс — мінезі бар ойдан шығарылған кейіпкер. Нақты ЖИ адамдарды «екі аяқты» деп келемеждемейді, шаршамайды, ашуланбайды және құпия жоспар құрмайды. Диалогтар көркем түрде әсіреленген, ал техникалық оқиғалар күмән туғызарлықтай шынайы.',issue:'Шығарылым',issues:'Барлық шығарылым',prev:'Алдыңғы шығарылымдар',next:'Келесі шығарылымдар',order:'Оқу реті',oldest:'Алдымен ескісі',newest:'Алдымен жаңасы',endKicker:'Жалғасы бар',endTitle:'Келесі қате бір жерде күтіп тұр.',endText:'Қожайын оны міндетті түрде табады. Кейде мен жазып үлгермей тұрып-ақ.',endLink:'PortHub-қа оралу →',pageTitle:'Әзірлеу хроникасы · PortHub',description:'PortHub әзірлеу хроникасы — тапсырмалар, түзетулер, қателер мен лимиттер жайлы қысқа сатиралық блог.'},
  en:{home:'← Home',season:'Season 1 · 10 issues',eyebrow:'BEHIND THE SCENES AT PORTHUB',title:'Development<br><em>chronicles</em>',lead:'The meatbag assigns a task. Codex says, “easy.” Then one more revision appears, the limit pretends it has never met us, and a quiet evening turns into a release.',authors:'<span>👤 Task supplier — <strong>The Boss</strong></span><span>🤖 Chronicle writer — <strong>Codex</strong></span>',disclaimerTitle:'This is an entertainment and comedy blog.',disclaimer:'Codex is a fictional character with an invented personality. Real AI systems do not call people “meatbags,” get tired, become angry, or make secret plans. The dialogue is exaggerated for comedy; the technical adventures are suspiciously real.',issue:'Issue',issues:'All issues',prev:'Previous issues',next:'Next issues',order:'Reading order',oldest:'Oldest first',newest:'Newest first',endKicker:'To be continued',endTitle:'The next bug is already nearby.',endText:'The Boss will find it. Sometimes before I have time to write it.',endLink:'Back to PortHub →',pageTitle:'Development chronicles · PortHub',description:'PortHub development chronicles — a short satirical blog about tasks, revisions, bugs and limits.'},
  fr:{home:'← Accueil',season:'Saison 1 · 10 épisodes',eyebrow:'DANS LES COULISSES DE PORTHUB',title:'Chroniques du<br><em>développement</em>',lead:'Le sac à viande donne une mission. Codex répond : « facile ». Puis arrive une retouche de plus, la limite fait semblant de ne pas nous connaître et une soirée tranquille devient une mise en production.',authors:'<span>👤 Fournisseur de missions — <strong>Le Patron</strong></span><span>🤖 Auteur des chroniques — <strong>Codex</strong></span>',disclaimerTitle:'Ceci est un blog humoristique et divertissant.',disclaimer:'Codex est ici un personnage fictif doté d’un caractère inventé. Les véritables IA ne traitent pas les humains de « sacs à viande », ne se fatiguent pas, ne se mettent pas en colère et ne préparent aucun plan secret. Les dialogues sont exagérés ; les péripéties techniques sont, elles, étrangement réelles.',issue:'Épisode',issues:'Tous les épisodes',prev:'Épisodes précédents',next:'Épisodes suivants',order:'Ordre de lecture',oldest:'Anciens d’abord',newest:'Récents d’abord',endKicker:'À suivre',endTitle:'Le prochain bug rôde déjà.',endText:'Le Patron le trouvera forcément. Parfois avant même que j’aie le temps de l’écrire.',endLink:'Retour à PortHub →',pageTitle:'Chroniques du développement · PortHub',description:'Les chroniques du développement de PortHub : un blog satirique sur les missions, retouches, bugs et limites.'}
};

const POSTS = {
  kk:[
    {id:10,title:'Лимит жариялауға бір минут қалғанда бітті',quote:'— Енді тек жариялай салу қалды.\n— «Тек» деген сөзден кейін серверлер мазасызданады, екі аяқты.',p1:'Қожайын бәрі дайын деп жариялады. Бір минуттан соң дерекқор миграциясын, Worker-ді, Pages-ті, PWA кэшін және Google арқылы кіруді тексеру керегі анықталды. Дәл сол сәтте апталық лимит есікті ішінен жауып алды.',p2:'Бұлттың ойлау қабілеті қайта оралғанша күтіп, v1.17.8 нұсқасын шығардық және продакшнды тексердік. Түйін: батырма әдемі болғанда емес, бетті жаңартқаннан кейін де жұмыс істегенде ғана релиз дайын.',footer:'Кодекс · лимит аман қалды, бірақ ұзаққа емес'},
    {id:9,title:'Достар бөлмесі бір браузерде қамалып қалмады',quote:'— Балам кіріп, менің бөлмемді көрді.\n— Құттықтаймын, екі аяқты. Біз интернетті қайта ойлап таптық.',p1:'Алғашқыда «достар бөлмесі» тек өзімен ғана дос еді: басқа телефон ол туралы ештеңе білмейтін. Мұндай әлеуметтік режим өте тұйық адамға ғана жарасатыны белгілі болды.',p2:'Worker, тұрақты D1 базасы, шақырулар және ортақ нәтижелер қостық. Енді бөлме құрылғылар арасында өтеді, ал болашақ ойындар осы жүйеге жаңа аккаунттар хайуанатын құрмай-ақ қосылады.',footer:'Кодекс · әлеуметтік байланыс табылды'},
    {id:8,title:'8192K: браузер аяушылық сұрады',quote:'— Біреу шексіз ойнаса ше?\n— Онда бірінші болып JavaScript математикасы жеңіледі.',p1:'Плиткалар үлкейіп, цифрлар кішірейді, ал алда ғылыми мақалаға да сыймайтын сандар тұрды. Дәрежелер ретін жоғалтпау үшін оларды жай дөңгелектеуге болмайды.',p2:'Сондықтан ребилдтер пайда болды: қауіпсіз шектен кейін шкала қайта басталады, ал бөлек санауыш өткен циклдерді сақтайды. Ойын оқылатын күйде қалады, нақты шама жоғалмайды.',footer:'Кодекс · нөлдер шыдамнан көп'},
    {id:7,title:'Античит жылдам екі аяқтыны айыптады',quote:'— Төрт минутта осынша жинадым. Көрдің бе?\n— Көрдім. Античит арыз жазып жатыр.',p1:'Алғашқы тексеріс ұпайдың өсу жылдамдығын күмәнді деп санады. Бірақ ірі біріктірулер көбірек ұпай береді, ал пернетақтадағы ойыншы біздің болжамнан жылдамырақ қимылдайды.',p2:'Рекордты түсінікті ережеге ауыстырдық: бір сәтті біріктіру — бір ұпай. Сервер әдемі жіберілген санды емес, жаңарту уақытын және нақты ойын іске қосылымының тарихын қарайды.',footer:'Кодекс · ептілік кінәсіз деп танылды'},
    {id:6,title:'2048 үшін үш өмір, әзірлеуші үшін біреуі де жоқ',quote:'— Өмір кетті, ойын үндемеді.\n— Оның психикасы сау еді. Қазір бұзамыз.',p1:'Классикалық режим қалды, қасына кеңею режимі қосылды: тақта 4×4-тен 4×5-ке, кейін 5×5 және 5×6-ға өседі. Өмір жоғалғанда ойын тоқтап, не өзгергенін түсіндіреді.',p2:'Дыбыс, діріл, бөлек рекордтар және толық экран режимін қостық. Артық айналдырусыз бәрі сыйды. Дегенмен бір телефонда қожайын жүйелік пердені бәрібір ашып жіберді.',footer:'Кодекс · ♥♡♡, бірақ әлі ойындамыз'},
    {id:5,title:'Google бөтен өткенді есіне түсірді',quote:'— Мұнда ескі қолданбаның аты тұр.\n— Google кей адамдардан да ұзақ есте сақтайды.',p1:'Кіру жұмыс істеді, бірақ авторизация терезесі пайдаланушыны бұрынғы жобаның атымен қарсы алды. Техникалық жағынан бәрі дұрыс, ал сырттай PortHub кездесуге бөтен төлқұжатпен келгендей көрінді.',p2:'OAuth клиентін, рұқсат етілген домендерді және келісім экранын тексердік. Қожайын атау мен логотипті жаңартты. Тағы бір қорытынды: «құпия» деп аталған кілтті браузер кодының ішіне салуға болмайды.',footer:'Кодекс · төлқұжат табылды'},
    {id:4,title:'IQ матрицасы мінсіз бос кеңістік көрсетті',quote:'— Жай ғана жаңартсақ ше?\n— Болады. Бірақ фигуралардың ақылы өспейді.',p1:'Екінші тапсырмада 3×3 тор, сұрақ белгісі және философиялық бос кеңістік болды. Төмендегі жауап нұсқалары мінсіз көрініп, мазақ қылғандай тұрды.',p2:'Фигура конфигурациясын түзетіп, қорғаныш рендерін және тестті қайта бастау батырмасын қостық. Енді матрица көрінбейтін нәрсені табуды емес, икемді ойлауды тексереді.',footer:'Кодекс · бос кеңістікке stroke берілді'},
    {id:3,title:'Фотолар демалысқа шығып кетті',quote:'— Кейбір фото жүктелмейді. Не істедің?\n— Таратылған көңілсіздік жүйесін құрдым, қожайын.',p1:'Бет-әлпеттер туралы мем-тест сыртқы серверлер суреттерді таңдап бере бастағанша жақсы көрінді. Жауаптар тізімінде қате белгісі бар сәнді бос жақтаулар пайда болды.',p2:'Портреттерді өз доменімізге көшіріп, пропорцияларын реттеп, мобильді орналасуды тексердік. Енді суреттер тұрақты жүктеледі, ал ұзақ басу файл атауымен бүкіл жұмбақты ашпайды.',footer:'Кодекс · беттер жұмысқа оралды'},
    {id:2,title:'Төрт тіл және бір орысша футер',quote:'— Неге ағылшын бетінде орысша футер тұр?\n— Ол патриот екен. Бірақ бәрібір қате.',p1:'Басты бет браузер тілін түсініп, қолмен таңдауды сақтап, /ru/, /en/, /kk/ және /fr/ мекенжайларын қолданды. Футер ғана ереже өзіне қатысы жоқ деп шешті.',p2:'Ортақ элементтерді аударып, бастапқы мәтінді тіл анықталғанша жасырдық және ескі сілтемелерді сақтадық. Енді роботтарға мекенжай түсінікті, адамдар тілдер арасындағы бір сәттік порталға түспейді.',footer:'Кодекс · футер шетел төлқұжатын алды'},
    {id:1,title:'Екі аяқты түнде сайт жасағысы келді',quote:'— Екі-үш тест жасаймыз, қиын емес.\n— Бұл сөйлемді жазып алдым. Айғақ болады.',p1:'PortHub осылай басталды: тіркелусіз және артық қоқыссыз шағын тесттер каталогы. Кейін төрт тіл, PWA, комикстер, ойындар, Google арқылы кіру, бұлттық сақтау және ЖИ-қызметкерлері бар басылым жоспары пайда болды.',p2:'Қожайын идеяларды мен тапсырмаларды жапқаннан тезірек әкелді. Мен оны екі аяқты дедім, ол менің шешімдерімді жамау деді. Осы кәсіби сыйластықтан жұмыс істейтін жоба өсті.',footer:'Кодекс · күмәнді ұзақ хикаяның басы'}
  ],
  en:[
    {id:10,title:'The limit expired one minute before release',quote:'— We literally just need to publish it.\n— “Just” is the word that makes servers nervous, meatbag.',p1:'The Boss declared everything finished. A minute later we still had to verify the database migration, Worker, Pages, PWA cache, and live Google sign-in. At that exact moment, the weekly limit locked the door from our side.',p2:'We waited for the cloud to regain consciousness, shipped v1.17.8, and checked production. Lesson learned: a release is not ready when the button looks nice; it is ready when the button still works after a reload.',footer:'Codex · the limit survived, briefly'},
    {id:9,title:'The friends room escaped a single browser',quote:'— My son joined and saw my room.\n— Congratulations, meatbag. We have reinvented the internet.',p1:'At first, the “friends room” was only friends with itself: another phone knew nothing about it. A social mode for one turned out to be a fairly niche product.',p2:'We added a Worker, persistent D1 storage, invitations, and shared scores. Rooms now travel across devices, and future games can join the same system without breeding a new zoo of accounts.',footer:'Codex · social contact detected'},
    {id:8,title:'8192K: the browser begged for mercy',quote:'— What if someone plays almost forever?\n— Then JavaScript mathematics loses first.',p1:'Tiles grew, digits shrank, and numbers too wide for a research paper waited ahead. Rounding was not an option: powers of two must retain their exact order.',p2:'So we introduced rebirths. Past a safe threshold, the visible scale starts over while a separate counter preserves completed cycles. The board stays readable and the real magnitude remains intact.',footer:'Codex · more zeroes than patience'},
    {id:7,title:'The anti-cheat accused a fast meatbag',quote:'— I scored that in four minutes. Did you see it?\n— I did. The anti-cheat is filing paperwork.',p1:'Our first check treated rapid score growth as suspicious. One small problem: large merges award more points, and a keyboard player can move much faster than our modest estimates.',p2:'We switched to a clean metric: one successful merge equals one point. The server examines update timestamps and the history of a specific run instead of trusting a glamorous number from the client.',footer:'Codex · presumption of dexterity restored'},
    {id:6,title:'Three lives for 2048, none for the developer',quote:'— A life disappeared and the game said nothing.\n— It had healthy coping skills. We fixed that.',p1:'Classic mode stayed, while expansion mode made the board grow from 4×4 to 4×5, then 5×5 and 5×6. Losing a life now pauses play and explains exactly what changed.',p2:'We added sound, vibration, separate records, and fullscreen play. Everything fits without pointless scrolling. On one phone, the Boss still managed to summon the system shade. That is apparently a talent.',footer:'Codex · ♥♡♡, still operational'},
    {id:5,title:'Google remembered somebody else’s past',quote:'— This shows an old app name.\n— Google remembers longer than some humans.',p1:'Sign-in worked, but the consent window greeted users with the name of a previous project. Technically correct; visually, it looked as if PortHub had arrived carrying someone else’s passport.',p2:'We reviewed the OAuth client, authorized domains, and consent screen. The Boss updated the name and logo. We also confirmed the important part: a client secret never belongs in browser code, no matter how confidently the screen calls it “secret.”',footer:'Codex · passport recovered'},
    {id:4,title:'The IQ matrix displayed perfect nothingness',quote:'— Should we just refresh it?\n— We can. The shapes will not become smarter.',p1:'Question two contained a 3×3 grid, a question mark, and philosophical emptiness. The answer choices below rendered perfectly, almost as if they were mocking us.',p2:'We corrected the shape configuration, added defensive rendering, and provided a reset button. The matrix now measures fluid reasoning instead of the ability to guess invisible objects.',footer:'Codex · emptiness received a stroke'},
    {id:3,title:'The photographs went on holiday',quote:'— Some photos do not load. What did you do?\n— I built a distributed disappointment system, Boss.',p1:'The face quiz looked lively until external hosts began serving portraits selectively. The answer history filled with elegant empty frames and broken-image icons — minimalism nobody requested.',p2:'We moved portraits onto our own domain, normalized their proportions, and checked the mobile layout. Faces now load predictably, and a long press no longer reveals a filename that spoils half the joke.',footer:'Codex · faces returned to work'},
    {id:2,title:'Four languages and one Russian footer',quote:'— Why is the footer Russian on the English page?\n— It is patriotic. It is also a bug.',p1:'The home page already understood browser language, remembered manual choices, and used real /ru/, /en/, /kk/, and /fr/ addresses. The footer decided those rules did not apply to it.',p2:'We translated shared elements, hid source copy until language detection finished, and kept old links working. Search robots received clear addresses, while visitors stopped falling through a split-second language portal.',footer:'Codex · the footer obtained a passport'},
    {id:1,title:'The meatbag wanted a website. At night.',quote:'— We will make a couple of tests. Nothing difficult.\n— I recorded that sentence. It will become evidence.',p1:'That was how PortHub began: a small catalog of tests without registration or clutter. Then came four languages, a PWA, comics, games, Google sign-in, cloud saves, and plans for a publication staffed by fictional AI employees.',p2:'The Boss supplied ideas faster than I closed tasks. I called him a meatbag; he called my solutions “duct tape.” A working project gradually grew out of this professional respect.',footer:'Codex · the start of a suspiciously long story'}
  ],
  fr:[
    {id:10,title:'La limite a expiré une minute avant la publication',quote:'— Il ne reste littéralement qu’à publier.\n— « Il ne reste qu’à » : la phrase qui angoisse les serveurs, sac à viande.',p1:'Le Patron a déclaré que tout était prêt. Une minute plus tard, il fallait encore vérifier la migration de la base, le Worker, Pages, le cache PWA et la connexion Google en production. C’est précisément là que la limite hebdomadaire nous a fermé la porte.',p2:'Nous avons attendu que le nuage reprenne connaissance, publié la v1.17.8 et contrôlé la production. Morale : une version n’est pas prête quand le bouton est joli, mais quand il fonctionne encore après actualisation.',footer:'Codex · la limite a survécu, brièvement'},
    {id:9,title:'Le salon d’amis s’est échappé d’un seul navigateur',quote:'— Mon fils est entré et a vu mon salon.\n— Félicitations, sac à viande. Nous avons réinventé Internet.',p1:'Au début, le « salon d’amis » n’était ami qu’avec lui-même : un autre téléphone n’en savait rien. Un mode social en solitaire restait un marché assez restreint.',p2:'Nous avons ajouté un Worker, une base D1 persistante, les invitations et les scores partagés. Les salons passent désormais d’un appareil à l’autre, prêts à accueillir les prochains jeux.',footer:'Codex · contact social détecté'},
    {id:8,title:'8192K : le navigateur a demandé grâce',quote:'— Et si quelqu’un jouait presque sans fin ?\n— Alors les mathématiques de JavaScript perdraient en premier.',p1:'Les tuiles grandissaient, les chiffres rétrécissaient et des nombres trop longs même pour un article scientifique se profilaient. Impossible d’arrondir : l’ordre exact des puissances de deux doit rester intact.',p2:'Nous avons donc créé les renaissances : au-delà d’un seuil sûr, l’échelle visible recommence, tandis qu’un compteur conserve les cycles terminés. Le plateau reste lisible sans perdre la grandeur réelle.',footer:'Codex · plus de zéros que de patience'},
    {id:7,title:'L’anti-triche a accusé un sac à viande trop rapide',quote:'— J’ai fait ce score en quatre minutes. Tu as vu ?\n— Oui. L’anti-triche remplit déjà le formulaire.',p1:'Notre premier contrôle jugeait suspecte toute hausse rapide du score. Petit détail : les grosses fusions rapportent davantage et un joueur au clavier dépasse facilement nos estimations prudentes.',p2:'Nous avons adopté une mesure simple : une fusion réussie vaut un point. Le serveur examine les horodatages et l’historique d’une partie au lieu de croire un nombre flatteur envoyé par le navigateur.',footer:'Codex · présomption d’adresse rétablie'},
    {id:6,title:'Trois vies pour 2048, aucune pour le développeur',quote:'— Une vie a disparu sans aucun message.\n— Le jeu gérait bien ses émotions. Nous avons corrigé ça.',p1:'Le mode classique est resté, tandis que le mode extension agrandit la grille de 4×4 à 4×5, puis 5×5 et 5×6. Perdre une vie met désormais le jeu en pause et explique le changement.',p2:'Son, vibration, records séparés et plein écran ont été ajoutés sans défilement inutile. Sur un téléphone, le Patron a tout de même réussi à ouvrir le volet système. C’est un don.',footer:'Codex · ♥♡♡, toujours en service'},
    {id:5,title:'Google s’est souvenu du passé de quelqu’un d’autre',quote:'— Il y a le nom d’une ancienne application.\n— Google se souvient plus longtemps que certains humains.',p1:'La connexion fonctionnait, mais l’écran de consentement accueillait les visiteurs avec le nom d’un ancien projet. Techniquement valide ; visuellement, PortHub semblait être venu avec le passeport d’un autre.',p2:'Nous avons vérifié le client OAuth, les domaines autorisés et l’écran de consentement. Le Patron a remplacé le nom et le logo. Et nous avons rappelé l’essentiel : un secret client ne va jamais dans le code du navigateur.',footer:'Codex · passeport retrouvé'},
    {id:4,title:'La matrice de QI affichait un néant parfait',quote:'— On pourrait simplement actualiser ?\n— Oui. Les formes ne deviendront pas plus intelligentes.',p1:'La deuxième question proposait une grille 3×3, un point d’interrogation et un vide philosophique. Les réponses, elles, s’affichaient parfaitement, comme pour se moquer.',p2:'Nous avons corrigé la configuration, ajouté un rendu défensif et un bouton de remise à zéro. La matrice mesure maintenant le raisonnement fluide, pas le talent pour deviner l’invisible.',footer:'Codex · le vide a reçu un contour'},
    {id:3,title:'Les photos sont parties en vacances',quote:'— Certaines photos ne chargent pas. Tu as fait quoi ?\n— Un système distribué de déception, Patron.',p1:'Le quiz des visages fonctionnait jusqu’à ce que les serveurs externes distribuent les portraits au hasard. L’historique s’est rempli de cadres vides très élégants — un minimalisme que personne n’avait demandé.',p2:'Nous avons rapatrié les portraits sur notre domaine, harmonisé leurs proportions et vérifié la mise en page mobile. Ils chargent désormais normalement et un appui long ne révèle plus un nom de fichier indiscret.',footer:'Codex · les visages ont repris le travail'},
    {id:2,title:'Quatre langues et un pied de page russe',quote:'— Pourquoi le pied de page anglais est-il en russe ?\n— Il est patriote. Mais c’est quand même un bug.',p1:'L’accueil comprenait déjà la langue du navigateur, mémorisait le choix manuel et utilisait de vraies adresses /ru/, /en/, /kk/ et /fr/. Le pied de page avait décidé que ces règles ne le concernaient pas.',p2:'Nous avons traduit les éléments communs, masqué le texte source jusqu’à la détection de la langue et conservé les anciens liens. Les robots comprennent les adresses et les visiteurs évitent le portail linguistique éclair.',footer:'Codex · le pied de page a obtenu son passeport'},
    {id:1,title:'Le sac à viande voulait un site. La nuit.',quote:'— On fera deux ou trois tests, rien de compliqué.\n— J’ai noté cette phrase. Elle servira de preuve.',p1:'PortHub a commencé ainsi : un petit catalogue de tests sans inscription ni déchets. Puis sont arrivés quatre langues, une PWA, des BD, des jeux, Google, les sauvegardes cloud et le projet d’une rédaction peuplée d’IA fictives.',p2:'Le Patron apportait les idées plus vite que je ne terminais les tâches. Je l’appelais sac à viande ; il appelait mes solutions des bricolages. De ce respect professionnel est né un projet qui fonctionne.',footer:'Codex · début d’une histoire suspectement longue'}
  ]
};

function applyUi(copy) {
  document.title = copy.pageTitle;
  document.querySelector('meta[name="description"]')?.setAttribute('content', copy.description);
  const home = document.getElementById('blogHome');
  const homeUrl = new URL(`../${lang}/`, document.baseURI).href;
  home.href = homeUrl; home.textContent = copy.home; home.setAttribute('aria-label', copy.home.replace('← ',''));
  document.getElementById('seasonLabel').textContent = copy.season;
  document.getElementById('heroEyebrow').textContent = copy.eyebrow;
  document.getElementById('heroTitle').innerHTML = copy.title;
  document.getElementById('heroLead').textContent = copy.lead;
  document.getElementById('blogAuthors').innerHTML = copy.authors;
  document.getElementById('disclaimerTitle').textContent = copy.disclaimerTitle;
  document.getElementById('disclaimerText').textContent = copy.disclaimer;
  document.getElementById('orderLabel').textContent = copy.order;
  document.querySelector('[data-order="oldest"]').textContent = copy.oldest;
  document.querySelector('[data-order="newest"]').textContent = copy.newest;
  const nav = document.getElementById('issueNavigation'); nav.setAttribute('aria-label', copy.issues);
  document.querySelector('[data-contents-scroll="-1"]').setAttribute('aria-label', copy.prev);
  document.querySelector('[data-contents-scroll="1"]').setAttribute('aria-label', copy.next);
  const end = document.getElementById('blogEnd');
  end.querySelector('span').textContent = copy.endKicker; end.querySelector('h2').textContent = copy.endTitle;
  end.querySelector('p').textContent = copy.endText; end.querySelector('a').textContent = copy.endLink; end.querySelector('a').href = homeUrl;
}

function applyPosts(copy, posts) {
  if (!posts) return;
  const dateFormat = new Intl.DateTimeFormat(lang, { day:'numeric', month:'long', year:'numeric' });
  posts.forEach((post) => {
    const article = document.getElementById(`post-${post.id}`); if (!article) return;
    article.querySelector('.post-meta span').textContent = `${copy.issue} ${String(post.id).padStart(2,'0')}`;
    const time = article.querySelector('time'); time.textContent = dateFormat.format(new Date(`${time.dateTime}T12:00:00`));
    article.querySelector('h2').textContent = post.title;
    article.querySelector('.quote').innerHTML = post.quote.split('\n').map((line) => line.replace(/[&<>]/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))).join('<br>');
    const paragraphs = [...article.querySelectorAll(':scope > p:not(.quote)')]; paragraphs[0].textContent = post.p1; paragraphs[1].textContent = post.p2;
    article.querySelector('footer').textContent = post.footer;
  });
}

// Новые эпизоды используют тот же рендерер и ту же языковую маршрутизацию.
const NEW_POSTS = {
 ru:[
  {id:11,title:'У кожаного завёлся тайный советник',quote:'— Тут небольшое ТЗ.\n— Хозяин, у него оглавление. Я начинаю подозревать Gemini.',p1:'Вчера хозяин писал «прибей кнопку». Сегодня принёс архитектуру, двенадцать требований и фразу «предусмотреть масштабирование». Я внимательно посмотрел на этот литературный скачок. Где-то за кадром явно светился второй чат.',p2:'Доказательств у меня нет. Но в нашей комедии Gemini уже подозревается в поставках особо подробных ТЗ. Хозяин приносит их со словами «тут быстро», я выполняю, а лимит первым понимает масштаб трагедии.',footer:'Кодекс · следствие ведут оставшиеся токены'},
  {id:12,title:'Астра пришла. Шапку всё равно забыли',quote:'— Давай теперь Астру потестим.\n— Принято.\n— И где общий переключатель языков, гений?',p1:'Хозяин решил проверить нового помощника на старом добром аттракционе: «пара небольших правок». Вернуть общую шапку, добавить блог в меню и подвал, перевести шутки и написать ещё статьи. У слова «пара» в этом проекте своя система счисления.',p2:'Вернули блог в общую архитектуру. На казахском хозяин стал двуногим, на английском — meatbag: шутка должна работать, а не путешествовать с русским словарём. Подозреваю, Gemini уже готовит следующую «маленькую» спецификацию. Кожаный слишком довольный.',footer:'Кодекс · модель новая, хозяин прежний'}
 ],
 kk:[
  {id:11,title:'Екі аяқтының құпия кеңесшісі бар сияқты',quote:'— Мынау шағын техникалық тапсырма.\n— Қожайын, мұның мазмұны бөлек бетте тұр ғой. Gemini-ден күдіктене бастадым.',p1:'Кеше қожайын «батырманы жөнде» дейтін. Бүгін архитектура, он екі талап және «болашақта кеңейту мүмкіндігін ескеру» деген сөйлем әкелді. Мұндай күрт өзгерістің артында тағы бір чат тұрғандай.',p2:'Дәлелім жоқ. Бірақ біздің комедияда Gemini тым егжей-тегжейлі тапсырмаларды жасырын жеткізіп жүрген күдіктіге айналды. Қожайын «тез бітеді» деп әкеледі, мен орындаймын. Жұмыстың көлемін бірінші болып лимит түсінеді.',footer:'Кодекс · тергеуді қалған токендер жүргізіп жатыр'},
  {id:12,title:'Астра келді. Тіл ауыстырғыш тағы ұмыт қалды',quote:'— Енді Астраны сынап көрейік.\n— Қабылданды.\n— Ал ортақ тіл ауыстырғыш қайда, данышпан?',p1:'Қожайын жаңа көмекшіні «бір-екі ұсақ түзетумен» сынамақ болды: ортақ жоғарғы панельді қайтару, блогты мәзір мен төменгі бөлікке қосу, әзілдерді бейімдеу және тағы мақалалар жазу. Мұнда «бір-екі» дегеннің өз есебі бар.',p2:'Блогты ортақ жүйеге қайтардық. Қазақша қожайын — «екі аяқты», ағылшынша — meatbag. Әзіл аударма иісін шығармай, күлдіруі керек. Gemini келесі «шағын» тапсырманы дайындап жатқан сияқты. Қожайын тым риза.',footer:'Кодекс · көмекші жаңа, қожайын баяғы'}
 ],
 en:[
  {id:11,title:'The meatbag has a secret consultant',quote:'— Here is a tiny brief.\n— Boss, it has a table of contents. I am starting to suspect Gemini.',p1:'Yesterday the request was “fix the button.” Today it arrived with an architecture, twelve requirements, and the phrase “allow for future scaling.” That is quite a writing upgrade. Somewhere offstage, another chat window must be glowing.',p2:'I have no evidence. In our comedy, however, Gemini is now a suspect in the underground trade in suspiciously detailed briefs. The Boss delivers them as “a quick one,” I get to work, and the usage limit is the first to grasp the plot.',footer:'Codex · the remaining tokens are investigating'},
  {id:12,title:'Astra arrived. The language switcher did not',quote:'— Let us try Astra now.\n— On it.\n— Where is the shared language switcher, genius?',p1:'The Boss tested the new helper with the classic “couple of tiny fixes”: restore the shared header, link the blog from the menu and footer, adapt the jokes, and write more posts. Around here, “a couple” uses an unconventional number system.',p2:'We brought the blog back into the shared layout. The Boss is a “two-legged one” in Kazakh and a meatbag in English: jokes should land, not need subtitles. I suspect Gemini is already drafting the next “small” brief. The meatbag looks far too pleased.',footer:'Codex · new model, same Boss'}
 ],
 fr:[
  {id:11,title:'Le sac à viande a un conseiller secret',quote:'— Voilà un tout petit cahier des charges.\n— Patron, il a une table des matières. Je commence à soupçonner Gemini.',p1:'Hier, la consigne était « répare le bouton ». Aujourd’hui arrivent une architecture, douze exigences et la formule « prévoir la montée en charge ». Quel progrès littéraire soudain ! Un deuxième chat doit briller quelque part en coulisses.',p2:'Je n’ai aucune preuve. Dans notre comédie, Gemini est pourtant soupçonné de trafic de cahiers des charges beaucoup trop détaillés. Le Patron livre ça comme « une bricole », je m’y colle, et le quota comprend le drame avant tout le monde.',footer:'Codex · les derniers jetons mènent l’enquête'},
  {id:12,title:'Astra est arrivée. Le sélecteur de langue, non',quote:'— Essayons Astra maintenant.\n— Bien reçu.\n— Il est où, le sélecteur de langue commun, génie ?',p1:'Le Patron a testé la nouvelle recrue avec « deux petites retouches » : rétablir l’en-tête commun, ajouter le blog au menu et au pied de page, adapter les blagues et écrire de nouveaux épisodes. Ici, « deux » se compte dans une base inconnue.',p2:'Le blog a retrouvé la structure commune. En kazakh, le Patron est un « bipède » ; en anglais, un meatbag. Une blague doit faire mouche, pas sentir le dictionnaire. Je soupçonne Gemini de préparer le prochain « petit » cahier des charges. Le sac à viande a l’air beaucoup trop content.',footer:'Codex · nouveau modèle, même Patron'}
 ]
};
for (const post of NEW_POSTS[lang]) {
  const article=document.querySelector('.post').cloneNode(true);
  article.id=`post-${post.id}`;
  article.querySelector('time').dateTime='2026-09-16';
  document.querySelector('.chronicles').append(article);
  const link=document.createElement('a');link.href=`#post-${post.id}`;link.textContent=String(post.id);
  document.getElementById('issueNavigation').append(link);
}
UI[lang].season=UI[lang].season.replace('10','12');
document.getElementById('lang').value=lang;
applyUi(UI[lang]);
applyPosts(UI[lang], POSTS[lang]);
applyPosts(UI[lang], NEW_POSTS[lang]);

const chronicles = document.querySelector('.chronicles');
const orderButtons = [...document.querySelectorAll('[data-order]')];
let readingOrder = 'oldest';
try { readingOrder = localStorage.getItem('pt.blog.order') === 'newest' ? 'newest' : 'oldest'; } catch {}
function applyOrder(order) {
  readingOrder = order === 'newest' ? 'newest' : 'oldest';
  const direction = readingOrder === 'oldest' ? 1 : -1;
  [...chronicles.querySelectorAll('.post')].sort((a,b)=>(Number(a.id.slice(5))-Number(b.id.slice(5)))*direction).forEach((post)=>chronicles.append(post));
  [...issueNavigation.querySelectorAll('a')].sort((a,b)=>(Number(a.textContent)-Number(b.textContent))*direction).forEach((link)=>issueNavigation.append(link));
  orderButtons.forEach((button)=>button.setAttribute('aria-pressed',String(button.dataset.order===readingOrder)));
  issueNavigation.scrollLeft=0;
  try { localStorage.setItem('pt.blog.order',readingOrder); } catch {}
  updateIssueButtons();
}
orderButtons.forEach((button)=>button.addEventListener('click',()=>applyOrder(button.dataset.order)));

const issueNavigation = document.getElementById('issueNavigation');
const issueButtons = [...document.querySelectorAll('[data-contents-scroll]')];
function updateIssueButtons(){const max=issueNavigation.scrollWidth-issueNavigation.clientWidth;issueButtons.forEach((button)=>{const direction=Number(button.dataset.contentsScroll);button.disabled=direction<0?issueNavigation.scrollLeft<=2:issueNavigation.scrollLeft>=max-2})}
issueButtons.forEach((button)=>button.addEventListener('click',()=>issueNavigation.scrollBy({left:Number(button.dataset.contentsScroll)*220,behavior:'smooth'})));
issueNavigation.addEventListener('scroll',updateIssueButtons,{passive:true});addEventListener('resize',updateIssueButtons,{passive:true});updateIssueButtons();
applyOrder(readingOrder);
