const LANGS=['ru','kk','en','fr'];
const savedLang=(()=>{try{return localStorage.getItem('pt.lang')}catch{return null}})();
let lang=LANGS.includes(savedLang)?savedLang:(LANGS.includes((navigator.language||'ru').slice(0,2))?(navigator.language||'ru').slice(0,2):'ru');
const COPY={
 ru:{home:'На главную',eyebrow:'МИНИ-КОМИКС · ВЫПУСК 01',title:'Операция<br><em>«Ночной нуар»</em>',lead:'Шесть кадров. Два героя. Одна очень плохая ночь для Синдиката.',frame:'Кадр',share:'Поделиться комиксом',copied:'Ссылка на комикс скопирована',shareText:'Операция «Ночной нуар» — мини-комикс в шести кадрах.'},
 kk:{home:'Басты бетке',eyebrow:'МИНИ-КОМИКС · 01 ШЫҒАРЫЛЫМ',title:'Операция<br><em>«Түнгі нуар»</em>',lead:'Алты кадр. Екі қаһарман. Синдикат үшін өте сәтсіз түн.',frame:'Кадр',share:'Комикспен бөлісу',copied:'Комикс сілтемесі көшірілді',shareText:'«Түнгі нуар» операциясы — алты кадрлық мини-комикс.'},
 en:{home:'Home',eyebrow:'MINI COMIC · ISSUE 01',title:'Operation<br><em>“Night Noir”</em>',lead:'Six panels. Two heroes. One very bad night for the Syndicate.',frame:'Panel',share:'Share this comic',copied:'Comic link copied',shareText:'Operation “Night Noir” — a six-panel mini comic.'},
 fr:{home:'Accueil',eyebrow:'MINI-BD · ÉPISODE 01',title:'Opération<br><em>«Noir nocturne»</em>',lead:'Six cases. Deux héros. Une très mauvaise nuit pour le Syndicat.',frame:'Case',share:'Partager la BD',copied:'Lien de la BD copié',shareText:'Opération «Noir nocturne» — une mini-BD en six cases.'}
};
const PANELS=[
 {title:{ru:'Засада в неоне',kk:'Неондағы тұзақ',en:'Neon Ambush',fr:'Embuscade au néon'},n:{ru:'Тяжёлые капли дождя разбивались об асфальт неоновой крыши. Алекс замерла в полуприседе, когда из ночного тумана вынырнули бесшумные тени. Красные объективы боевых дронов захватили её в перекрестье прицелов.',kk:'Жаңбырдың ауыр тамшылары неонды шатырдың асфальтына соғылды. Алекс жартылай отыра қатып қалды: түнгі тұманнан үнсіз көлеңкелер шықты. Жауынгерлік дрондардың қызыл объективтері оны нысанаға алды.',en:'Heavy rain shattered across the neon rooftop. Alex froze in a crouch as silent shadows slipped out of the night fog. The red lenses of combat drones locked her in their sights.',fr:'La pluie martelait le toit baigné de néons. Alex se figea, accroupie, tandis que des ombres silencieuses surgissaient du brouillard. Les objectifs rouges des drones de combat la prirent pour cible.'},s:{ru:'Датчики молчат… Это засада Синдиката!',kk:'Датчиктер үнсіз… Бұл Синдикаттың тұзағы!',en:'Sensors are silent… It’s a Syndicate ambush!',fr:'Les capteurs sont muets… C’est une embuscade du Syndicat !'}},
 {title:{ru:'Энерго-западня',kk:'Энергиялық қақпан',en:'Energy Trap',fr:'Piège énergétique'},n:{ru:'Поднявшийся из пола силовой купол вспыхнул ослепительно синим светом. Энергетическая решётка мгновенно заблокировала микросхемы её костюма.',kk:'Еденнен көтерілген күш күмбезі көз қаратпайтын көк жарықпен жанды. Энергия торы оның костюмінің микросхемаларын бірден бұғаттады.',en:'A force dome rose from the floor in a blinding blue flash. The energy grid instantly jammed every circuit in her suit.',fr:'Un dôme de force jaillit du sol dans un éclair bleu aveuglant. La grille d’énergie bloqua aussitôt les circuits de sa combinaison.'},s:{ru:'Энергощит заблокировал костюм… Но Макс близко!',kk:'Энергия қалқаны костюмді бұғаттады… Бірақ Макс жақын!',en:'Energy shield jammed my suit… But Max is near!',fr:'Le bouclier bloque ma combinaison… Mais Max est proche !'}},
 {title:{ru:'Взрывной прорыв',kk:'Жарылыспен кіру',en:'Explosive Entry',fr:'Entrée explosive'},n:{ru:'Тяжёлая стальная дверь бункера разлетелась на тысячи осколков от мощнейшего удара. Сквозь дым и сноп искр вглубь комплекса шагнул Макс в экзо-броне.',kk:'Қуатты соққыдан бункердің ауыр болат есігі мыңдаған бөлшекке ұшты. Түтін мен ұшқын арасынан экзо-сауыт киген Макс кешенге кірді.',en:'The bunker’s steel door burst into a thousand fragments under one crushing blow. Through smoke and sparks, Max stepped into the complex in exo-armor.',fr:'La lourde porte d’acier du bunker vola en éclats sous un coup colossal. À travers la fumée et les étincelles, Max entra dans le complexe en exo-armure.'},s:{ru:'Ваша система безопасности — полный отстой!',kk:'Сіздердің қауіпсіздік жүйелеріңіз түкке тұрғысыз!',en:'Your security system is a joke!',fr:'Votre système de sécurité est une vraie plaisanterie !'}},
 {title:{ru:'Перехват управления',kk:'Басқаруды қолға алу',en:'System Override',fr:'Prise de contrôle'},n:{ru:'Один точный удар бронированного кулака в центр главного узла разнёс консоль в дребезги. Зелёные каскады данных охватили систему, уничтожая барьеры.',kk:'Брондалған жұдырықтың негізгі торапқа дәл соққысы консольді талқандады. Жасыл деректер тасқыны жүйені шарпып, кедергілерді жойды.',en:'One precise strike from an armored fist smashed the main console. Green cascades of data swept through the system, tearing down every barrier.',fr:'Un coup précis du poing blindé pulvérisa la console centrale. Des cascades de données vertes envahirent le système et détruisirent les barrières.'},s:{ru:'Щит отключен! Уходим вместе!',kk:'Қалқан өшірілді! Бірге кетеміз!',en:'Shield deactivated! Let’s move out together!',fr:'Bouclier désactivé ! On décroche ensemble !'}},
 {title:{ru:'Спина к спине',kk:'Арқа тіресе',en:'Back to Back',fr:'Dos à dos'},n:{ru:'Алекс с лёту перехватила бластер и встала плечом к плечу с Максом. Лаборатория заполнилась сиренами, но игра шла по их правилам.',kk:'Алекс бластерді қағып алып, Макспен иық тірестіре тұрды. Зертхананы дабыл үні басты, бірақ енді ойын олардың ережесімен жүрді.',en:'Alex caught the blaster on the move and stood shoulder to shoulder with Max. Sirens filled the lab, but now the game was being played by their rules.',fr:'Alex attrapa le blaster au vol et se plaça aux côtés de Max. Les sirènes envahirent le laboratoire, mais désormais la partie se jouait selon leurs règles.'},s:{ru:'Ты опоздал на 3 минуты! — Зато вышел красиво!',kk:'3 минутқа кешіктің! — Есесіне әдемі кірдім!',en:'You’re 3 minutes late! — But I made one hell of an entrance!',fr:'Tu as 3 minutes de retard ! — Mais quelle entrée en scène !'}},
 {title:{ru:'Финальный побег',kk:'Соңғы қашу',en:'Final Escape',fr:'Évasion finale'},n:{ru:'Тяжёлый истребитель резал ночные облака, уходя вверх к ослепительной полной луне. За спиной героев цитадель Синдиката затянулась огненным цветком взрыва.',kk:'Ауыр жойғыш ұшақ түнгі бұлттарды жарып, жарқыраған толық айға қарай көтерілді. Артта Синдикат қамалы жарылыстың отты гүліне оранды.',en:'The heavy fighter sliced through the night clouds toward a dazzling full moon. Behind the heroes, the Syndicate citadel vanished inside a fiery bloom.',fr:'Le chasseur fendit les nuages nocturnes vers une pleine lune aveuglante. Derrière les héros, la citadelle du Syndicat disparut dans une fleur de feu.'},s:{ru:'Миссия завершена. Город в безопасности!',kk:'Миссия аяқталды. Қала қауіпсіз жерде!',en:'Mission accomplished. The city is safe!',fr:'Mission accomplie. La ville est hors de danger !'}}
];
const app=document.querySelector('#app'),viewer=document.querySelector('#viewer'),viewerContent=document.querySelector('#viewerContent');
function render(){const c=COPY[lang];document.documentElement.lang=lang;app.innerHTML=`<main class="shell"><header class="top"><a class="brand" href="../">Port<b>Hub</b></a><select class="lang" id="lang" aria-label="Language">${LANGS.map(x=>`<option value="${x}"${x===lang?' selected':''}>${x.toUpperCase()}</option>`).join('')}</select></header><section class="hero"><div class="eyebrow">${c.eyebrow}</div><h1>${c.title}</h1><p>${c.lead}</p></section><section class="story">${PANELS.map((p,i)=>`<article class="frame"><button class="art" type="button" data-panel="${i}" aria-label="${p.title[lang]}"><img src="night-noir/frame-${String(i+1).padStart(2,'0')}.webp" alt="${p.title[lang]}" loading="${i>1?'lazy':'eager'}"><span class="bubble">${p.s[lang]}</span></button><div class="copy"><div class="chapter"><i>${i+1}</i>${c.frame}</div><h2>${p.title[lang]}</h2><p>${p.n[lang]}</p></div></article>`).join('')}</section><div class="share-wrap"><button class="share" id="share" type="button">↗ ${c.share}</button></div></main>`;document.querySelector('#lang').onchange=e=>{lang=e.target.value;try{localStorage.setItem('pt.lang',lang)}catch{}render()};document.querySelectorAll('[data-panel]').forEach(x=>x.onclick=()=>openPanel(Number(x.dataset.panel)));document.querySelector('#share').onclick=share}
function openPanel(i){const p=PANELS[i],c=COPY[lang];viewerContent.innerHTML=`<img src="night-noir/frame-${String(i+1).padStart(2,'0')}.webp" alt="${p.title[lang]}"><div class="viewer-copy"><h2>${c.frame} ${i+1}: ${p.title[lang]}</h2><p>${p.n[lang]}</p><blockquote>${p.s[lang]}</blockquote></div>`;viewer.showModal()}
document.querySelector('.viewer-close').onclick=()=>viewer.close();viewer.onclick=e=>{if(e.target===viewer)viewer.close()};
async function share(){const c=COPY[lang],url=globalThis.PT_CONFIG?.onlineUrl('comics/')||new URL('./',location.href).href;try{if(navigator.share)await navigator.share({title:document.title,text:c.shareText,url});else{await navigator.clipboard.writeText(`${c.shareText} ${url}`);toast(c.copied)}}catch(e){if(e?.name!=='AbortError')toast(c.copied)}}
function toast(text){const node=document.querySelector('#toast');node.textContent=text;node.classList.add('show');setTimeout(()=>node.classList.remove('show'),1800)}
render();
