const LANGS=['ru','kk','en','fr'];
const savedLang=(()=>{try{return localStorage.getItem('pt.lang')}catch{return null}})();
let lang=LANGS.includes(savedLang)?savedLang:(LANGS.includes((navigator.language||'ru').slice(0,2))?(navigator.language||'ru').slice(0,2):'ru');
const COPY={
 ru:{home:'На главную',eyebrow:'МИНИ-КОМИКС · ВЫПУСК 01',title:'Операция<br><em>«Ночной нуар»</em>',lead:'Шесть кадров. Два героя. Одна очень плохая ночь для Синдиката.',frame:'Кадр',share:'Поделиться комиксом',copied:'Ссылка на комикс скопирована',shareText:'Операция «Ночной нуар» — мини-комикс в шести кадрах.'},
 kk:{home:'Басты бетке',eyebrow:'МИНИ-КОМИКС · 01 ШЫҒАРЫЛЫМ',title:'Операция<br><em>«Түнгі нуар»</em>',lead:'Алты кадр. Екі қаһарман. Синдикат үшін өте сәтсіз түн.',frame:'Кадр',share:'Комикспен бөлісу',copied:'Комикс сілтемесі көшірілді',shareText:'«Түнгі нуар» операциясы — алты кадрлық мини-комикс.'},
 en:{home:'Home',eyebrow:'MINI COMIC · ISSUE 01',title:'Operation<br><em>“Night Noir”</em>',lead:'Six panels. Two heroes. One very bad night for the Syndicate.',frame:'Panel',share:'Share this comic',copied:'Comic link copied',shareText:'Operation “Night Noir” — a six-panel mini comic.'},
 fr:{home:'Accueil',eyebrow:'MINI-BD · ÉPISODE 01',title:'Opération<br><em>«Noir nocturne»</em>',lead:'Six cases. Deux héros. Une très mauvaise nuit pour le Syndicat.',frame:'Case',share:'Partager la BD',copied:'Lien de la BD copié',shareText:'Opération «Noir nocturne» — une mini-BD en six cases.'}
};
const NIGHT_PANELS=[
 {title:{ru:'Засада в неоне',kk:'Неондағы тұзақ',en:'Neon Ambush',fr:'Embuscade au néon'},n:{ru:'Тяжёлые капли дождя разбивались об асфальт неоновой крыши. Алекс замерла в полуприседе, когда из ночного тумана вынырнули бесшумные тени. Красные объективы боевых дронов захватили её в перекрестье прицелов.',kk:'Жаңбырдың ауыр тамшылары неонды шатырдың асфальтына соғылды. Алекс жартылай отыра қатып қалды: түнгі тұманнан үнсіз көлеңкелер шықты. Жауынгерлік дрондардың қызыл объективтері оны нысанаға алды.',en:'Heavy rain shattered across the neon rooftop. Alex froze in a crouch as silent shadows slipped out of the night fog. The red lenses of combat drones locked her in their sights.',fr:'La pluie martelait le toit baigné de néons. Alex se figea, accroupie, tandis que des ombres silencieuses surgissaient du brouillard. Les objectifs rouges des drones de combat la prirent pour cible.'},s:{ru:'Датчики молчат… Это засада Синдиката!',kk:'Датчиктер үнсіз… Бұл Синдикаттың тұзағы!',en:'Sensors are silent… It’s a Syndicate ambush!',fr:'Les capteurs sont muets… C’est une embuscade du Syndicat !'}},
 {title:{ru:'Энерго-западня',kk:'Энергиялық қақпан',en:'Energy Trap',fr:'Piège énergétique'},n:{ru:'Поднявшийся из пола силовой купол вспыхнул ослепительно синим светом. Энергетическая решётка мгновенно заблокировала микросхемы её костюма.',kk:'Еденнен көтерілген күш күмбезі көз қаратпайтын көк жарықпен жанды. Энергия торы оның костюмінің микросхемаларын бірден бұғаттады.',en:'A force dome rose from the floor in a blinding blue flash. The energy grid instantly jammed every circuit in her suit.',fr:'Un dôme de force jaillit du sol dans un éclair bleu aveuglant. La grille d’énergie bloqua aussitôt les circuits de sa combinaison.'},s:{ru:'Энергощит заблокировал костюм… Но Макс близко!',kk:'Энергия қалқаны костюмді бұғаттады… Бірақ Макс жақын!',en:'Energy shield jammed my suit… But Max is near!',fr:'Le bouclier bloque ma combinaison… Mais Max est proche !'}},
 {title:{ru:'Взрывной прорыв',kk:'Жарылыспен кіру',en:'Explosive Entry',fr:'Entrée explosive'},n:{ru:'Тяжёлая стальная дверь бункера разлетелась на тысячи осколков от мощнейшего удара. Сквозь дым и сноп искр вглубь комплекса шагнул Макс в экзо-броне.',kk:'Қуатты соққыдан бункердің ауыр болат есігі мыңдаған бөлшекке ұшты. Түтін мен ұшқын арасынан экзо-сауыт киген Макс кешенге кірді.',en:'The bunker’s steel door burst into a thousand fragments under one crushing blow. Through smoke and sparks, Max stepped into the complex in exo-armor.',fr:'La lourde porte d’acier du bunker vola en éclats sous un coup colossal. À travers la fumée et les étincelles, Max entra dans le complexe en exo-armure.'},s:{ru:'Ваша система безопасности — полный отстой!',kk:'Сіздердің қауіпсіздік жүйелеріңіз түкке тұрғысыз!',en:'Your security system is a joke!',fr:'Votre système de sécurité est une vraie plaisanterie !'}},
 {title:{ru:'Перехват управления',kk:'Басқаруды қолға алу',en:'System Override',fr:'Prise de contrôle'},n:{ru:'Один точный удар бронированного кулака в центр главного узла разнёс консоль в дребезги. Зелёные каскады данных охватили систему, уничтожая барьеры.',kk:'Брондалған жұдырықтың негізгі торапқа дәл соққысы консольді талқандады. Жасыл деректер тасқыны жүйені шарпып, кедергілерді жойды.',en:'One precise strike from an armored fist smashed the main console. Green cascades of data swept through the system, tearing down every barrier.',fr:'Un coup précis du poing blindé pulvérisa la console centrale. Des cascades de données vertes envahirent le système et détruisirent les barrières.'},s:{ru:'Щит отключен! Уходим вместе!',kk:'Қалқан өшірілді! Бірге кетеміз!',en:'Shield deactivated! Let’s move out together!',fr:'Bouclier désactivé ! On décroche ensemble !'}},
 {title:{ru:'Спина к спине',kk:'Арқа тіресе',en:'Back to Back',fr:'Dos à dos'},n:{ru:'Алекс с лёту перехватила бластер и встала плечом к плечу с Максом. Лаборатория заполнилась сиренами, но игра шла по их правилам.',kk:'Алекс бластерді қағып алып, Макспен иық тірестіре тұрды. Зертхананы дабыл үні басты, бірақ енді ойын олардың ережесімен жүрді.',en:'Alex caught the blaster on the move and stood shoulder to shoulder with Max. Sirens filled the lab, but now the game was being played by their rules.',fr:'Alex attrapa le blaster au vol et se plaça aux côtés de Max. Les sirènes envahirent le laboratoire, mais désormais la partie se jouait selon leurs règles.'},s:{ru:'Ты опоздал на 3 минуты! — Зато вышел красиво!',kk:'3 минутқа кешіктің! — Есесіне әдемі кірдім!',en:'You’re 3 minutes late! — But I made one hell of an entrance!',fr:'Tu as 3 minutes de retard ! — Mais quelle entrée en scène !'}},
 {title:{ru:'Финальный побег',kk:'Соңғы қашу',en:'Final Escape',fr:'Évasion finale'},n:{ru:'Тяжёлый истребитель резал ночные облака, уходя вверх к ослепительной полной луне. За спиной героев цитадель Синдиката затянулась огненным цветком взрыва.',kk:'Ауыр жойғыш ұшақ түнгі бұлттарды жарып, жарқыраған толық айға қарай көтерілді. Артта Синдикат қамалы жарылыстың отты гүліне оранды.',en:'The heavy fighter sliced through the night clouds toward a dazzling full moon. Behind the heroes, the Syndicate citadel vanished inside a fiery bloom.',fr:'Le chasseur fendit les nuages nocturnes vers une pleine lune aveuglante. Derrière les héros, la citadelle du Syndicat disparut dans une fleur de feu.'},s:{ru:'Миссия завершена. Город в безопасности!',kk:'Миссия аяқталды. Қала қауіпсіз жерде!',en:'Mission accomplished. The city is safe!',fr:'Mission accomplie. La ville est hors de danger !'}}
];
const ECLIPSE_PANELS=[
 {title:{ru:'Сигнал бедствия',kk:'Дабыл сигналы',en:'Distress Signal',fr:'Signal de détresse'},n:{ru:'Сигнал тревоги перехватил радиоэфир через секунды после побега. Синдикат активировал систему «Затмение», способную обесточить весь мегаполис.',kk:'Дабыл сигналы қашып шыққаннан кейін бірнеше секундтан соң радиоэфирді басып алды. Синдикат бүкіл мегаполисті тоқсыз қалдыруға қабілетті «Тұтылу» жүйесін іске қосты.',en:'A distress signal cut into the radio frequency seconds after their escape. The Syndicate had activated Eclipse, a system capable of blacking out the entire megacity.',fr:'Un signal de détresse interrompit la radio quelques secondes après leur fuite. Le Syndicat avait activé « Éclipse », un système capable de plonger toute la mégapole dans le noir.'},s:{ru:'У нас 10 минут до полного отключения города!',kk:'Қала толық өшкенше бізде 10 минут бар!',en:'We have 10 minutes before total city blackout!',fr:'Nous avons 10 minutes avant la panne totale !'}},
 {title:{ru:'Скрытый вход',kk:'Жасырын кіреберіс',en:'Hidden Entrance',fr:'Entrée secrète'},n:{ru:'Главный вход был заблокирован. Алекс быстро вскрыла вентиляционный люк на крыше штаба плазменным резаком.',kk:'Басты кіреберіс бұғатталған. Алекс плазмалық кескішпен бас штабтың шатырындағы желдету люгін жылдам ашып алды.',en:'The main entrance was sealed. Alex quickly cut through a rooftop ventilation hatch at headquarters with a plasma torch.',fr:'L’entrée principale était condamnée. Alex découpa rapidement une trappe de ventilation sur le toit du quartier général.'},s:{ru:'Быстрей! Плазма почти перегрелась!',kk:'Тездет! Плазма қызып кетті!',en:'Hurry! The plasma torch is overheating!',fr:'Fais vite ! Le découpeur plasma surchauffe !'}},
 {title:{ru:'Падение в шахту',kk:'Шахтаға құлау',en:'Into the Shaft',fr:'Chute dans la cage'},n:{ru:'Свободное падение в шахту лифта было единственным быстрым способом добраться до нижних уровней комплекса.',kk:'Лифт шахтасына секіру жер астының төменгі деңгейлеріне түсудің жалғыз жылдам жолы еді.',en:'Free-falling down the elevator shaft was the only fast way to reach the underground levels.',fr:'Sauter dans la cage d’ascenseur était le seul moyen rapide d’atteindre les niveaux inférieurs.'},s:{ru:'Держись за магнитный трос!',kk:'Магнитті арқаннан ұстай бер!',en:'Hold onto the magnetic cable!',fr:'Accroche-toi au câble magnétique !'}},
 {title:{ru:'Главный сервер «Затмение»',kk:'«Тұтылу» бас сервері',en:'The Eclipse Core',fr:'Le cœur d’Éclipse'},n:{ru:'Серверное ядро «Затмения» гудело от колоссальной энергии. В центре зала пульсировал квантовый ИИ Синдиката.',kk:'«Тұтылу» ядросының сервері орасан зор энергиядан уілдеп тұрды. Залдың ортасында Синдикаттың кванттық жасанды интеллекті пульсацияланып жатты.',en:'The Eclipse core server room hummed with power. The Syndicate’s quantum AI pulsated at the center of the hall.',fr:'La salle du noyau « Éclipse » vibrait d’une énergie colossale. L’IA quantique du Syndicat pulsait en son centre.'},s:{ru:'Вот оно, ядро управления…',kk:'Міне, басқару ядросы…',en:'There it is, the control core…',fr:'Le voilà, le noyau de commande…'}},
 {title:{ru:'Защитник Синдиката',kk:'Синдикат қорғаушысы',en:'Syndicate Enforcer',fr:'Le gardien du Syndicat'},n:{ru:'Из тени вышла тяжёлая боевая единица Синдиката — киборг-ликвидатор с двумя плазмомётами.',kk:'Көлеңкеден Синдикаттың ауыр жауынгерлік бірлігі — екі плазмаатарлы киборг-жойғыш шыға келді.',en:'A heavy Syndicate enforcer emerged from the shadows — an executioner cyborg with dual plasma cannons.',fr:'Une lourde unité de combat du Syndicat surgit de l’ombre : un cyborg exécuteur armé de deux canons à plasma.'},s:{ru:'Макс, отвлеки его! Я загружу вирус!',kk:'Макс, оның назарын аудар! Мен вирусты жүктеймін!',en:'Max, distract him! I’ll upload the virus!',fr:'Max, détourne son attention ! Je charge le virus !'}},
 {title:{ru:'Перехват управления',kk:'Басқаруды басып алу',en:'System Override',fr:'Prise de contrôle'},n:{ru:'Пока Макс сдерживал огонь щитом, Алекс успела вставить чип с вирусом. Экран ядра залило красным сообщением об ошибке.',kk:'Макс соққыны қалқанмен бөгеп тұрғанда, Алекс вирус чипін салып үлгерді. Ядро экраны қызыл қателікке толды.',en:'While Max held the line with his shield, Alex plugged in the virus drive. The core screen flared with a red critical error.',fr:'Pendant que Max encaissait les tirs avec son bouclier, Alex inséra la puce infectée. L’écran du noyau se couvrit d’une erreur critique rouge.'},s:{ru:'Перехват завершён! Но кто отдавал приказы?!',kk:'Басқару алынды! Бірақ бұйрықты кім берген?!',en:'Override complete! But who was giving the orders?!',fr:'Prise de contrôle réussie ! Mais qui donnait les ordres ?!'}}
];
const ANATOMY_PANELS=[
 {title:{ru:'Бессонная ночь',kk:'Ұйқысыз түн',en:'Sleepless Night',fr:'Nuit blanche'},n:{ru:'Подготовка к экзамену по анатомии затянулась до утра. Айри уснула прямо поверх открытого атласа.',kk:'Анатомия емтиханына дайындық таңға дейін созылды. Айри ашық атластың үстіне ұйықтап кетті.',en:'Studying for the anatomy exam went on until morning. Airi fell asleep right on top of her open textbook.',fr:'Les révisions pour l’examen d’anatomie se prolongèrent jusqu’au matin. Airi s’endormit sur son livre ouvert.'},s:{ru:'Ещё одна страница… и я точно всё запомню…',kk:'Тағы бір бет… сосын бәрін анық есте сақтаймын…',en:'Just one more page… and I’ll definitely remember it all…',fr:'Encore une page… et je me souviendrai de tout…'}},
 {title:{ru:'Забота старшекурсника',kk:'Жоғары курс студентінің қамқорлығы',en:'A Senior’s Kindness',fr:'L’attention d’un aîné'},n:{ru:'Рен тихо проходил мимо рядов библиотеки. Увидев уставшую Айри, он аккуратно поставил рядом стакан горячего кофе.',kk:'Рен кітапхана қатарларының жанынан ақырын өтіп бара жатты. Шаршаған Айриді көріп, ол жанына ыстық кофе қойды.',en:'Ren quietly walked past the library aisles. Seeing exhausted Airi, he gently placed a warm cup of coffee beside her.',fr:'Ren traversait silencieusement la bibliothèque. Voyant Airi épuisée, il posa doucement un café chaud à côté d’elle.'},s:{ru:'Ты отлично поработала. Отдохни немного!',kk:'Жақсы жұмыс істедің. Сәл демалып ал!',en:'You did a great job. Rest a little!',fr:'Tu as bien travaillé. Repose-toi un peu !'}},
 {title:{ru:'Внезапное утро',kk:'Күтпеген таң',en:'A Surprising Morning',fr:'Un réveil inattendu'},n:{ru:'Проснувшись от аромата свежего латте, Айри обнаружила записку с пожеланием удачи на экзамене.',kk:'Жаңа демделген латте хош иісінен оянған Айри емтиханда сәттілік тілеген жазбаны тапты.',en:'Waking up to the aroma of fresh latte, Airi found a small note wishing her good luck on the exam.',fr:'Réveillée par l’arôme du café, Airi trouva un petit mot lui souhaitant bonne chance pour l’examen.'},s:{ru:'Это же почерк Рена… Сердце бьётся быстрее нормы!',kk:'Бұл Реннің қолжазбасы ғой… Жүрегім жиі соғып кетті!',en:'It’s Ren’s handwriting… My heart rate is above normal!',fr:'C’est l’écriture de Ren… Mon cœur bat plus vite que la normale !'}},
 {title:{ru:'Отлично за экзамен',kk:'Емтиханнан үздік баға',en:'Top Marks',fr:'Examen réussi'},n:{ru:'Зачётная книжка запестрела высшими баллами. Сложнейший экзамен семестра остался позади.',kk:'Сынақ кітапшасы жоғары баллдарға толды. Семестрдің ең қиын емтиханы артта қалды.',en:'Her grade book was filled with top marks. The hardest exam of the semester was officially over.',fr:'Son relevé affichait les meilleures notes. L’examen le plus difficile du semestre était enfin derrière elle.'},s:{ru:'Сдала! Я сделала это!',kk:'Тапсырдым! Мен мұны істедім!',en:'Passed! I actually did it!',fr:'Réussi ! Je l’ai fait !'}},
 {title:{ru:'Разбор конспекта',kk:'Конспектіні талдау',en:'Reviewing Notes',fr:'Révision des notes'},n:{ru:'После занятий Рен помогал Айри разбирать сложные клинические случаи в пустой аудитории.',kk:'Сабақтан кейін Рен бос аудиторияда Айриге күрделі клиникалық жағдайларды талдауға көмектесті.',en:'After classes, Ren helped Airi review complex clinical cases in an empty lecture hall.',fr:'Après les cours, Ren aida Airi à réviser des cas cliniques complexes dans une salle vide.'},s:{ru:'Смотри, здесь главное — не волноваться и верить в себя.',kk:'Қарашы, мұндағы ең бастысы — толқымау және өзіңе сену.',en:'Look, the key here is not to worry and to believe in yourself.',fr:'Regarde, l’essentiel est de ne pas stresser et de croire en toi.'}},
 {title:{ru:'Закат на крыше',kk:'Шатырдағы күн батуы',en:'Rooftop Sunset',fr:'Coucher de soleil'},n:{ru:'Вечернее солнце окрасило крышу университета в золотистые тона. Простая беседа казалась важнее любых лекций.',kk:'Кешкі күн университет шатырын алтын түске бөледі. Қарапайым әңгіме кез келген дәрістен маңыздырақ болып көрінді.',en:'The evening sun bathed the university rooftop in golden light. A simple conversation felt more important than any lecture.',fr:'Le soleil couchant baignait le toit de l’université d’une lumière dorée. Une simple conversation semblait plus importante que tous les cours.'},s:{ru:'Спасибо за кофе… и за то, что ты рядом!',kk:'Кофе үшін… және қасымда болғаның үшін рақмет!',en:'Thanks for the coffee… and for being by my side!',fr:'Merci pour le café… et d’être à mes côtés !'}}
];
const ISSUES={
 'night-noir':{folder:'night-noir',panels:NIGHT_PANELS,meta:{ru:['МИНИ-КОМИКС · ВЫПУСК 01','Операция<br><em>«Ночной нуар»</em>','Шесть кадров. Два героя. Одна очень плохая ночь для Синдиката.'],kk:['МИНИ-КОМИКС · 01 ШЫҒАРЫЛЫМ','Операция<br><em>«Түнгі нуар»</em>','Алты кадр. Екі қаһарман. Синдикат үшін өте сәтсіз түн.'],en:['MINI COMIC · ISSUE 01','Operation<br><em>“Night Noir”</em>','Six panels. Two heroes. One very bad night for the Syndicate.'],fr:['MINI-BD · ÉPISODE 01','Opération<br><em>«Noir nocturne»</em>','Six cases. Deux héros. Une très mauvaise nuit pour le Syndicat.']}},
 'eclipse-protocol':{folder:'eclipse-protocol',panels:ECLIPSE_PANELS,meta:{ru:['МИНИ-КОМИКС · ВЫПУСК 02','Операция<br><em>«Протокол Затмение»</em>','Город погаснет через десять минут. Алекс и Макс возвращаются в самое сердце Синдиката.'],kk:['МИНИ-КОМИКС · 02 ШЫҒАРЫЛЫМ','Операция<br><em>«Тұтылу хаттамасы»</em>','Қала он минуттан кейін сөнеді. Алекс пен Макс Синдикаттың жүрегіне оралады.'],en:['MINI COMIC · ISSUE 02','Operation<br><em>“Eclipse Protocol”</em>','The city goes dark in ten minutes. Alex and Max return to the heart of the Syndicate.'],fr:['MINI-BD · ÉPISODE 02','Opération<br><em>«Protocole Éclipse»</em>','La ville s’éteindra dans dix minutes. Alex et Max retournent au cœur du Syndicat.']}},
 'anatomy-of-feelings':{folder:'anatomy-of-feelings',panels:ANATOMY_PANELS,meta:{ru:['МИНИ-КОМИКС · ВЫПУСК 03','<em>«Анатомия чувств»</em>','Тёплая история о бессонной сессии, кофе и чувствах между будущими врачами.'],kk:['МИНИ-КОМИКС · 03 ШЫҒАРЫЛЫМ','<em>«Сезімдер анатомиясы»</em>','Ұйқысыз сессия, кофе және болашақ дәрігерлер арасындағы сезімдер туралы жылы оқиға.'],en:['MINI COMIC · ISSUE 03','<em>“Anatomy of Feelings”</em>','A warm story about sleepless exams, coffee, and feelings between two future doctors.'],fr:['MINI-BD · ÉPISODE 03','<em>«Anatomie des sentiments»</em>','Une histoire chaleureuse d’examens, de café et de sentiments entre deux futurs médecins.']}}
};
const requestedIssue=new URLSearchParams(location.search).get('issue');
const issueId=ISSUES[requestedIssue]?requestedIssue:'night-noir';
const issue=ISSUES[issueId];
const app=document.querySelector('#app'),viewer=document.querySelector('#viewer'),viewerContent=document.querySelector('#viewerContent');
function render(){const c=COPY[lang],m=issue.meta[lang],catalogTitle=lang==='ru'?'Мини-комиксы':lang==='kk'?'Мини-комикстер':lang==='fr'?'Mini-BD':'Mini Comics',choose=lang==='ru'?'Выберите выпуск':lang==='kk'?'Шығарылымды таңдаңыз':lang==='fr'?'Choisissez un épisode':'Choose an issue',read=lang==='ru'?'Читать':lang==='kk'?'Оқу':lang==='fr'?'Lire':'Read';document.documentElement.lang=lang;document.title=`${m[1].replace(/<[^>]+>/g,'')} — PortHub`;app.innerHTML=`<main class="shell"><header class="top"><a class="brand" href="../">Port<b>Hub</b></a><select class="lang" id="lang" aria-label="Language">${LANGS.map(x=>`<option value="${x}"${x===lang?' selected':''}>${x.toUpperCase()}</option>`).join('')}</select></header><section class="catalog-head"><div class="eyebrow">PORTHUB STORIES</div><h1>${catalogTitle}</h1><p>${choose}</p></section><nav class="issue-picker" aria-label="${choose}">${Object.entries(ISSUES).map(([id,item],i)=>`<a href="${id==='night-noir'?'./':`?issue=${id}`}" class="${id===issueId?'active':''}"><img src="${item.folder}/frame-01.webp" alt="" loading="${i?'lazy':'eager'}"><span><b>${String(i+1).padStart(2,'0')}</b><strong>${item.meta[lang][1].replace(/<[^>]+>/g,'')}</strong><small>${read} →</small></span></a>`).join('')}</nav><section class="hero"><div class="eyebrow">${m[0]}</div><h1>${m[1]}</h1><p>${m[2]}</p></section><section class="story">${issue.panels.map((p,i)=>`<article class="frame"><button class="art" type="button" data-issue="${issueId}" data-panel="${i}" aria-label="${p.title[lang]}"><img src="${issue.folder}/frame-${String(i+1).padStart(2,'0')}.webp" alt="${p.title[lang]}" loading="${i>1?'lazy':'eager'}"><span class="bubble">${p.s[lang]}</span></button><div class="copy"><div class="chapter"><i>${i+1}</i>${c.frame}</div><h2>${p.title[lang]}</h2><p>${p.n[lang]}</p></div></article>`).join('')}</section><div class="share-wrap"><button class="share" id="share" type="button">↗ ${c.share}</button></div></main>`;document.querySelector('#lang').onchange=e=>{lang=e.target.value;try{localStorage.setItem('pt.lang',lang)}catch{}render()};document.querySelectorAll('[data-panel]').forEach(x=>x.onclick=()=>openPanel(Number(x.dataset.panel)));document.querySelector('#share').onclick=share}
function openPanel(i){const p=issue.panels[i],c=COPY[lang];viewerContent.innerHTML=`<img src="${issue.folder}/frame-${String(i+1).padStart(2,'0')}.webp" alt="${p.title[lang]}"><div class="viewer-copy"><h2>${c.frame} ${i+1}: ${p.title[lang]}</h2><p>${p.n[lang]}</p><blockquote>${p.s[lang]}</blockquote></div>`;viewer.showModal()}
document.querySelector('.viewer-close').onclick=()=>viewer.close();viewer.onclick=e=>{if(e.target===viewer)viewer.close()};
async function share(){const c=COPY[lang],url=new URL(globalThis.PT_CONFIG?.onlineUrl('comics/')||new URL('./',location.href).href);if(issueId!=='night-noir')url.searchParams.set('issue',issueId);const text=`${issue.meta[lang][1].replace(/<[^>]+>/g,'')} — ${lang==='ru'?'мини-комикс в шести кадрах':lang==='kk'?'алты кадрлық мини-комикс':lang==='fr'?'une mini-BD en six cases':'a six-panel mini comic'}.`;try{if(navigator.share)await navigator.share({title:document.title,text,url:url.href});else{await navigator.clipboard.writeText(`${text} ${url.href}`);toast(c.copied)}}catch(e){if(e?.name!=='AbortError')toast(c.copied)}}
function toast(text){const node=document.querySelector('#toast');node.textContent=text;node.classList.add('show');setTimeout(()=>node.classList.remove('show'),1800)}
render();
