(()=>{'use strict';
const LANGS=['ru','kk','en','fr'],requestedLang=(new URLSearchParams(location.search).get('lang')||'').slice(0,2).toLowerCase(),browserLang=(navigator.language||'ru').slice(0,2).toLowerCase();let lang=LANGS.includes(requestedLang)?requestedLang:(localStorage.getItem('pt.lang')||browserLang);if(!LANGS.includes(lang))lang='ru';try{localStorage.setItem('pt.lang',lang)}catch{}
const UI={
ru:{home:'На главную',tag:'CULTURE‑FAIR · ПОДВИЖНЫЙ ИНТЕЛЛЕКТ',title:'Не знания.<br><em>Способ мышления.</em>',lead:'Здесь не спрашивают даты, слова и школьные факты. 12 визуальных матриц проверяют, как быстро вы находите правило в незнакомой системе.',why:[['Без зубрёжки','Результат почти не зависит от эрудиции.'],['Без языкового барьера','В заданиях только формы, позиции и изменения.'],['Чистая логика','Вращения, прогрессии, наложение OR и исключение XOR.']],note:'12 минут на весь тест. Одна правильная фигура в каждой матрице. Результат — ориентировочная оценка матричного рассуждения, а не клинический диагноз и не официальный тест Равена или Mensa.',start:'Начать 12‑минутный тест',task:'Матрица',of:'из',left:'Осталось',ask:'Какая фигура должна быть вместо знака вопроса?',next:'Далее',finish:'Завершить',choose:'Сначала выберите ответ',result:'Ваш результат',raw:'правильных',time:'время',estimate:'ориентир IQ',again:'Пройти ещё раз',share:'Поделиться',other:'Другие тесты',copied:'Ссылка скопирована',timeout:'Время вышло',bands:[['Нужно разогреться','Базовые правила пока ускользали. Это навык: повторное прохождение обычно заметно улучшает поиск закономерностей.'],['Рабочая логика','Простые правила вы ловите уверенно, а многослойные требуют больше времени.'],['Сильное матричное мышление','Вы хорошо удерживаете несколько визуальных правил и быстро отбрасываете шум.'],['Очень сильный результат','Сложные преобразования, циклы и наложения вы распознаёте заметно выше среднего.']],shareText:'Мой результат Matrix IQ: {score}/12, ориентир {iq}. Проверь своё матричное мышление:'},
en:{home:'Home',tag:'CULTURE‑FAIR · FLUID REASONING',title:'Not knowledge.<br><em>How you think.</em>',lead:'No dates, vocabulary or school facts. Twelve visual matrices test how quickly you discover rules inside unfamiliar systems.',why:[['No memorization','The score barely depends on general knowledge.'],['Low language load','Tasks use shapes, positions and transformations.'],['Pure patterns','Rotation, progression, OR overlays and XOR cancellation.']],note:'You have 12 minutes. Each matrix has one answer. The result is an informal estimate of matrix reasoning—not a clinical diagnosis or an official Raven/Mensa score.',start:'Start the 12-minute test',task:'Matrix',of:'of',left:'Time left',ask:'Which figure replaces the question mark?',next:'Next',finish:'Finish',choose:'Choose an answer first',result:'Your result',raw:'correct',time:'time',estimate:'IQ estimate',again:'Try again',share:'Share',other:'Other tests',copied:'Link copied',timeout:'Time is up',bands:[['Warm-up needed','The basic rules escaped this time. Pattern finding is trainable, and a second run often improves.'],['Working logic','You catch simple rules reliably; layered ones need more time.'],['Strong matrix reasoning','You hold several visual rules at once and discard noise efficiently.'],['Very strong result','You detect complex transformations, cycles and overlays well above average.']],shareText:'My Matrix IQ result: {score}/12, estimate {iq}. Test your matrix reasoning:'},
kk:{home:'Басты бет',tag:'CULTURE‑FAIR · ИКЕМДІ ОЙЛАУ',title:'Білім емес.<br><em>Ойлау тәсілі.</em>',lead:'Мұнда даталар мен мектеп фактілері жоқ. 12 көрнекі матрица бейтаныс жүйеден заңдылық табуды тексереді.',why:[['Жаттаусыз','Нәтиже білім қорына аз тәуелді.'],['Тілдік кедергі аз','Тек пішін, орын және өзгеріс.'],['Таза логика','Айналу, прогрессия, OR және XOR.']],note:'Барлық тестке 12 минут. Әр матрицада бір дұрыс жауап. Нәтиже — матрицалық ойлаудың бағдарлық бағасы, ресми Raven немесе Mensa ұпайы емес.',start:'12 минуттық тестті бастау',task:'Матрица',of:'/',left:'Қалды',ask:'Сұрақ белгісінің орнына қай пішін келеді?',next:'Келесі',finish:'Аяқтау',choose:'Алдымен жауап таңдаңыз',result:'Нәтижеңіз',raw:'дұрыс',time:'уақыт',estimate:'IQ бағдары',again:'Қайта өту',share:'Бөлісу',other:'Басқа тесттер',copied:'Сілтеме көшірілді',timeout:'Уақыт бітті',bands:[['Қыздыру керек','Негізгі ережелер бұл жолы байқалмады. Заңдылық іздеу — жаттықтырылатын дағды.'],['Жұмыс логикасы','Қарапайым ережелерді сенімді табасыз, күрделілеріне уақыт керек.'],['Күшті матрицалық ойлау','Бірнеше көрнекі ережені қатар ұстап, артық ақпаратты жақсы сүзесіз.'],['Өте күшті нәтиже','Күрделі өзгерістер, циклдер мен қабаттасуды ортадан жоғары табасыз.']],shareText:'Matrix IQ нәтижем: {score}/12, бағдар {iq}. Өзіңді тексер:'},
fr:{home:'Accueil',tag:'CULTURE‑FAIR · RAISONNEMENT FLUIDE',title:'Pas le savoir.<br><em>Votre façon de penser.</em>',lead:'Ni dates, ni vocabulaire scolaire. Douze matrices visuelles testent votre capacité à découvrir une règle inconnue.',why:[['Sans bachotage','Le résultat dépend peu de la culture générale.'],['Peu de langage','Seulement formes, positions et transformations.'],['Logique pure','Rotations, progressions, OR et XOR.']],note:'Douze minutes au total. Une seule réponse par matrice. Le résultat est une estimation indicative du raisonnement matriciel, pas un diagnostic ni un score officiel Raven/Mensa.',start:'Commencer le test de 12 minutes',task:'Matrice',of:'sur',left:'Temps restant',ask:'Quelle figure remplace le point d’interrogation ?',next:'Suivant',finish:'Terminer',choose:'Choisissez d’abord une réponse',result:'Votre résultat',raw:'correctes',time:'temps',estimate:'estimation QI',again:'Recommencer',share:'Partager',other:'Autres tests',copied:'Lien copié',timeout:'Temps écoulé',bands:[['Échauffement nécessaire','Les règles de base vous ont échappé cette fois. La recherche de motifs se travaille.'],['Logique opérationnelle','Vous trouvez les règles simples; les règles superposées demandent plus de temps.'],['Fort raisonnement matriciel','Vous maintenez plusieurs règles visuelles et filtrez bien le bruit.'],['Très fort résultat','Vous détectez les transformations, cycles et superpositions complexes bien au-dessus de la moyenne.']],shareText:'Mon résultat Matrix IQ : {score}/12, estimation {iq}. Testez votre raisonnement :'}};
const SHARE_UI={ru:{image:'Поделиться результатом как картинкой',copy:'Скопировать ссылку',saved:'Картинка сохранена, ссылка скопирована'},kk:{image:'Нәтижені суретпен бөлісу',copy:'Сілтемені көшіру',saved:'Сурет сақталды, сілтеме көшірілді'},en:{image:'Share result as an image',copy:'Copy link',saved:'Image saved and link copied'},fr:{image:'Partager le résultat en image',copy:'Copier le lien',saved:'Image enregistrée et lien copié'}};
// Короткие конфиги примитивов; все 12 задач ниже рисует один SVG-рендерер.
const P=(s,n=1)=>({k:'poly',s,n}),L=x=>({k:'lines',x}),A=d=>({k:'arrow',d}),D=p=>({k:'dot',p}),B=m=>({k:'bits',m}),C=(s,f,d)=>({k:'combo',s,f,d});
const Q=[
{m:[[P(0,1),P(0,2),P(0,3)],[P(4,1),P(4,2),P(4,3)],[P(3,1),P(3,2),null]],o:[P(3,3),P(3,4),P(4,3),P(0,3)],a:0},
{m:[[A(0),A(1),A(2)],[A(3),A(0),A(1)],[A(2),A(3),null]],o:[A(0),A(1),A(2),A(3)],a:0},
{m:[[L('v'),L('h'),L('vh')],[L('a'),L('b'),L('ab')],[L('vh'),L('ab'),null]],o:[L('vhab'),L('ab'),L('vh'),L('')],a:0},
{m:[[L('vha'),L('va'),L('h')],[L('vhab'),L('vhb'),L('a')],[L('hab'),L('hb'),null]],o:[L('a'),L('b'),L('h'),L('ab')],a:0},
{m:[[C(0,0,0),C(4,1,1),C(3,2,2)],[C(3,1,1),C(0,2,2),C(4,0,0)],[C(4,2,2),C(3,0,0),null]],o:[C(0,1,1),C(0,0,2),C(4,1,1),C(3,1,0)],a:0},
{m:[[D(0),D(1),D(2)],[D(1),D(2),D(3)],[D(2),D(3),null]],o:[D(0),D(1),D(2),D(3)],a:0},
{m:[[B(1),B(3),B(7)],[B(2),B(6),B(14)],[B(4),B(12),null]],o:[B(15),B(13),B(8),B(9)],a:1},
{m:[[P(3),P(4),P(6)],[P(5),P(3),P(7)],[P(4),P(6),null]],o:[P(8),P(9),P(10),P(6)],a:1},
{m:[[P(3,1),P(4,2),P(5,3)],[P(4,1),P(5,2),P(6,3)],[P(5,1),P(6,2),null]],o:[P(7,3),P(7,2),P(6,3),P(8,3)],a:0},
{m:[[D(0),D(2),D(1)],[D(1),D(3),D(2)],[D(2),D(0),null]],o:[D(3),D(0),D(1),D(2)],a:0},
{m:[[L('vh'),L('ha'),L('va')],[L('ab'),L('vb'),L('va')],[L('hb'),L('ab'),null]],o:[L('ha'),L('v'),L('h'),L('vb')],a:0},
{m:[[B(5),B(10),B(15)],[B(3),B(12),B(15)],[B(6),B(9),null]],o:[B(15),B(12),B(3),B(0)],a:0}
];
function shape(s,cx=50,cy=50,r=25){if(s===0)return `<circle cx="${cx}" cy="${cy}" r="${r}"/>`;const n=Math.max(3,s),pts=Array.from({length:n},(_,i)=>{const a=-Math.PI/2+i*Math.PI*2/n;return `${cx+Math.cos(a)*r},${cy+Math.sin(a)*r}`}).join(' ');return `<polygon points="${pts}"/>`}
function art(v){if(!v)return '<text x="50" y="62" text-anchor="middle" font-size="40">?</text>';let x='';if(v.k==='poly'){for(let i=0;i<v.n;i++)x+=shape(v.s,50+(i-(v.n-1)/2)*19,50,Math.max(8,22-v.n*3))}if(v.k==='arrow')x=`<path d="M50 76V25M50 25L35 42M50 25L65 42" transform="rotate(${v.d*90} 50 50)"/>`;if(v.k==='lines'){if(v.x.includes('v'))x+='<path d="M50 18V82"/>';if(v.x.includes('h'))x+='<path d="M18 50H82"/>';if(v.x.includes('a'))x+='<path d="M22 78L78 22"/>';if(v.x.includes('b'))x+='<path d="M22 22L78 78"/>'}if(v.k==='dot'){const p=[[25,25],[75,25],[75,75],[25,75]][v.p];x=`<rect x="15" y="15" width="70" height="70"/><circle cx="${p[0]}" cy="${p[1]}" r="8" fill="currentColor"/>`}if(v.k==='bits'){x='<rect x="18" y="18" width="64" height="64"/>';[[20,20],[52,20],[20,52],[52,52]].forEach((p,i)=>{if(v.m&(1<<i))x+=`<rect x="${p[0]}" y="${p[1]}" width="28" height="28" fill="currentColor"/>`;x+=`<rect x="${p[0]}" y="${p[1]}" width="28" height="28"/>`})}if(v.k==='combo'){const fills=['none','currentColor','url(#h)'];x=`<g fill="${fills[v.f]}">${shape(v.s)}</g>`;if(v.d<2)x+=`<circle cx="50" cy="50" r="7" fill="${v.d?'white':'currentColor'}"/>`}return x}
function svg(v,cell=false){return `<svg viewBox="0 0 100 100" aria-hidden="true"><defs><pattern id="h" width="8" height="8" patternUnits="userSpaceOnUse"><path d="M0 8L8 0"/></pattern></defs><g fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round" stroke-linejoin="round">${art(v)}</g>${cell?'':''}</svg>`}
function matrix(q){return `<svg viewBox="0 0 306 306" role="img"><defs><pattern id="h" width="8" height="8" patternUnits="userSpaceOnUse"><path d="M0 8L8 0" stroke="currentColor" stroke-width="2"/></pattern></defs>${q.m.flatMap((r,y)=>r.map((v,x)=>`<g transform="translate(${x*102+1} ${y*102+1})"><rect width="100" height="100" rx="10" fill="#102733" stroke="#2b5363"/><g fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round" stroke-linejoin="round">${art(v)}</g></g>`)).join('')}</svg>`}
const app=document.querySelector('#app');let at=0,answers=Array(Q.length).fill(null),end=0,tick=0,result=null,shareBlobPromise=null;
const restartText={ru:'↻ Начать заново',kk:'↻ Қайта бастау',en:'↻ Start over',fr:'↻ Recommencer'};
const top=()=>`<header class="top"><a class="brand" href="../../">PortHub · Matrix IQ</a><div class="tools">${end&&!result?`<button class="reset" id="reset">${restartText[lang]}</button>`:''}<a href="../../">${UI[lang].home}</a><select id="lang">${LANGS.map(x=>`<option ${x===lang?'selected':''}>${x.toUpperCase()}</option>`).join('')}</select></div></header>`;
function bind(){document.querySelector('#lang').onchange=e=>{lang=e.target.value.toLowerCase();localStorage.setItem('pt.lang',lang);result?showResult():end?question():intro()};const r=document.querySelector('#reset');if(r)r.onclick=start}
function intro(){clearInterval(tick);end=0;const c=UI[lang];app.innerHTML=top()+`<main class="panel intro"><div class="eyebrow">${c.tag}</div><h1>${c.title}</h1><p class="lead">${c.lead}</p><div class="reason">${c.why.map(x=>`<div><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}</div><p class="note">${c.note}</p><button class="primary wide" id="start">${c.start}</button></main>`;bind();document.querySelector('#start').onclick=start}
function start(){at=0;answers=Array(Q.length).fill(null);result=null;end=Date.now()+720000;localStorage.removeItem('pt.matrixIq.result');saveProgress();question();tick=setInterval(updateClock,250)}
function saveProgress(){localStorage.setItem('pt.matrixIq.progress',JSON.stringify({v:1,at,answers,end}))}
function clock(){return Math.max(0,end-Date.now())}function clockText(){const s=Math.ceil(clock()/1000);return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}function updateClock(){const el=document.querySelector('.clock');if(el)el.textContent=`${UI[lang].left}: ${clockText()}`;if(clock()<=0)finish(true)}
function question(){saveProgress();const c=UI[lang],q=Q[at];app.innerHTML=top()+`<main class="panel quiz"><div class="quiz-head"><span>${c.task} ${at+1} ${c.of} ${Q.length}</span><span class="clock">${c.left}: ${clockText()}</span></div><div class="progress"><i style="width:${at/Q.length*100}%"></i></div><div class="matrix">${matrix(q)}</div><h2 class="ask">${c.ask}</h2><div class="answers">${q.o.map((o,i)=>`<button class="answer ${answers[at]===i?'selected':''}" data-i="${i}" aria-label="${i+1}">${svg(o)}</button>`).join('')}</div><div class="nav"><button class="secondary" id="prev" ${at===0?'disabled':''}>←</button><button class="primary" id="next">${at===Q.length-1?c.finish:c.next} →</button></div></main>`;bind();document.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{answers[at]=+b.dataset.i;question()});document.querySelector('#prev').onclick=()=>{if(at){at--;question()}};document.querySelector('#next').onclick=()=>{if(answers[at]===null)return toast(c.choose);if(at<Q.length-1){at++;question()}else finish(false)}}
// Предварительная норма: raw μ=5.5, raw SD=2.5 → IQ μ=100, SD=15.
function iqNumber(score){return Math.max(61,Math.min(145,Math.round(100+(score-5.5)/2.5*15)))}function iqEstimate(score){return `≈${iqNumber(score)}`}function band(score){return score<=3?0:score<=6?1:score<=9?2:3}
function finish(timed){if(result)return;clearInterval(tick);const score=answers.reduce((n,x,i)=>n+(x===Q[i].a),0),spent=Math.min(720000,Math.max(0,720000-clock()));result={v:1,score,spent,iq:iqEstimate(score),timed};localStorage.removeItem('pt.matrixIq.progress');localStorage.setItem('pt.matrixIq.result',JSON.stringify(result));if(score>=10)localStorage.setItem('pt.achievement.matrixGold','1');showResult()}
function percentile(iq){const z=(iq-100)/15,t=1/(1+.2316419*Math.abs(z)),d=.3989423*Math.exp(-z*z/2),p=1-d*t*(.3193815+t*(-.3565638+t*(1.781478+t*(-1.821256+t*1.330274))));return Math.round((z<0?1-p:p)*100)}
function persona(score){const a={ru:['Выдуманный мем‑режим: Губка Боб и Патрик ищут правило вместе','Выдуманный мем‑режим: Гомер включил детектива','Выдуманный мем‑режим: Тони Старк собирает систему на лету','Выдуманный мем‑режим: Шерлок отбрасывает весь шум'],kk:['Ойдан шығарылған мем: Губка Боб пен Патрик ережені іздейді','Ойдан шығарылған мем: Гомер детектив болды','Ойдан шығарылған мем: Тони Старк жүйені тез жинайды','Ойдан шығарылған мем: Шерлок артықты сүзеді'],en:['Fictional meme mode: SpongeBob and Patrick hunt the rule','Fictional meme mode: Homer turns detective','Fictional meme mode: Tony Stark assembles the system','Fictional meme mode: Sherlock filters every distraction'],fr:['Mode mème fictif : Bob l’éponge et Patrick cherchent la règle','Mode mème fictif : Homer devient détective','Mode mème fictif : Tony Stark assemble le système','Mode mème fictif : Sherlock filtre tout le bruit']}[lang],d={ru:'Методика визуальных матриц опирается на научные принципы измерения подвижного интеллекта Gf. Шкала PortHub предварительная и не заменяет стандартизированную диагностику. Персонажи добавлены для юмора; приписываемые знаменитостям IQ могут быть неточны, поскольку нет подтверждения, что они проходили сопоставимый тест.',kk:'Көрнекі матрицалар әдісі Gf икемді интеллектін өлшеудің ғылыми қағидаларына сүйенеді. PortHub шкаласы алдын ала және стандартталған диагностиканы алмастырмайды. Кейіпкерлер әзіл үшін; атақтыларға телінетін IQ нақты болмауы мүмкін.',en:'Visual matrices are grounded in scientific approaches to fluid-intelligence (Gf) measurement. The PortHub scale is preliminary and does not replace standardized assessment. Characters are for humor; celebrity IQ claims may be inaccurate because comparable testing is unverified.',fr:'Les matrices visuelles reposent sur les principes scientifiques de mesure de l’intelligence fluide Gf. L’échelle PortHub est préliminaire et ne remplace pas une évaluation standardisée. Les personnages sont humoristiques ; les QI attribués aux célébrités peuvent être inexacts.'}[lang];return `${a[band(score)]}<small>${d}</small>`}
function showResult(){clearInterval(tick);const c=UI[lang],b=c.bands[band(result.score)],iq=iqNumber(result.score),pct=percentile(iq),pos=Math.max(0,Math.min(100,(iq-70)/.75)),s=SHARE_UI[lang];app.innerHTML=top()+`<main class="panel result"><div class="eyebrow">${c.result}</div><div class="score">${result.score}/12</div><h1>${b[0]}</h1><p>${b[1]}</p><div class="persona">${persona(result.score)}<small>${lang==='ru'?`Игровая ассоциация · выше примерно ${pct}% выборки`:`Playful analogy · about percentile ${pct}`}</small></div><div class="iq-scale"><div class="ticks"><span>70</span><span>85</span><span>100</span><span>115</span><span>130</span><span>145</span></div><div class="track"><i style="left:${pos}%"></i></div><b style="left:${pos}%">${result.iq}</b></div><div class="stats"><div class="stat"><b>${result.score}/12</b><span>${c.raw}</span></div><div class="stat"><b>${Math.floor(result.spent/60000)}:${String(Math.floor(result.spent/1000)%60).padStart(2,'0')}</b><span>${c.time}</span></div><div class="stat"><b>${result.iq}</b><span>${c.estimate}</span></div></div><p class="note">${c.note}</p><div class="actions"><button class="primary" id="share">↗ ${s.image}</button><button class="secondary" id="copy">${s.copy}</button><button class="secondary" id="again">${c.again}</button><a class="secondary" href="../../">${c.other}</a></div></main>`;bind();shareBlobPromise=resultCardBlob(b);document.querySelector('#again').onclick=start;document.querySelector('#copy').onclick=copyResultLink;document.querySelector('#share').onclick=share}
function resultUrl(){return `https://porthub.fyi/tests/matrix-iq/?lang=${lang}`}
function resultShareText(){return UI[lang].shareText.replace('{score}',result.score).replace('{iq}',result.iq)}
function wrapCanvas(ctx,text,x,y,maxWidth,lineHeight,maxLines=5){const words=String(text).split(/\s+/);let line='',lines=0;for(const word of words){const next=line?`${line} ${word}`:word;if(ctx.measureText(next).width>maxWidth&&line){ctx.fillText(line,x,y+lines*lineHeight);lines++;line=word;if(lines>=maxLines)break}else line=next}if(line&&lines<maxLines)ctx.fillText(line,x,y+lines*lineHeight);return y+(lines+1)*lineHeight}
function resultCardBlob(bandCopy){const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1350;const ctx=canvas.getContext('2d'),gradient=ctx.createLinearGradient(0,0,1080,1350);gradient.addColorStop(0,'#0d2834');gradient.addColorStop(1,'#061016');ctx.fillStyle=gradient;ctx.fillRect(0,0,1080,1350);ctx.fillStyle='#56e6ff';ctx.font='900 42px system-ui';ctx.fillText('PortHub · MATRIX IQ',80,105);ctx.fillStyle='#9db2bd';ctx.font='700 30px system-ui';ctx.fillText(UI[lang].result,80,180);ctx.fillStyle='#baff66';ctx.font='950 170px system-ui';ctx.fillText(`${result.score}/12`,76,355);ctx.fillStyle='#f3fbff';ctx.font='900 68px system-ui';let y=wrapCanvas(ctx,bandCopy[0],80,465,920,78,3);ctx.fillStyle='#d8e4e8';ctx.font='500 34px system-ui';y=wrapCanvas(ctx,bandCopy[1],80,y+30,920,50,5);ctx.fillStyle='#102733';ctx.fillRect(80,900,920,210);ctx.fillStyle='#56e6ff';ctx.font='900 50px system-ui';ctx.fillText(result.iq,125,995);ctx.fillStyle='#9db2bd';ctx.font='700 27px system-ui';ctx.fillText(UI[lang].estimate,125,1040);ctx.fillStyle='#f3fbff';ctx.font='900 50px system-ui';ctx.fillText(`${Math.floor(result.spent/60000)}:${String(Math.floor(result.spent/1000)%60).padStart(2,'0')}`,610,995);ctx.fillStyle='#9db2bd';ctx.font='700 27px system-ui';ctx.fillText(UI[lang].time,610,1040);ctx.fillStyle='#f2cb75';ctx.font='850 34px system-ui';ctx.fillText('porthub.fyi',80,1260);return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('PNG')),'image/png'))}
async function copyResultLink(silent=false){const value=`${resultShareText()} ${resultUrl()}`;try{await navigator.clipboard.writeText(value)}catch{const input=document.createElement('textarea');input.value=value;input.style.position='fixed';input.style.opacity='0';document.body.appendChild(input);input.select();document.execCommand('copy');input.remove()}if(!silent)toast(UI[lang].copied)}
async function share(){const c=UI[lang],s=SHARE_UI[lang],url=resultUrl(),text=resultShareText();try{const blob=await shareBlobPromise,file=new File([blob],'matrix-iq-result.png',{type:'image/png'});if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({title:'Matrix IQ',text,url,files:[file]});return}const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='matrix-iq-result.png';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);await copyResultLink(true);toast(s.saved)}catch(error){if(error?.name!=='AbortError')toast(c.copied)}}
function toast(s){const e=document.querySelector('#toast');e.textContent=s;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1600)}
try{const x=JSON.parse(localStorage.getItem('pt.matrixIq.result')||'null');if(x&&x.v===1&&Number.isInteger(x.score)&&x.score>=0&&x.score<=12)result=x;else{const p=JSON.parse(localStorage.getItem('pt.matrixIq.progress')||'null');if(p?.v===1&&Array.isArray(p.answers)&&p.answers.length===Q.length&&p.end>Date.now()){at=Math.max(0,Math.min(Q.length-1,p.at|0));answers=p.answers;end=p.end}}}catch{}if(result)showResult();else if(end){question();tick=setInterval(updateClock,250)}else intro();
})();
