const m = (ru, kk, en, fr) => ({ ru, kk, en, fr });
const q = (scale, ru, kk, en, fr) => ({ scale, text: m(ru, kk, en, fr) });
const p = (emoji, color, label, title, lead, strength, shadow, environment, experiment, areas, joke) => ({ emoji, color, label, title, lead, strength, shadow, environment, experiment, areas, joke });

const strengths = {
  id: 'strengths', icon: '⚡', count: 24, entertainment: false,
  title: m('Ваши рабочие суперсилы', 'Сіздің жұмыс күштеріңіз', 'Your working superpowers', 'Vos superpouvoirs au travail'),
  intro: m('24 понятные ситуации покажут не абстрактный «тип», а способы, которыми вы чаще приносите пользу.', '24 түсінікті жағдай сіздің жұмыста қалай пайда әкелетініңізді көрсетеді.', '24 plain situations reveal how you most naturally create value at work.', '24 situations claires montrent comment vous créez naturellement de la valeur.'),
  badge: m('8 сил · 6 минут', '8 күш · 6 минут', '8 strengths · 6 minutes', '8 forces · 6 minutes'),
  disclaimer: m('Тест описывает привычные способы действия, а не интеллект, характер целиком или ценность человека.', 'Тест әрекет ету әдеттерін сипаттайды, интеллект не адамның құнын емес.', 'This describes preferred ways of acting, not intelligence, your whole personality, or your worth.', 'Ce test décrit des façons d’agir préférées, pas l’intelligence, toute la personnalité ni la valeur humaine.'),
  scales: {
    logic: p('🔎','#5b5bd6',m('Логика','Логика','Logic','Logique'),m('Разборщик сложного','Күрделіні талдаушы','Complexity decoder','Décodeur de complexité'),m('Сначала понять, потом решать. Вы замечаете связи, противоречия и причины.', 'Алдымен түсіну, содан кейін шешу. Сіз байланыстар мен себептерді байқайсыз.', 'Understand first, then decide. You notice links, contradictions, and causes.', 'Comprendre d’abord, décider ensuite. Vous voyez les liens et les causes.'),m('Превращать туманную задачу в проверяемую схему.', 'Түсініксіз міндетті тексерілетін схемаға айналдыру.', 'Turn a vague problem into a testable model.', 'Transformer un problème flou en modèle vérifiable.'),m('Можно анализировать дольше, чем живёт сама проблема.', 'Мәселенің өзінен ұзақ талдауға болады.', 'Analysis can outlive the problem itself.', 'L’analyse peut durer plus longtemps que le problème.'),m('Доступ к фактам, сложные вопросы и время сосредоточиться.', 'Деректер, күрделі сұрақтар және тыныш уақыт.', 'Facts, hard questions, and focused time.', 'Des faits, des questions difficiles et du temps calme.'),m('Разберите одну спорную задачу и сформулируйте вывод в пяти строках.', 'Бір даулы мәселені бес жолмен қорытындылаңыз.', 'Analyze one disputed issue and state your conclusion in five lines.', 'Analysez une question discutée et concluez en cinq lignes.'),m('аналитика, аудит, стратегия, диагностика','талдау, аудит, стратегия, диагностика','analytics, audit, strategy, diagnosis','analyse, audit, stratégie, diagnostic'),m('Можете найти логическую ошибку даже в шутке. Не всегда обязательно.','Әзілден де логикалық қате таба аласыз. Міндетті емес.','You can find a logic flaw in a joke. You do not always have to.','Vous trouvez une faille logique même dans une blague. Pas toujours nécessaire.')),
    ideas: p('💡','#a254c4',m('Идеи','Идеялар','Ideas','Idées'),m('Генератор вариантов','Нұсқа генераторы','Option generator','Générateur d’options'),m('Когда один путь закрыт, вы быстро видите ещё несколько.', 'Бір жол жабылса, бірнеше жаңа жол көресіз.', 'When one route closes, you quickly see several more.', 'Quand une voie se ferme, vous en voyez vite plusieurs.'),m('Находить свежий угол и оживлять пустой лист.', 'Жаңа қыр тауып, бос парақты жандандыру.', 'Find a fresh angle and animate a blank page.', 'Trouver un angle neuf et donner vie à une page blanche.'),m('Новые идеи могут вытеснить завершение старых.', 'Жаңа идеялар бұрынғы істі аяқтауға кедергі болуы мүмкін.', 'New ideas can crowd out finishing old ones.', 'Les nouvelles idées peuvent empêcher de finir les anciennes.'),m('Свобода эксперимента, понятная аудитория и короткие циклы.', 'Тәжірибе еркіндігі, түсінікті аудитория және қысқа цикл.', 'Freedom to experiment, a clear audience, and short cycles.', 'Liberté d’expérimenter, public clair et cycles courts.'),m('За вечер закончите одну маленькую идею, не улучшая её бесконечно.', 'Бір кеште бір шағын идеяны аяқтаңыз.', 'Finish one small idea tonight without polishing forever.', 'Terminez une petite idée ce soir sans la perfectionner sans fin.'),m('продукт, дизайн, контент, маркетинг','өнім, дизайн, контент, маркетинг','product, design, content, marketing','produit, design, contenu, marketing'),m('Один вариант? Отлично, сейчас будет ещё семь.','Бір нұсқа ма? Қазір тағы жетеуі болады.','One option? Great, seven more are coming.','Une option ? Parfait, sept autres arrivent.')),
    people: p('🤝','#2d9b83',m('Люди','Адамдар','People','Personnes'),m('Человеческий интерфейс','Адамдар арасындағы көпір','Human interface','Interface humaine'),m('Вы слышите не только слова и помогаете людям понимать друг друга.', 'Сіз сөзді ғана емес, адамның ойын да түсінесіз.', 'You hear more than words and help people understand one another.', 'Vous entendez plus que les mots et aidez les gens à se comprendre.'),m('Переводить сложное на человеческий язык и снижать напряжение.', 'Күрделіні қарапайым тілге аударып, шиеленісті азайту.', 'Translate complexity into human language and lower tension.', 'Traduire la complexité en langage humain et apaiser la tension.'),m('Чужие эмоции и задачи могут занять слишком много места.', 'Өзгенің сезімі мен міндеті тым көп орын алуы мүмкін.', 'Other people’s emotions and tasks can take too much space.', 'Les émotions et tâches des autres peuvent prendre trop de place.'),m('Уважительная команда, обратная связь и видимая польза людям.', 'Сыйластық, кері байланыс және адамдарға көрінетін пайда.', 'Respect, feedback, and visible usefulness to people.', 'Respect, retours et utilité visible pour les personnes.'),m('Проведите короткое объяснение или помогите решить один конфликт.', 'Қысқа түсіндірме өткізіңіз немесе бір дауды шешуге көмектесіңіз.', 'Teach something briefly or help resolve one disagreement.', 'Expliquez brièvement quelque chose ou aidez à résoudre un désaccord.'),m('обучение, HR, продажи, помощь, переговоры','оқыту, HR, сату, көмек, келіссөз','learning, HR, sales, support, negotiation','formation, RH, vente, aide, négociation'),m('Иногда вас зовут на встречу просто чтобы остальные не поссорились.','Кейде сізді жиналысқа басқалар ұрыспасын деп шақырады.','Sometimes you are invited just so everyone else stays civil.','On vous invite parfois juste pour que les autres restent calmes.')),
    execution: p('✅','#66758d',m('Исполнение','Аяқтау','Execution','Exécution'),m('Доводчик','Аяқтаушы','Finisher','Finisseur'),m('Вы цените не красивое начало, а готовый работающий результат.', 'Сіз әдемі бастамадан гөрі дайын нәтижені бағалайсыз.', 'You value a finished, working result more than a beautiful start.', 'Vous valorisez un résultat terminé plus qu’un beau début.'),m('Держать темп, закрывать хвосты и превращать план в факт.', 'Қарқынды ұстап, жоспарды нәтижеге айналдыру.', 'Maintain pace, close loose ends, and turn plans into facts.', 'Tenir le rythme, fermer les boucles et rendre le plan réel.'),m('Можно тащить лишнее только потому, что «надо закончить».', 'Тек «аяқтау керек» деп артық жүкті көтеруге болады.', 'You may carry unnecessary work simply because it must be finished.', 'Vous pouvez porter un travail inutile juste pour le terminer.'),m('Ясная цель, критерий готовности и право убирать лишнее.', 'Анық мақсат, дайындық өлшемі және артығын алып тастау.', 'A clear goal, definition of done, and permission to remove waste.', 'Objectif clair, définition du terminé et droit de supprimer le superflu.'),m('Выберите один зависший хвост и закройте его за 45 минут.', 'Бір тұрып қалған істі 45 минутта аяқтаңыз.', 'Pick one stale task and close it in 45 minutes.', 'Choisissez une tâche bloquée et terminez-la en 45 minutes.'),m('операции, проекты, производство, логистика','операциялар, жобалар, өндіріс, логистика','operations, projects, production, logistics','opérations, projets, production, logistique'),m('Вы знаете страшную тайну: дедлайн иногда можно выполнить.','Дедлайнды кейде орындауға болатынын білесіз.','You know the secret: deadlines can occasionally be met.','Vous connaissez le secret : un délai peut parfois être respecté.')),
    influence: p('📣','#d77a31',m('Влияние','Ықпал','Influence','Influence'),m('Собиратель поддержки','Қолдау жинаушы','Support builder','Mobilisateur'),m('Вы умеете занять позицию, показать ценность и потянуть людей за идеей.', 'Сіз позицияны ұстап, идеяға қолдау жинайсыз.', 'You can take a position, show value, and gather people behind an idea.', 'Vous savez prendre position, montrer la valeur et rassembler.'),m('Давать движению импульс и договариваться о ресурсах.', 'Қозғалысқа серпін беріп, ресурс туралы келісу.', 'Give momentum and negotiate for resources.', 'Donner de l’élan et négocier les ressources.'),m('Убедительность без проверки может превратиться в обещания.', 'Тексерусіз сендіру артық уәдеге айналуы мүмкін.', 'Persuasion without checks can become overpromising.', 'La persuasion sans vérification peut devenir une promesse excessive.'),m('Видимая цель, право решать и честная обратная связь.', 'Көрінетін мақсат, шешім құқығы және адал кері байланыс.', 'Visible goals, decision rights, and honest feedback.', 'Objectifs visibles, droit de décider et retours honnêtes.'),m('Сформулируйте полезную идею в трёх предложениях и покажите пяти людям.', 'Пайдалы идеяны үш сөйлеммен бес адамға көрсетіңіз.', 'Pitch a useful idea in three sentences to five people.', 'Présentez une idée utile en trois phrases à cinq personnes.'),m('руководство, продажи, партнёрства, продукт','басқару, сату, серіктестік, өнім','leadership, sales, partnerships, product','direction, vente, partenariats, produit'),m('«Кто возьмёт ответственность?» подозрительно часто заканчивается вашим именем.','«Кім жауап береді?» деген сұрақ жиі сізбен аяқталады.','“Who will own this?” suspiciously often ends with your name.','« Qui s’en charge ? » finit souvent par votre nom.')),
    adaptability: p('🌀','#3d93ad',m('Адаптация','Бейімделу','Adaptability','Adaptation'),m('Навигатор перемен','Өзгеріс навигаторы','Change navigator','Navigateur du changement'),m('Если реальность не прочитала план, вы меняете тактику без долгой драмы.', 'Шындық жоспарға сай болмаса, тактиканы тез өзгертесіз.', 'If reality ignores the plan, you change tactics without prolonged drama.', 'Si la réalité ignore le plan, vous changez de tactique sans drame.'),m('Быстро замечать новый контекст и находить рабочий обходной путь.', 'Жаңа жағдайды байқап, жұмыс істейтін жол табу.', 'Read new context quickly and find a workable route.', 'Lire vite le contexte et trouver un passage praticable.'),m('Постоянная смена курса может лишить результат глубины.', 'Бағытты жиі ауыстыру нәтижені үстірт етуі мүмкін.', 'Constant course changes can keep results shallow.', 'Changer sans cesse de cap peut rendre le résultat superficiel.'),m('Живые проекты, короткие циклы и ясная точка проверки.', 'Жанды жобалар, қысқа цикл және анық тексеру нүктесі.', 'Live projects, short cycles, and a clear review point.', 'Projets vivants, cycles courts et point de contrôle clair.'),m('Для текущей проблемы придумайте план Б и условие, когда на него переходить.', 'Қазіргі мәселе үшін Б жоспарын және оған өту шартын жазыңыз.', 'Create a plan B and define exactly when to use it.', 'Créez un plan B et définissez quand l’utiliser.'),m('стартапы, сервис, кризисные проекты, продукт','стартап, сервис, дағдарыс жобалары, өнім','startups, service, crisis projects, product','start-up, service, projets de crise, produit'),m('План Б появляется раньше, чем другие успели оплакать план А.','Б жоспары басқалар А жоспарына өкініп үлгермей пайда болады.','Plan B appears before others finish mourning plan A.','Le plan B arrive avant la fin du deuil du plan A.')),
    depth: p('🧠','#704ac7',m('Глубина','Тереңдік','Depth','Profondeur'),m('Глубокий эксперт','Терең сарапшы','Deep expert','Expert en profondeur'),m('Вы способны долго держать внимание и докапываться до нюансов.', 'Сіз назарды ұзақ ұстап, ұсақ мәнге дейін зерттейсіз.', 'You can hold focus and keep digging into nuance.', 'Vous pouvez rester concentré et creuser les nuances.'),m('Накапливать редкое знание и видеть детали, которые пропускают другие.', 'Сирек білім жинап, өзгелер көрмеген бөлшекті байқау.', 'Build rare knowledge and notice details others miss.', 'Construire un savoir rare et voir les détails manqués.'),m('Интересная глубина может оторвать от срока и аудитории.', 'Қызықты тереңдік мерзім мен аудиториядан алыстатуы мүмкін.', 'Interesting depth can detach you from deadlines and audience needs.', 'La profondeur peut vous éloigner du délai et du public.'),m('Тихое время, сложная тема и возможность стать мастером.', 'Тыныш уақыт, күрделі тақырып және шебер болу мүмкіндігі.', 'Quiet time, a hard topic, and room to master it.', 'Temps calme, sujet difficile et espace pour le maîtriser.'),m('Выберите один вопрос и изучайте только его 60 минут без новых вкладок.', 'Бір сұрақты 60 минут жаңа бет ашпай зерттеңіз.', 'Study one question for 60 minutes without opening new tabs.', 'Étudiez une seule question 60 minutes sans nouvel onglet.'),m('R&D, инженерия, право, экспертиза, наука','R&D, инженерия, құқық, сараптама, ғылым','R&D, engineering, law, expertise, science','R&D, ingénierie, droit, expertise, science'),m('Не просто загуглили — случайно получили второе образование за вечер.','Жай іздемедіңіз — бір кеште екінші білім алдыңыз.','You did not just search; you accidentally earned a second degree tonight.','Vous n’avez pas cherché : vous avez presque obtenu un second diplôme.')),
    calm: p('🧊','#2f8f91',m('Спокойствие','Сабыр','Calm','Calme'),m('Холодная голова','Салқын ой','Cool head','Tête froide'),m('Под давлением у вас сохраняется рабочая часть мозга.', 'Қысым кезінде ойлау қабілетіңіз сақталады.', 'Under pressure, the working part of your brain tends to stay online.', 'Sous pression, la partie utile de votre cerveau reste active.'),m('Отделять срочное от громкого и возвращать группу к фактам.', 'Шұғылды дауыстыдан бөліп, топты дерекке қайтару.', 'Separate urgent from loud and bring a group back to facts.', 'Séparer l’urgent du bruyant et ramener le groupe aux faits.'),m('Спокойный вид могут принять за безразличие — проговаривайте участие.', 'Сабырлы кейіп немқұрайдылық болып көрінуі мүмкін.', 'Calm can look like indifference, so make your care visible.', 'Le calme peut sembler indifférent : montrez votre implication.'),m('Ответственность без постоянной паники и понятный порядок действий.', 'Үнемі дүрбелеңсіз жауапкершілік және түсінікті әрекет.', 'Responsibility without constant panic and a clear response plan.', 'Responsabilité sans panique permanente et plan d’action clair.'),m('В следующей срочной ситуации сначала назовите три факта и один шаг.', 'Келесі шұғыл жағдайда үш факт пен бір қадамды атаңыз.', 'In the next urgent moment, name three facts and one next step.', 'À la prochaine urgence, nommez trois faits et une étape.'),m('операции, контроль, медицина, руководство, безопасность','операциялар, бақылау, медицина, басқару, қауіпсіздік','operations, control, health, leadership, safety','opérations, contrôle, santé, direction, sécurité'),m('Когда все бегают, вы раздражающе спокойно спрашиваете: «что произошло?»','Бәрі жүгіргенде, сіз сабырмен «не болды?» дейсіз.','When everyone runs, you calmly ask, “What actually happened?”','Quand tout le monde court, vous demandez calmement : « Que s’est-il passé ? »'))
  },
  questions: [
    q('logic','В новой задаче сначала отделяю факты от предположений','Жаңа міндетте алдымен фактіні болжамнан бөлемін','In a new task, I first separate facts from assumptions','Dans une nouvelle tâche, je sépare d’abord les faits des suppositions'),
    q('ideas','Обычно могу предложить несколько разных решений','Әдетте бірнеше түрлі шешім ұсына аламын','I can usually suggest several different solutions','Je peux généralement proposer plusieurs solutions'),
    q('people','Замечаю, когда люди говорят об одном, но понимают разное','Адамдар бір сөзді әртүрлі түсінгенін байқаймын','I notice when people use the same words but mean different things','Je remarque quand les mêmes mots cachent des sens différents'),
    q('execution','После старта мне важно довести дело до готового результата','Бастаған істі дайын нәтижеге жеткізу мен үшін маңызды','After starting, I want to carry the work to a finished result','Après avoir commencé, je veux aller jusqu’au résultat fini'),
    q('influence','Мне комфортно представить идею и попросить поддержку','Идеяны ұсынып, қолдау сұрау маған ыңғайлы','I am comfortable presenting an idea and asking for support','Je suis à l’aise pour présenter une idée et demander du soutien'),
    q('adaptability','Если план не работает, быстро меняю способ','Жоспар істемесе, тәсілді тез өзгертемін','If a plan fails, I quickly change the approach','Si un plan échoue, je change vite d’approche'),
    q('depth','Могу долго изучать одну тему, не теряя интереса','Бір тақырыпты қызығушылық жоғалтпай ұзақ зерттей аламын','I can study one subject deeply without losing interest','Je peux approfondir un sujet longtemps sans perdre l’intérêt'),
    q('calm','В срочной ситуации сначала уточняю, что произошло','Шұғыл жағдайда алдымен не болғанын анықтаймын','In an urgent situation, I first clarify what happened','Dans une urgence, je commence par clarifier les faits'),
    q('logic','Перед решением проверяю, не противоречат ли данные друг другу','Шешім алдында деректердің қайшы емес екенін тексеремін','Before deciding, I check whether the evidence conflicts','Avant de décider, je vérifie si les données se contredisent'),
    q('ideas','Мне нравится начинать с пустого листа','Бос парақтан бастағанды ұнатамын','I enjoy starting from a blank page','J’aime partir d’une page blanche'),
    q('people','Умею объяснить сложное простыми словами','Күрделіні қарапайым сөзбен түсіндіре аламын','I can explain complex things in plain language','Je sais expliquer les choses complexes simplement'),
    q('execution','Замечаю незакрытые мелочи и возвращаюсь к ним','Аяқталмаған ұсақ істі байқап, қайта ораламын','I notice loose ends and return to close them','Je remarque les détails inachevés et j’y reviens'),
    q('influence','Могу договориться о ресурсах или условиях','Ресурс не шарт туралы келіссөз жүргізе аламын','I can negotiate for resources or terms','Je peux négocier des ressources ou des conditions'),
    q('adaptability','В незнакомой ситуации быстро нахожу рабочий ритм','Бейтаныс жағдайда жұмыс ырғағын тез табамын','I quickly find a workable rhythm in unfamiliar situations','Je trouve vite un rythme efficace dans une situation nouvelle'),
    q('depth','Обычно замечаю нюансы, которые другие пропускают','Өзгелер өткізіп алған ұсақ мәнді байқаймын','I often notice nuances others miss','Je remarque souvent des nuances que les autres manquent'),
    q('calm','Под давлением могу продолжать говорить конкретно','Қысымда да нақты сөйлей аламын','Under pressure, I can keep speaking concretely','Sous pression, je peux rester concret'),
    q('logic','Мне интересно искать настоящую причину ошибки','Қатенің шынайы себебін іздеу қызық','I enjoy finding the real cause of an error','J’aime chercher la vraie cause d’une erreur'),
    q('ideas','Часто вижу, как привычную вещь можно сделать иначе','Таныс затты басқаша жасау жолын жиі көремін','I often see how a familiar thing could be done differently','Je vois souvent comment faire autrement une chose familière'),
    q('people','Могу помочь двум сторонам услышать друг друга','Екі тараптың бірін-бірі естуіне көмектесе аламын','I can help two sides hear one another','Je peux aider deux parties à s’écouter'),
    q('execution','Мне легче работать, когда есть понятный итог','Нәтиже анық болса, жұмыс істеу жеңіл','I work better when the finish line is clear','Je travaille mieux quand le résultat attendu est clair'),
    q('influence','Если никто не начинает, могу взять инициативу','Ешкім бастамаса, бастаманы қолға аламын','If nobody starts, I can take initiative','Si personne ne commence, je peux prendre l’initiative'),
    q('adaptability','После неожиданной перемены быстро собираю новый план','Күтпеген өзгерістен кейін жаңа жоспарды тез құрамын','After an unexpected change, I quickly rebuild the plan','Après un changement imprévu, je reconstruis vite le plan'),
    q('depth','Предпочитаю хорошо понять одну тему, а не пробежать пять','Бес тақырыпты үстірт өткеннен біреуін жақсы түсінгенді қалаймын','I prefer understanding one topic well over skimming five','Je préfère bien comprendre un sujet plutôt que survoler cinq'),
    q('calm','Когда вокруг паника, могу выделить следующий конкретный шаг','Айнала дүрбелең болса, келесі нақты қадамды бөле аламын','When others panic, I can identify the next concrete step','Quand les autres paniquent, je peux identifier la prochaine étape')
  ]
};

const trajectory = {
  id:'trajectory',icon:'🧭',count:20,entertainment:false,
  title:m('Предприниматель, руководитель или специалист?','Кәсіпкер, басшы немесе маман?','Founder, manager, or specialist?','Entrepreneur, manager ou spécialiste ?'),
  intro:m('Не ищем «лучшую» карьеру. Сравним пять способов строить работу, доход, свободу и ответственность.','«Ең жақсы» жолды емес, жұмыс пен еркіндікті құрудың бес тәсілін салыстырамыз.','There is no “best” path. Compare five ways to build work, income, freedom, and responsibility.','Il n’y a pas de voie « supérieure ». Comparez cinq façons de construire travail, revenu et liberté.'),
  badge:m('5 траекторий · 5 минут','5 жол · 5 минут','5 paths · 5 minutes','5 trajectoires · 5 minutes'),
  disclaimer:m('Ни один путь не выше другого. Результат показывает текущие предпочтения; они меняются с опытом, деньгами, здоровьем и этапом жизни.','Ешбір жол жоғары емес. Қалау тәжірибе мен өмір кезеңіне қарай өзгереді.','No path ranks above another. Preferences can change with experience, money, health, and life stage.','Aucune voie n’est supérieure. Les préférences changent avec l’expérience et la vie.'),
  scales:{
    founder:p('🚀','#db7432',m('Основатель','Негізін қалаушы','Founder','Fondateur'),m('Строитель своего','Өз ісін құрушы','Own-venture builder','Créateur de son projet'),m('Вас привлекает возможность выбрать направление и построить систему с нуля.','Бағытты таңдап, жүйені нөлден құру қызықтырады.','You are drawn to choosing direction and building from zero.','Vous aimez choisir la direction et construire de zéro.'),m('Видеть возможность и брать на себя неопределённость.','Мүмкіндікті көріп, белгісіздікті қабылдау.','Spot opportunity and accept uncertainty.','Voir l’occasion et accepter l’incertitude.'),m('Риск романтизировать хаос и недооценить продажи и запас денег.','Хаосты әдемілеп, сату мен қаржы қорын бағаламау қаупі бар.','You may romanticize chaos and underestimate sales or cash runway.','Risque de romantiser le chaos et sous-estimer ventes et trésorerie.'),m('Рынок рядом, короткая проверка идей и право менять курс.','Нарыққа жақын, идеяны қысқа тексеру және бағытты өзгерту құқығы.','Close to the market, fast tests, and freedom to change course.','Proximité du marché, tests rapides et liberté de changer de cap.'),m('Попробуйте продать маленький результат до создания большого продукта.','Үлкен өнімнен бұрын шағын нәтижені сатып көріңіз.','Sell a small outcome before building a large product.','Vendez un petit résultat avant de créer un grand produit.'),m('свой бизнес, стартап, агентство, продукт','өз бизнесі, стартап, агенттік, өнім','business, startup, agency, product','entreprise, start-up, agence, produit'),m('Стабильность прекрасна. Особенно когда построили её сами после хаоса.','Тұрақтылық жақсы. Әсіресе оны хаостан кейін өзіңіз құрсаңыз.','Stability is lovely—especially after you build it from chaos.','La stabilité est belle, surtout après l’avoir construite dans le chaos.')),
    manager:p('👥','#5e61cb',m('Руководитель','Басшы','Manager','Manager'),m('Усилитель команды','Команданы күшейтуші','Team multiplier','Multiplicateur d’équipe'),m('Ваш рычаг — общий результат через людей, приоритеты и решения.','Сіздің тетігіңіз — адамдар мен шешім арқылы ортақ нәтиже.','Your leverage is a shared result through people, priorities, and decisions.','Votre levier est le résultat collectif via les personnes et décisions.'),m('Собирать сильных людей и создавать ясность.','Күшті адамдарды жинап, айқындық жасау.','Build a strong team and create clarity.','Réunir une équipe forte et créer de la clarté.'),m('Можно стать диспетчером чужих задач и забыть про развитие людей.','Өзгенің тапсырмасын ғана таратып, адам дамуын ұмытуға болады.','You can become a task dispatcher and forget people’s growth.','Vous pouvez distribuer les tâches et oublier le développement.'),m('Реальные полномочия, честная ответственность и поддержка сверху.','Нақты өкілеттік, адал жауапкершілік және қолдау.','Real authority, clear responsibility, and support above you.','Autorité réelle, responsabilité claire et soutien.'),m('Организуйте маленький проект с двумя людьми и запросите обратную связь.','Екі адаммен шағын жоба өткізіп, кері байланыс сұраңыз.','Lead a small two-person project and ask for feedback.','Dirigez un petit projet à deux personnes et demandez un retour.'),m('team lead, руководитель, program manager','team lead, басшы, program manager','team lead, manager, program manager','chef d’équipe, manager, program manager'),m('Хотели просто поработать, а через неделю уже распределяете роли.','Жай жұмыс істегіңіз келді, бір аптадан соң рөл бөліп жүрсіз.','You meant to help; a week later you are assigning roles.','Vous vouliez aider ; une semaine plus tard vous répartissez les rôles.')),
    expert:p('🧠','#774bc5',m('Эксперт','Сарапшы','Expert','Expert'),m('Мастер глубины','Тереңдік шебері','Depth master','Maître de la profondeur'),m('Вам важнее стать очень сильным в области, чем владеть большим штатом.','Үлкен штаттан гөрі салада өте мықты болу маңызды.','Deep mastery matters more than owning a large headcount.','La maîtrise profonde compte plus qu’une grande équipe.'),m('Решать редкие сложные задачи и поднимать стандарт качества.','Сирек күрделі міндетті шешіп, сапа деңгейін көтеру.','Solve rare hard problems and raise quality standards.','Résoudre des problèmes rares et élever la qualité.'),m('Глубина может стать укрытием от переговоров и видимости.','Тереңдік келіссөз бен көрінуден жасырынуға айналуы мүмкін.','Depth can become shelter from negotiation and visibility.','La profondeur peut cacher l’évitement de la négociation.'),m('Сложные задачи, автономия метода и уважение к экспертизе.','Күрделі міндет, әдіс еркіндігі және сараптамаға құрмет.','Hard problems, method autonomy, and respect for expertise.','Problèmes difficiles, autonomie de méthode et respect de l’expertise.'),m('Опубликуйте один короткий разбор или помогите решить редкую проблему.','Бір қысқа талдау жариялаңыз немесе сирек мәселені шешіңіз.','Publish one short analysis or solve one unusually hard problem.','Publiez une courte analyse ou résolvez un problème rare.'),m('senior/lead, архитектор, консультант, исследователь','senior/lead, сәулетші, кеңесші, зерттеуші','senior/lead, architect, consultant, researcher','senior/lead, architecte, consultant, chercheur'),m('Рост — когда сложные вопросы перестают задавать всем и несут вам.','Өсу — күрделі сұрақтарды енді бәріне емес, сізге әкеледі.','Growth is when hard questions stop going to everyone and come to you.','La progression, c’est quand les questions difficiles arrivent chez vous.')),
    independent:p('🪁','#2f95a0',m('Независимый специалист','Тәуелсіз маман','Independent specialist','Spécialiste indépendant'),m('Свободный профессионал','Еркін кәсіпқой','Independent professional','Professionnel indépendant'),m('Вам нужна автономия без обязательной мечты строить корпорацию.','Корпорация құрмай-ақ, автономия қажет.','You want autonomy without necessarily building a corporation.','Vous voulez l’autonomie sans devoir bâtir une entreprise.'),m('Выбирать клиентов, формат и способ решения.','Клиентті, форматты және шешу тәсілін таңдау.','Choose clients, format, and method.', 'Choisir clients, format et méthode.'),m('Свобода приносит продажи, учёт и несколько начальников-клиентов.','Еркіндікпен бірге сату, есеп және бірнеше клиент-басшы келеді.','Freedom includes sales, admin, and several client-bosses.','La liberté inclut ventes, gestion et plusieurs clients-patrons.'),m('Чёткая специализация, финансовая подушка и понятные границы.','Анық мамандану, қаржы қоры және шекара.','Clear specialization, cash buffer, and firm boundaries.','Spécialisation claire, réserve financière et limites.'),m('Предложите одну понятную услугу реальному клиенту.','Бір түсінікті қызметті нақты клиентке ұсыныңыз.','Offer one clearly defined service to a real client.','Proposez un service clair à un vrai client.'),m('фриланс, частная практика, консалтинг, проектная работа','фриланс, жеке практика, кеңес, жоба жұмысы','freelance, private practice, consulting, project work','freelance, pratique privée, conseil, projets'),m('Начальника нет. Потом выясняется, что клиентов несколько.','Бастық жоқ. Кейін клиент бірнешеу екені белгілі болады.','No boss—then you notice you have several clients.','Pas de patron, puis vous découvrez plusieurs clients.')),
    steady:p('🛡️','#477c65',m('Стабильный профессионал','Тұрақты кәсіпқой','Steady professional','Professionnel stable'),m('Надёжный мастер','Сенімді шебер','Reliable professional','Professionnel fiable'),m('Ясные ожидания, качественная работа и жизнь вне работы для вас реальная ценность.','Анық талап, сапалы жұмыс және жұмыстан тыс өмір маңызды.','Clear expectations, quality work, and life outside work genuinely matter.', 'Des attentes claires, du bon travail et une vie hors travail comptent.'),m('Создавать надёжный результат без постоянного героизма.','Үнемі ерліксіз сенімді нәтиже жасау.','Create reliable outcomes without constant heroics.','Créer un résultat fiable sans héroïsme permanent.'),m('Стабильность может задержать смену среды, которая уже перестала подходить.','Тұрақтылық енді жарамайтын ортада ұстап қалуы мүмкін.','Stability can keep you in an environment that no longer fits.','La stabilité peut vous retenir dans un environnement inadéquat.'),m('Понятная роль, справедливые правила, предсказуемый ритм.','Түсінікті рөл, әділ ереже және болжамды ырғақ.','A clear role, fair rules, and a predictable rhythm.','Rôle clair, règles justes et rythme prévisible.'),m('Сравните три вакансии не только по зарплате, но и по ритму и границам.','Үш жұмысты жалақымен ғана емес, ырғақ пен шекарамен салыстырыңыз.','Compare three jobs by rhythm and boundaries, not salary alone.','Comparez trois emplois par rythme et limites, pas seulement salaire.'),m('корпоративная экспертиза, техника, качество, стабильные роли','корпоративтік сараптама, техника, сапа, тұрақты рөл','corporate expertise, technical, quality, stable roles','expertise en entreprise, technique, qualité, rôles stables'),m('Бизнес-план на вечер: закрыть ноутбук вовремя.','Кешкі бизнес-жоспар: ноутбукті уақытында жабу.','Tonight’s business plan: close the laptop on time.','Plan d’affaires du soir : fermer l’ordinateur à l’heure.'))
  },
  questions:[
    q('founder','Мне интересно построить продукт или услугу с нуля','Өнім не қызметті нөлден құру қызық','I want to build a product or service from zero','Je veux créer un produit ou service de zéro'),q('manager','Мне интересно отвечать за общий результат команды','Команданың ортақ нәтижесіне жауап беру қызық','I want responsibility for a team’s shared result','Je veux répondre du résultat collectif'),q('expert','Мне важно стать человеком, к которому идут с самыми сложными вопросами','Ең күрделі сұрақпен келетін маман болғым келеді','I want to be the person others bring the hardest questions to','Je veux être la personne à qui l’on confie les questions les plus difficiles'),q('independent','Мне хочется самому выбирать клиентов и формат работы','Клиент пен жұмыс форматын өзім таңдағым келеді','I want to choose my own clients and work format','Je veux choisir mes clients et mon format de travail'),q('steady','Мне важны предсказуемый доход и понятные ожидания','Болжамды табыс пен анық талап маңызды','Predictable income and clear expectations matter to me','Un revenu prévisible et des attentes claires comptent'),
    q('founder','Финансовая неопределённость кажется приемлемой ради своего направления','Өз бағытым үшін қаржылық белгісіздікті қабылдай аламын','I can accept financial uncertainty for my own direction','Je peux accepter l’incertitude financière pour ma propre direction'),q('manager','Мне нравится распределять роли и помогать людям расти','Рөл бөліп, адамдардың өсуіне көмектесу ұнайды','I enjoy assigning roles and helping people grow','J’aime répartir les rôles et aider les personnes à progresser'),q('expert','Свобода выбирать способ решения важнее статуса руководителя','Шешу тәсілін таңдау еркіндігі басшы мәртебесінен маңызды','Freedom in how I solve problems matters more than manager status','La liberté de méthode compte plus que le statut de manager'),q('independent','Несколько проектов привлекают больше одной постоянной должности','Бір тұрақты қызметтен бірнеше жоба қызығырақ','Several projects appeal to me more than one permanent role','Plusieurs projets m’attirent plus qu’un poste permanent'),q('steady','После работы хочу спокойно переключаться на свою жизнь','Жұмыстан кейін өз өміріме тыныш ауысқым келеді','I want to switch fully to my own life after work','Je veux vraiment passer à ma vie personnelle après le travail'),
    q('founder','Продажи и поиск спроса кажутся частью интересной игры','Сату мен сұраныс іздеу қызық ойынның бір бөлігі','Sales and finding demand feel like an interesting part of the game','La vente et la recherche de demande font partie du jeu'),q('manager','Сложное решение за команду пугает меньше, чем отсутствие полномочий','Команда үшін күрделі шешім өкілетсіздіктен аз қорқытады','A hard team decision worries me less than lacking authority','Une décision difficile me gêne moins que l’absence d’autorité'),q('expert','Лучше редкая компетенция, чем широкий набор поверхностных навыков','Үстірт көп дағдыдан сирек терең құзырет жақсы','I prefer rare depth over many shallow skills','Je préfère une compétence rare à de nombreux savoirs superficiels'),q('independent','Ради автономии могу самостоятельно вести переговоры, учёт и расписание','Автономия үшін келіссөз, есеп және кестені өзім жүргіземін','I can handle sales, admin, and scheduling for autonomy','Je peux gérer vente, administration et planning pour l’autonomie'),q('steady','Предсказуемый ритм для меня не скука, а ресурс','Болжамды ырғақ мен үшін жалықтыру емес, ресурс','A predictable rhythm is a resource, not boredom','Un rythme prévisible est une ressource, pas un ennui'),
    q('founder','Если проект провалится, мне проще запустить следующую попытку','Жоба сәтсіз болса, келесі әрекетті бастау оңай','If a project fails, I can imagine launching another attempt','Si un projet échoue, je peux en lancer un autre'),q('manager','Мне нравится, когда мой результат усиливается работой других людей','Нәтижем өзге адамдардың еңбегімен күшейгені ұнайды','I like my impact being multiplied through other people','J’aime multiplier mon impact grâce aux autres'),q('expert','Долгое обучение ради мастерства в одной области меня не пугает','Бір салада шебер болу үшін ұзақ оқу мені қорқытпайды','I can study for a long time to master one field','Je peux étudier longtemps pour maîtriser un domaine'),q('independent','Свобода выбирать нагрузку важнее карьерной лестницы','Жүктемені таңдау еркіндігі мансап сатысынан маңызды','Freedom to choose workload matters more than a career ladder','Choisir ma charge compte plus qu’une échelle de carrière'),q('steady','Хорошая работа не обязана становиться центром всей жизни','Жақсы жұмыс бүкіл өмірдің орталығы болуы міндетті емес','A good job does not need to become the center of life','Un bon travail ne doit pas devenir le centre de la vie')]
};

const numerologyDetails = {
  '1':{
    strength:m('Быстро переводите идею в первый шаг и берёте ответственность за направление.','Идеяны алғашқы қадамға тез айналдырып, бағыт үшін жауапкершілік аласыз.','You turn an idea into a first step quickly and take responsibility for direction.','Vous transformez vite une idée en première étape et assumez la direction.'),
    shadow:m('Есть риск торопить людей или начинать больше, чем получается довести.','Адамдарды асықтыру немесе аяқтауға үлгермейтін көп істі бастау қаупі бар.','You may rush people or start more than you can finish.','Vous pouvez presser les autres ou lancer plus que vous ne pouvez terminer.'),
    environment:m('Подходят задачи, где можно принимать решения и быстро видеть отклик.','Шешім қабылдап, нәтижені тез көруге болатын міндеттер сай келеді.','Work fits when you can make decisions and see feedback quickly.','Les missions où vous décidez et voyez vite le retour vous conviennent.'),
    experiment:m('Выберите одну идею и за семь дней доведите её до первого измеримого результата.','Бір идеяны таңдап, жеті күнде алғашқы өлшенетін нәтижеге жеткізіңіз.','Choose one idea and take it to a first measurable result within seven days.','Choisissez une idée et obtenez un premier résultat mesurable en sept jours.')
  },
  '2':{
    strength:m('Замечаете позиции обеих сторон и помогаете договариваться без лишней борьбы.','Екі жақтың да ойын байқап, артық тартыссыз келісуге көмектесесіз.','You notice both sides and help people reach agreement without needless conflict.','Vous voyez les deux côtés et facilitez l’accord sans conflit inutile.'),
    shadow:m('Стараясь сохранить мир, можно слишком долго откладывать собственную позицию.','Тыныштықты сақтаймын деп, өз пікіріңізді тым ұзақ кейінге қалдыруыңыз мүмкін.','Keeping the peace can make you postpone your own position for too long.','Préserver la paix peut vous faire repousser trop longtemps votre propre position.'),
    environment:m('Сильнее раскрывают переговоры, партнёрство и работа, где важны доверие и контакт.','Келіссөз, серіктестік және сенім маңызды жұмыс сізді жақсы ашады.','Negotiation, partnership, and trust-based work bring out your best.','La négociation, le partenariat et le travail fondé sur la confiance vous révèlent.'),
    experiment:m('Проведите один непростой разговор и письменно зафиксируйте общую договорённость.','Бір күрделі әңгімені өткізіп, ортақ келісімді жазып қойыңыз.','Have one difficult conversation and write down the shared agreement.','Menez une conversation difficile et notez clairement l’accord commun.')
  },
  '3':{
    strength:m('Находите свежую форму для идеи и умеете сделать её понятной и заметной.','Идеяға жаңа пішін тауып, оны түсінікті әрі көрінетін ете аласыз.','You find a fresh form for an idea and make it clear and noticeable.','Vous trouvez une forme neuve pour une idée et la rendez claire et visible.'),
    shadow:m('Поток новых задумок может оттеснять скучную, но важную доводку.','Жаңа ойлар көп болып, маңызды аяқтау жұмысы кейін қалуы мүмкін.','New ideas can crowd out the less exciting work of finishing.','Les nouvelles idées peuvent repousser le travail moins séduisant de finition.'),
    environment:m('Нужны свобода выражения, живая обратная связь и право пробовать несколько вариантов.','Ойды еркін жеткізу, тірі кері байланыс және бірнеше нұсқаны сынау мүмкіндігі керек.','You thrive with room to express, live feedback, and permission to try variants.','Vous progressez avec liberté d’expression, retours directs et droit d’essayer.'),
    experiment:m('Соберите один законченный материал: текст, макет, видео или короткую презентацию.','Бір аяқталған материал жасаңыз: мәтін, макет, видео не қысқа таныстырылым.','Finish one piece: a text, mockup, video, or short presentation.','Terminez une création : texte, maquette, vidéo ou courte présentation.')
  },
  '4':{
    strength:m('Превращаете хаос в понятный порядок, который выдерживает повторение и нагрузку.','Ретсіздікті қайталанатын әрі жүктемеге шыдайтын түсінікті тәртіпке айналдырасыз.','You turn chaos into a clear system that holds up under repetition and load.','Vous transformez le chaos en système clair, durable et reproductible.'),
    shadow:m('Желание всё предусмотреть может замедлить старт или сделать правила слишком жёсткими.','Бәрін алдын ала ойлау бастаманы баяулатып, ережені тым қатаң етуі мүмкін.','Planning for everything can delay the start or make rules too rigid.','Vouloir tout prévoir peut retarder le départ ou rigidifier les règles.'),
    environment:m('Подходят процессы с ясной ответственностью, стандартами качества и видимым прогрессом.','Жауапкершілігі анық, сапа өлшемі және көрінетін ілгерілеуі бар жұмыс сай келеді.','Clear ownership, quality standards, and visible progress suit you.','Responsabilités claires, standards de qualité et progrès visible vous conviennent.'),
    experiment:m('Возьмите один повторяющийся процесс и уберите из него лишний шаг или путаницу.','Бір қайталанатын үдерісті алып, артық қадамды не шатасуды жойыңыз.','Take one repeated process and remove one needless step or source of confusion.','Prenez un processus répétitif et retirez une étape inutile ou une confusion.')
  },
  '5':{
    strength:m('Быстро осваиваетесь в новой обстановке и замечаете возможности там, где другим непривычно.','Жаңа ортаға тез бейімделіп, өзгелерге бейтаныс жерде мүмкіндік көресіз.','You adapt quickly and spot opportunity in unfamiliar situations.','Vous vous adaptez vite et repérez des possibilités dans l’inconnu.'),
    shadow:m('Постоянная тяга к новизне может мешать накопить глубину и устойчивый результат.','Жаңалыққа тұрақты ұмтылыс тереңдік пен тұрақты нәтиже жинауға кедергі болуы мүмкін.','A constant pull toward novelty can prevent depth and durable results.','La recherche constante de nouveauté peut empêcher profondeur et continuité.'),
    environment:m('Лучше работают короткие циклы, разнообразные задачи, движение и свобода менять способ.','Қысқа цикл, әртүрлі міндет, қозғалыс және тәсілді өзгерту еркіндігі жақсы әсер етеді.','Short cycles, varied tasks, movement, and flexibility work well for you.','Cycles courts, tâches variées, mouvement et souplesse vous stimulent.'),
    experiment:m('Попробуйте один новый формат, но заранее определите критерий, по которому решите продолжать или остановиться.','Бір жаңа форматты сынап, жалғастыру не тоқтату өлшемін алдын ала белгілеңіз.','Try one new format and set the rule for continuing or stopping in advance.','Testez un nouveau format et fixez d’avance le critère pour continuer ou arrêter.')
  },
  '6':{
    strength:m('Удерживаете качество и заботитесь, чтобы результат был действительно удобен людям.','Сапаны ұстап, нәтиженің адамдарға шынымен ыңғайлы болуын ойлайсыз.','You protect quality and make sure the result truly works for people.','Vous protégez la qualité et veillez à l’utilité réelle pour les personnes.'),
    shadow:m('Забота обо всех может незаметно превратиться в лишнюю нагрузку и трудность сказать «нет».','Барлығына қамқорлық артық жүкке және «жоқ» деудің қиындығына айналуы мүмкін.','Caring for everyone can quietly become overload and difficulty saying no.','Prendre soin de tous peut devenir surcharge et difficulté à dire non.'),
    environment:m('Подходят сервис, образование, качество и команды, где ценят надёжность и человеческое отношение.','Қызмет көрсету, білім, сапа және адамға мән беретін команда сай келеді.','Service, education, quality work, and humane teams suit you.','Service, éducation, qualité et équipes humaines vous conviennent.'),
    experiment:m('Улучшите один маленький момент для пользователя и отдельно обозначьте границу своей ответственности.','Пайдаланушы үшін бір шағын нәрсені жақсартып, өз жауапкершілік шегіңізді белгілеңіз.','Improve one small user experience and state one boundary of your responsibility.','Améliorez un détail pour l’utilisateur et posez une limite claire à votre responsabilité.')
  },
  '7':{
    strength:m('Докапываетесь до причины, отделяете факты от шума и находите неочевидную связь.','Себепке дейін жетіп, деректі шудан ажыратып, жасырын байланысты табасыз.','You dig for causes, separate signal from noise, and find hidden connections.','Vous cherchez les causes, séparez le signal du bruit et trouvez les liens cachés.'),
    shadow:m('Глубокий анализ может затянуть решение или увести в одиночество без обратной связи.','Терең талдау шешімді созып, кері байланыссыз жалғыз жұмысқа әкетуі мүмкін.','Deep analysis can delay decisions or isolate you from feedback.','L’analyse profonde peut retarder la décision ou vous isoler des retours.'),
    environment:m('Нужны сложные вопросы, время на концентрацию, доступ к данным и уважение к доказательствам.','Күрделі сұрақ, назар аударуға уақыт, дерек және дәлелге құрмет керек.','You need hard questions, focus time, access to data, and respect for evidence.','Il vous faut des questions difficiles, du temps concentré, des données et le respect des preuves.'),
    experiment:m('Разберите одну проблему до причины, а вывод изложите другому человеку в пяти понятных предложениях.','Бір мәселенің себебін тауып, қорытындыны бес түсінікті сөйлеммен басқа адамға жеткізіңіз.','Trace one problem to its cause, then explain the conclusion in five clear sentences.','Remontez à la cause d’un problème puis expliquez la conclusion en cinq phrases claires.')
  },
  '8':{
    strength:m('Видите, как соединить людей, деньги и процессы ради крупного измеримого результата.','Адам, қаржы және үдерісті үлкен өлшенетін нәтиже үшін біріктіре аласыз.','You connect people, money, and processes to produce measurable scale.','Vous reliez personnes, argent et processus pour créer un résultat mesurable.'),
    shadow:m('Фокус на цифрах и скорости может заслонить цену результата для команды и клиентов.','Сан мен жылдамдыққа назар нәтиженің команда мен клиентке бағасын жасыруы мүмкін.','Focus on numbers and speed can hide the human cost of the result.','Le goût des chiffres et de la vitesse peut masquer le coût humain du résultat.'),
    environment:m('Подходят цели с полномочиями, ресурсами, прозрачными показателями и ответственностью за итог.','Өкілеттік, ресурс, ашық көрсеткіш және қорытынды жауапкершілігі бар мақсаттар сай келеді.','Goals with authority, resources, clear measures, and ownership suit you.','Les objectifs avec autorité, ressources, mesures claires et responsabilité vous conviennent.'),
    experiment:m('Выберите один показатель, найдите главное ограничение и проверьте одно действие, способное его сдвинуть.','Бір көрсеткішті таңдап, негізгі шектеуді тауып, оны жылжытатын бір әрекетті сынаңыз.','Choose one metric, find its main constraint, and test one action that could move it.','Choisissez un indicateur, trouvez sa contrainte principale et testez une action pour la déplacer.')
  },
  '9':{
    strength:m('Связываете отдельные действия с общей картиной и помогаете людям не терять смысл.','Жеке әрекеттерді жалпы көрініспен байланыстырып, адамдарға мағынаны жоғалтпауға көмектесесіз.','You connect individual actions to the bigger picture and help people keep meaning in sight.','Vous reliez les actions à l’ensemble et aidez les personnes à garder le sens.'),
    shadow:m('Большая идея может оставаться красивой, если не перевести её в сроки, роли и проверяемый результат.','Үлкен идея мерзімге, рөлге және тексерілетін нәтижеге айналмаса, жай әдемі ой болып қалуы мүмкін.','A big idea stays abstract unless it becomes deadlines, roles, and testable outcomes.','Une grande idée reste abstraite sans délais, rôles et résultat vérifiable.'),
    environment:m('Раскрывают обучение, наставничество, общественно полезные проекты и работа с долгим горизонтом.','Оқыту, тәлімгерлік, қоғамға пайдалы жоба және ұзақ мерзімді жұмыс сай келеді.','Teaching, mentoring, public-value projects, and long horizons bring out your best.','Enseignement, mentorat, projets utiles et vision longue vous révèlent.'),
    experiment:m('Объясните одному человеку, зачем нужна текущая задача, и договоритесь о ближайшем конкретном шаге.','Бір адамға қазіргі міндеттің не үшін керегін түсіндіріп, келесі нақты қадамды келісіңіз.','Explain why one current task matters and agree on the next concrete step.','Expliquez le sens d’une tâche actuelle et convenez de la prochaine étape concrète.')
  }
};

const numerology = {
  id:'numerology',icon:'🔢',count:18,entertainment:false,dateRequired:true,
  title:m('Карьера + число даты','Мансап + туған күн саны','Career + birth-date number','Carrière + nombre de naissance'),
  intro:m('Сначала оцениваем реальные предпочтения, затем добавляем небольшой нумерологический слой по дате. Ответы влияют на 80%, дата — на 20%.','Алдымен нақты қалауды бағалаймыз, кейін күн бойынша шағын нумерологиялық қабат қосамыз. Жауап 80%, күн 20%.','First we score real preferences, then add a small numerology layer from the birth date. Answers count for 80%; the date for 20%.','Nous évaluons d’abord les préférences réelles, puis ajoutons une petite couche numérologique. Réponses 80 %, date 20 %.'),
  badge:m('18 вопросов · число даты','18 сұрақ · туған күн саны','18 questions · birth-date number','18 questions · nombre de naissance'),
  disclaimer:m('Нумерологическая часть рассчитана по числу даты и дополняет ответы. Дата не определяет профессию; насколько этот слой откликается, каждый решает сам. Не используйте результат как единственное основание для выбора карьеры.','Нумерологиялық бөлік туған күн саны бойынша есептеліп, жауаптарды толықтырады. Күн мамандықты анықтамайды; бұл қабаттың қаншалықты сәйкес келетінін әркім өзі шешеді. Нәтижені мансап таңдаудың жалғыз негізі етпеңіз.', 'The numerology layer is calculated from the birth-date number and complements your answers. A date does not determine a career; each person decides how strongly this layer resonates. Do not use the result as the sole basis for a career choice.', 'La couche numérologique est calculée à partir du nombre de naissance et complète vos réponses. Une date ne détermine pas un métier ; chacun décide dans quelle mesure cette lecture lui parle. N’utilisez pas ce résultat comme seul fondement d’un choix de carrière.'),
  scales:Object.fromEntries([
    [1,'🚀','#d86c35','Инициатор','Бастаушы','Initiator','Initiateur','запускать и вести','бастау және жетелеу','start and lead','lancer et guider'],[2,'🤝','#379b91','Дипломат','Дипломат','Diplomat','Diplomate','соединять людей','адамдарды біріктіру','connect people','relier les personnes'],[3,'🎨','#ad58bd','Создатель','Жасаушы','Creator','Créateur','выражать идеи','идеяны білдіру','express ideas','exprimer des idées'],[4,'🧱','#65758d','Системщик','Жүйе құрушы','System builder','Bâtisseur de systèmes','строить порядок','тәртіп құру','build order','construire l’ordre'],[5,'🧭','#3f90b2','Исследователь перемен','Өзгеріс зерттеушісі','Change explorer','Explorateur du changement','пробовать новое','жаңаны сынау','try the new','essayer le nouveau'],[6,'💛','#d28648','Заботливый организатор','Қамқор ұйымдастырушы','Caring organizer','Organisateur attentionné','создавать пользу','пайда жасау','create care and value','créer soin et valeur'],[7,'🔬','#674fc3','Аналитик глубины','Терең талдаушы','Deep analyst','Analyste profond','исследовать глубоко','терең зерттеу','investigate deeply','analyser en profondeur'],[8,'🏆','#b65a54','Управленец результата','Нәтиже басқарушы','Results driver','Pilote de résultats','масштабировать результат','нәтижені өсіру','scale results','amplifier les résultats'],[9,'🌍','#4b8c69','Наставник смысла','Мағына тәлімгері','Purpose mentor','Mentor de sens','видеть общую картину','жалпы көріністі көру','see the bigger picture','voir l’ensemble']
  ].map(([id,emoji,color,ru,kk,en,fr,ruA,kkA,enA,frA])=>{
    const details=numerologyDetails[String(id)];
    return [String(id),p(emoji,color,m(ru,kk,en,fr),m(ru,kk,en,fr),m(`Вам близко ${ruA}.`,`${kkA} сізге жақын.`,`You are drawn to ${enA}.`,`Vous aimez ${frA}.`),details.strength,details.shadow,details.environment,details.experiment,m(ruA,kkA,enA,frA),m('Число подсказывает настроение, но дедлайн всё равно настоящий.','Сан көңіл күй береді, дедлайн бәрібір нақты.','The number sets a mood; the deadline is still real.','Le nombre donne une ambiance ; le délai reste réel.'))];
  })),
  questions:[
    q('1','Мне нравится запускать новое дело раньше других','Жаңа істі бірінші бастаған ұнайды','I like being first to start something new','J’aime lancer une nouvelle chose'),q('1','Могу брать на себя окончательное решение','Соңғы шешімді қабылдауға дайынмын','I can take responsibility for the final decision','Je peux prendre la décision finale'),
    q('2','Мне легко замечать интересы обеих сторон','Екі жақтың мүддесін оңай байқаймын','I easily notice both sides’ interests','Je remarque facilement les intérêts des deux côtés'),q('2','Предпочитаю создавать союз, а не побеждать в споре','Дауда жеңгеннен одақ құрғанды қалаймын','I prefer building agreement over winning an argument','Je préfère construire un accord que gagner un débat'),
    q('3','Мне важно выражать идеи через слова, образ или сцену','Идеяны сөз, бейне не сахна арқылы білдіру маңызды','I want to express ideas through words, images, or performance','Je veux exprimer des idées par les mots, l’image ou la scène'),q('3','Новые идеи заряжают меня сильнее готовых инструкций','Дайын нұсқаудан жаңа идея көбірек қуат береді','New ideas energize me more than ready-made instructions','Les idées nouvelles me stimulent plus que les instructions'),
    q('4','Мне нравится создавать понятный порядок','Түсінікті тәртіп құру ұнайды','I enjoy creating clear order','J’aime créer un ordre clair'),q('4','Стабильная система радует больше яркого старта','Тұрақты жүйе жарқын бастамадан маңызды','A stable system pleases me more than a flashy start','Un système stable me plaît plus qu’un départ spectaculaire'),
    q('5','Меня привлекают перемены, поездки и новые форматы','Өзгеріс, сапар және жаңа формат қызықтырады','Change, travel, and new formats attract me','Le changement, les voyages et les nouveaux formats m’attirent'),q('5','Я быстро осваиваюсь в незнакомой обстановке','Бейтаныс ортаға тез бейімделемін','I adapt quickly in unfamiliar settings','Je m’adapte vite à un environnement inconnu'),
    q('6','Мне важно, чтобы результат улучшал чью-то жизнь','Нәтиже біреудің өмірін жақсартқаны маңызды','I want my work to improve someone’s life','Je veux que mon travail améliore une vie'),q('6','Люблю создавать комфорт и удерживать качество','Жайлылық жасап, сапаны ұстап тұру ұнайды','I enjoy creating comfort and maintaining quality','J’aime créer du confort et maintenir la qualité'),
    q('7','Мне интересно докапываться до скрытой причины','Жасырын себепке дейін зерттеу қызық','I enjoy digging for hidden causes','J’aime chercher les causes cachées'),q('7','Могу долго работать один над сложной темой','Күрделі тақырыппен жалғыз ұзақ жұмыс істей аламын','I can work alone on a hard topic for a long time','Je peux travailler seul longtemps sur un sujet difficile'),
    q('8','Меня мотивирует измеримый крупный результат','Өлшенетін үлкен нәтиже ынталандырады','Large measurable results motivate me','Un grand résultat mesurable me motive'),q('8','Мне интересно управлять ресурсами и ростом','Ресурс пен өсуді басқару қызық','I am interested in managing resources and growth','La gestion des ressources et de la croissance m’intéresse'),
    q('9','Мне важно видеть смысл и общую картину','Мағына мен жалпы көріністі көру маңызды','Meaning and the bigger picture matter to me','Le sens et la vue d’ensemble comptent'),q('9','Мне нравится делиться опытом и направлять','Тәжірибе бөлісіп, бағыт беру ұнайды','I enjoy sharing experience and guiding others','J’aime partager mon expérience et guider')]
};

export const tests = { strengths, trajectory, numerology };

